/**
 * Growth rule type enum shared by points and experience rules.
 */
export enum GrowthRuleTypeEnum {
  // Forum
  CREATE_TOPIC = 1,
  CREATE_REPLY = 2,
  TOPIC_LIKED = 3,
  REPLY_LIKED = 4,
  TOPIC_FAVORITED = 5,
  DAILY_CHECK_IN = 6,
  ADMIN = 7,
  TOPIC_VIEW = 8,
  TOPIC_REPORT = 9,
  /** 帖子被评论 */
  TOPIC_COMMENT = 16,

  // Comment
  CREATE_COMMENT = 10,
  COMMENT_LIKED = 11,
  COMMENT_REPORT = 12,

  // Comic work
  COMIC_WORK_VIEW = 100,
  COMIC_WORK_LIKE = 101,
  COMIC_WORK_FAVORITE = 102,
  COMIC_WORK_REPORT = 103,
  /** 漫画作品评论 */
  COMIC_WORK_COMMENT = 104,

  // Novel work
  NOVEL_WORK_VIEW = 200,
  NOVEL_WORK_LIKE = 201,
  NOVEL_WORK_FAVORITE = 202,
  NOVEL_WORK_REPORT = 203,
  /** 小说作品评论 */
  NOVEL_WORK_COMMENT = 204,

  // Comic chapter
  COMIC_CHAPTER_READ = 300,
  COMIC_CHAPTER_LIKE = 301,
  COMIC_CHAPTER_PURCHASE = 302,
  COMIC_CHAPTER_DOWNLOAD = 303,
  COMIC_CHAPTER_EXCHANGE = 304,
  COMIC_CHAPTER_REPORT = 305,
  /** 漫画章节评论 */
  COMIC_CHAPTER_COMMENT = 306,

  // Novel chapter
  NOVEL_CHAPTER_READ = 400,
  NOVEL_CHAPTER_LIKE = 401,
  NOVEL_CHAPTER_PURCHASE = 402,
  NOVEL_CHAPTER_DOWNLOAD = 403,
  NOVEL_CHAPTER_EXCHANGE = 404,
  NOVEL_CHAPTER_REPORT = 405,
  /** 小说章节评论 */
  NOVEL_CHAPTER_COMMENT = 406,

  // Badge & Achievement
  BADGE_EARNED = 600,
  PROFILE_COMPLETE = 601,
  AVATAR_UPLOAD = 602,

  // Social interaction
  FOLLOW_USER = 700,
  BE_FOLLOWED = 701,
  SHARE_CONTENT = 702,
  INVITE_USER = 703,

  // Report handling
  REPORT_VALID = 800,
  REPORT_INVALID = 801,
}
