export * from '../../../../prisma/prismaClient/client'
export * from '../../../../prisma/prismaClient/models'
export * from './base.service'
export * from './prisma.service'
export * from './prisma.types'
export * from 'nestjs-prisma/dist/custom'
