import {
  appBadge,
  appUserBadgeAssignment,
  appUserBrowseLog,
  appUserComment,
  appUserDownloadRecord,
  appUserExperienceRule,
  appUserFavorite,
  appUserFollow,
  appUserLevelRule,
  appUserLike,
  appUserNotification,
  appUserNotificationPreference,
  appUserPointRule,
  appUserPurchaseRecord,
  appUserReport,
  appUserWorkReadingState,
  forumModeratorSectionRelation,
  forumTopicTagRelation,
  systemConfig,
  systemDictionary,
  systemDictionaryItem,
  systemRequestLog,
  systemSensitiveWord,
} from '@db/schema'

describe('table naming normalization schema exports', () => {
  it('exposes the renamed schema symbols from the public barrel', () => {
    expect([
      appBadge,
      appUserBadgeAssignment,
      appUserBrowseLog,
      appUserComment,
      appUserDownloadRecord,
      appUserExperienceRule,
      appUserFavorite,
      appUserFollow,
      appUserLevelRule,
      appUserLike,
      appUserNotification,
      appUserNotificationPreference,
      appUserPointRule,
      appUserPurchaseRecord,
      appUserReport,
      appUserWorkReadingState,
      forumModeratorSectionRelation,
      forumTopicTagRelation,
      systemConfig,
      systemDictionary,
      systemDictionaryItem,
      systemRequestLog,
      systemSensitiveWord,
    ]).toHaveLength(23)
  })
})
