export enum MessageNotificationTypeEnum {
  COMMENT_REPLY = 'COMMENT_REPLY',
  COMMENT_LIKE = 'COMMENT_LIKE',
  CONTENT_FAVORITE = 'CONTENT_FAVORITE',
  USER_FOLLOW = 'USER_FOLLOW',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
}
