
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  AdminUser: 'AdminUser',
  ClientConfig: 'ClientConfig',
  ClientNotice: 'ClientNotice',
  ClientPage: 'ClientPage',
  ClientUser: 'ClientUser',
  RequestLog: 'RequestLog',
  Dictionary: 'Dictionary',
  DictionaryItem: 'DictionaryItem',
  WorkAuthorRoleType: 'WorkAuthorRoleType',
  WorkAuthorRole: 'WorkAuthorRole',
  WorkAuthor: 'WorkAuthor',
  WorkComicAuthor: 'WorkComicAuthor',
  WorkComicCategory: 'WorkComicCategory',
  WorkComicChapter: 'WorkComicChapter',
  WorkComicVersion: 'WorkComicVersion',
  WorkComic: 'WorkComic',
  WorkCategory: 'WorkCategory',
  WorkCategoryContentType: 'WorkCategoryContentType',
  WorkContentType: 'WorkContentType'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AdminUserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  avatar: 'avatar',
  mobile: 'mobile',
  isEnabled: 'isEnabled',
  role: 'role',
  lastLoginAt: 'lastLoginAt',
  lastLoginIp: 'lastLoginIp',
  loginFailAt: 'loginFailAt',
  loginFailIp: 'loginFailIp',
  loginFailCount: 'loginFailCount',
  isLocked: 'isLocked',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AdminUserScalarFieldEnum = (typeof AdminUserScalarFieldEnum)[keyof typeof AdminUserScalarFieldEnum]


export const RelationLoadStrategy = {
  query: 'query',
  join: 'join'
} as const

export type RelationLoadStrategy = (typeof RelationLoadStrategy)[keyof typeof RelationLoadStrategy]


export const ClientConfigScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClientConfigScalarFieldEnum = (typeof ClientConfigScalarFieldEnum)[keyof typeof ClientConfigScalarFieldEnum]


export const ClientNoticeScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  noticeType: 'noticeType',
  priorityLevel: 'priorityLevel',
  publishStartTime: 'publishStartTime',
  publishEndTime: 'publishEndTime',
  pageId: 'pageId',
  popupBackgroundImage: 'popupBackgroundImage',
  isPublished: 'isPublished',
  enablePlatform: 'enablePlatform',
  isPinned: 'isPinned',
  showAsPopup: 'showAsPopup',
  readCount: 'readCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClientNoticeScalarFieldEnum = (typeof ClientNoticeScalarFieldEnum)[keyof typeof ClientNoticeScalarFieldEnum]


export const ClientPageScalarFieldEnum = {
  id: 'id',
  code: 'code',
  path: 'path',
  name: 'name',
  title: 'title',
  accessLevel: 'accessLevel',
  isEnabled: 'isEnabled',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClientPageScalarFieldEnum = (typeof ClientPageScalarFieldEnum)[keyof typeof ClientPageScalarFieldEnum]


export const ClientUserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  nickname: 'nickname',
  avatarUrl: 'avatarUrl',
  phoneNumber: 'phoneNumber',
  emailAddress: 'emailAddress',
  isEnabled: 'isEnabled',
  genderType: 'genderType',
  birthDate: 'birthDate',
  lastLoginAt: 'lastLoginAt',
  lastLoginIp: 'lastLoginIp',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type ClientUserScalarFieldEnum = (typeof ClientUserScalarFieldEnum)[keyof typeof ClientUserScalarFieldEnum]


export const RequestLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  username: 'username',
  apiType: 'apiType',
  ip: 'ip',
  method: 'method',
  path: 'path',
  params: 'params',
  actionType: 'actionType',
  isSuccess: 'isSuccess',
  userAgent: 'userAgent',
  device: 'device',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RequestLogScalarFieldEnum = (typeof RequestLogScalarFieldEnum)[keyof typeof RequestLogScalarFieldEnum]


export const DictionaryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  cover: 'cover',
  isEnabled: 'isEnabled',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type DictionaryScalarFieldEnum = (typeof DictionaryScalarFieldEnum)[keyof typeof DictionaryScalarFieldEnum]


export const DictionaryItemScalarFieldEnum = {
  id: 'id',
  dictionaryCode: 'dictionaryCode',
  name: 'name',
  code: 'code',
  order: 'order',
  cover: 'cover',
  isEnabled: 'isEnabled',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type DictionaryItemScalarFieldEnum = (typeof DictionaryItemScalarFieldEnum)[keyof typeof DictionaryItemScalarFieldEnum]


export const WorkAuthorRoleTypeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  description: 'description',
  isEnabled: 'isEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkAuthorRoleTypeScalarFieldEnum = (typeof WorkAuthorRoleTypeScalarFieldEnum)[keyof typeof WorkAuthorRoleTypeScalarFieldEnum]


export const WorkAuthorRoleScalarFieldEnum = {
  id: 'id',
  authorId: 'authorId',
  roleTypeId: 'roleTypeId',
  isPrimary: 'isPrimary',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkAuthorRoleScalarFieldEnum = (typeof WorkAuthorRoleScalarFieldEnum)[keyof typeof WorkAuthorRoleScalarFieldEnum]


export const WorkAuthorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  avatar: 'avatar',
  description: 'description',
  isEnabled: 'isEnabled',
  nationality: 'nationality',
  gender: 'gender',
  worksCount: 'worksCount',
  followersCount: 'followersCount',
  featured: 'featured',
  socialLinks: 'socialLinks',
  remark: 'remark',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type WorkAuthorScalarFieldEnum = (typeof WorkAuthorScalarFieldEnum)[keyof typeof WorkAuthorScalarFieldEnum]


export const WorkComicAuthorScalarFieldEnum = {
  id: 'id',
  comicId: 'comicId',
  authorId: 'authorId',
  roleType: 'roleType',
  isPrimary: 'isPrimary',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkComicAuthorScalarFieldEnum = (typeof WorkComicAuthorScalarFieldEnum)[keyof typeof WorkComicAuthorScalarFieldEnum]


export const WorkComicCategoryScalarFieldEnum = {
  comicId: 'comicId',
  categoryId: 'categoryId',
  isPrimary: 'isPrimary',
  weight: 'weight',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkComicCategoryScalarFieldEnum = (typeof WorkComicCategoryScalarFieldEnum)[keyof typeof WorkComicCategoryScalarFieldEnum]


export const WorkComicChapterScalarFieldEnum = {
  id: 'id',
  title: 'title',
  subtitle: 'subtitle',
  isPublished: 'isPublished',
  comicId: 'comicId',
  versionId: 'versionId',
  chapterNumber: 'chapterNumber',
  readRule: 'readRule',
  purchaseAmount: 'purchaseAmount',
  contents: 'contents',
  isPreview: 'isPreview',
  publishAt: 'publishAt',
  viewCount: 'viewCount',
  likeCount: 'likeCount',
  commentCount: 'commentCount',
  remark: 'remark',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type WorkComicChapterScalarFieldEnum = (typeof WorkComicChapterScalarFieldEnum)[keyof typeof WorkComicChapterScalarFieldEnum]


export const WorkComicVersionScalarFieldEnum = {
  id: 'id',
  comicId: 'comicId',
  versionName: 'versionName',
  language: 'language',
  translatorGroup: 'translatorGroup',
  description: 'description',
  isRecommended: 'isRecommended',
  isPublished: 'isPublished',
  publishAt: 'publishAt',
  lastUpdated: 'lastUpdated',
  totalViews: 'totalViews',
  favoriteCount: 'favoriteCount',
  likeCount: 'likeCount',
  rating: 'rating',
  ratingCount: 'ratingCount',
  readRule: 'readRule',
  purchaseAmount: 'purchaseAmount',
  copyright: 'copyright',
  disclaimer: 'disclaimer',
  remark: 'remark',
  sortOrder: 'sortOrder',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkComicVersionScalarFieldEnum = (typeof WorkComicVersionScalarFieldEnum)[keyof typeof WorkComicVersionScalarFieldEnum]


export const WorkComicScalarFieldEnum = {
  id: 'id',
  name: 'name',
  alias: 'alias',
  cover: 'cover',
  popularity: 'popularity',
  popularityWeight: 'popularityWeight',
  language: 'language',
  region: 'region',
  ageRating: 'ageRating',
  isPublished: 'isPublished',
  publishAt: 'publishAt',
  lastUpdated: 'lastUpdated',
  description: 'description',
  publisher: 'publisher',
  originalSource: 'originalSource',
  serialStatus: 'serialStatus',
  totalChapters: 'totalChapters',
  totalViews: 'totalViews',
  favoriteCount: 'favoriteCount',
  commentCount: 'commentCount',
  likeCount: 'likeCount',
  rating: 'rating',
  ratingCount: 'ratingCount',
  canDownload: 'canDownload',
  canComment: 'canComment',
  readRule: 'readRule',
  purchaseAmount: 'purchaseAmount',
  seoTitle: 'seoTitle',
  seoDescription: 'seoDescription',
  seoKeywords: 'seoKeywords',
  recommendWeight: 'recommendWeight',
  isRecommended: 'isRecommended',
  isHot: 'isHot',
  isNew: 'isNew',
  copyright: 'copyright',
  disclaimer: 'disclaimer',
  remark: 'remark',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkComicScalarFieldEnum = (typeof WorkComicScalarFieldEnum)[keyof typeof WorkComicScalarFieldEnum]


export const WorkCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  icon: 'icon',
  popularity: 'popularity',
  popularityWeight: 'popularityWeight',
  order: 'order',
  isEnabled: 'isEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkCategoryScalarFieldEnum = (typeof WorkCategoryScalarFieldEnum)[keyof typeof WorkCategoryScalarFieldEnum]


export const WorkCategoryContentTypeScalarFieldEnum = {
  categoryId: 'categoryId',
  contentTypeId: 'contentTypeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkCategoryContentTypeScalarFieldEnum = (typeof WorkCategoryContentTypeScalarFieldEnum)[keyof typeof WorkCategoryContentTypeScalarFieldEnum]


export const WorkContentTypeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  isEnabled: 'isEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkContentTypeScalarFieldEnum = (typeof WorkContentTypeScalarFieldEnum)[keyof typeof WorkContentTypeScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull'
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

