CREATE TABLE "admin_menu" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "admin_menu_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(120) NOT NULL CONSTRAINT "admin_menu_code_key" UNIQUE,
	"parent_id" integer,
	"type" varchar(20) DEFAULT 'menu' NOT NULL,
	"title" varchar(80) NOT NULL,
	"path" varchar(200) NOT NULL,
	"name" varchar(120),
	"component" varchar(240),
	"redirect" varchar(200),
	"icon" varchar(80),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_visible" boolean DEFAULT true NOT NULL,
	"is_enabled" boolean DEFAULT true NOT NULL,
	"keep_alive" boolean DEFAULT false NOT NULL,
	"external_link" varchar(300),
	"created_at" timestamp(6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp(6) with time zone NOT NULL,
	CONSTRAINT "admin_menu_type_chk" CHECK ("type" in ('catalog', 'menu')),
	CONSTRAINT "admin_menu_code_not_blank_chk" CHECK (length(trim("code")) > 0)
);
--> statement-breakpoint
CREATE TABLE "admin_permission" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "admin_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(160) NOT NULL CONSTRAINT "admin_permission_code_key" UNIQUE,
	"name" varchar(120) NOT NULL,
	"group_code" varchar(120) NOT NULL,
	"description" varchar(300),
	"source" varchar(30) DEFAULT 'api' NOT NULL,
	"is_enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp(6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp(6) with time zone NOT NULL,
	CONSTRAINT "admin_permission_code_not_blank_chk" CHECK (length(trim("code")) > 0),
	CONSTRAINT "admin_permission_source_chk" CHECK ("source" in ('api'))
);
--> statement-breakpoint
CREATE TABLE "admin_rbac_revision" (
	"code" varchar(30) PRIMARY KEY,
	"revision" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp(6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "admin_role" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "admin_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(80) NOT NULL CONSTRAINT "admin_role_code_key" UNIQUE,
	"name" varchar(80) NOT NULL,
	"description" varchar(300),
	"is_system" boolean DEFAULT false NOT NULL,
	"is_enabled" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp(6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp(6) with time zone NOT NULL,
	CONSTRAINT "admin_role_code_not_blank_chk" CHECK (length(trim("code")) > 0)
);
--> statement-breakpoint
CREATE TABLE "admin_role_menu" (
	"role_id" integer,
	"menu_id" integer,
	"created_at" timestamp(6) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "admin_role_menu_pkey" PRIMARY KEY("role_id","menu_id")
);
--> statement-breakpoint
CREATE TABLE "admin_role_permission" (
	"role_id" integer,
	"permission_id" integer,
	"created_at" timestamp(6) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "admin_role_permission_pkey" PRIMARY KEY("role_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "admin_user_role" (
	"admin_user_id" integer,
	"role_id" integer,
	"created_at" timestamp(6) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "admin_user_role_pkey" PRIMARY KEY("admin_user_id","role_id")
);
--> statement-breakpoint
INSERT INTO "admin_rbac_revision" ("code", "revision", "updated_at") VALUES ('admin', 1, now()) ON CONFLICT ("code") DO NOTHING;--> statement-breakpoint
INSERT INTO "admin_role" ("code", "name", "description", "is_system", "is_enabled", "sort_order", "updated_at") VALUES ('super_admin', '超级管理员', '系统内置超级管理员，默认拥有全部权限和菜单', true, true, 1, now()) ON CONFLICT ("code") DO UPDATE SET "name" = EXCLUDED."name", "description" = EXCLUDED."description", "is_system" = true, "is_enabled" = true, "sort_order" = EXCLUDED."sort_order", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_role" ("code", "name", "description", "is_system", "is_enabled", "sort_order", "updated_at") VALUES ('normal_admin', '普通管理员', '系统内置普通管理员，仅保留基础自助能力', true, true, 2, now()) ON CONFLICT ("code") DO UPDATE SET "name" = EXCLUDED."name", "description" = EXCLUDED."description", "is_system" = true, "is_enabled" = true, "sort_order" = EXCLUDED."sort_order", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_user_role" ("admin_user_id", "role_id") SELECT "admin_user"."id", "admin_role"."id" FROM "admin_user" INNER JOIN "admin_role" ON "admin_role"."code" = CASE WHEN "admin_user"."role" = 1 THEN 'super_admin' ELSE 'normal_admin' END ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('dashboard', NULL, 'catalog', '仪表盘', '/dashboard', 'Dashboard', NULL, '/dashboard/analytics', 'lucide:layout-dashboard', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('dashboard_analytics', (SELECT "id" FROM "admin_menu" WHERE "code" = 'dashboard'), 'menu', '分析页', '/dashboard/analytics', 'Analytics', '/dashboard/analytics/index', NULL, 'lucide:area-chart', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('dashboard_workspace', (SELECT "id" FROM "admin_menu" WHERE "code" = 'dashboard'), 'menu', '工作台', '/dashboard/workspace', 'Workspace', '/dashboard/workspace/index', NULL, 'carbon:workspace', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('content_manager', NULL, 'catalog', '内容管理', '/content-manager', 'ContentManager', NULL, '/content-manager/comic-manager', 'majesticons:book-open-line', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('content_comic_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'content_manager'), 'menu', '漫画', '/content-manager/comic-manager', 'ComicManager', '/content-manager/comic-manager/core/index', NULL, 'codex:dot-circle', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('content_novel_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'content_manager'), 'menu', '小说', '/content-manager/novel-manager', 'NovelManager', '/content-manager/novel-manager/core/index', NULL, 'codex:dot-circle', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('content_author_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'content_manager'), 'menu', '作者管理', '/content-manager/author-manager', 'AuthorManager', '/content-manager/author-manager/index', NULL, 'codex:dot-circle', 30, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('content_category_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'content_manager'), 'menu', '分类管理', '/content-manager/category-manager', 'CategoryManager', '/content-manager/category-manager/index', NULL, 'codex:dot-circle', 40, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('content_tag_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'content_manager'), 'menu', '标签管理', '/content-manager/tag-manager', 'TagManager', '/content-manager/tag-manager/index', NULL, 'codex:dot-circle', 50, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('content_emoji_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'content_manager'), 'menu', '表情管理', '/content-manager/emoji-manager', 'ContentEmojiManager', '/content-manager/emoji-manager/index', NULL, 'codex:dot-circle', 60, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('content_governance', NULL, 'catalog', '内容治理', '/content-governance', 'ContentGovernance', NULL, '/content-governance/reports', 'lucide:shield-check', 30, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('content_governance_reports', (SELECT "id" FROM "admin_menu" WHERE "code" = 'content_governance'), 'menu', '举报处理', '/content-governance/reports', 'ContentGovernanceReports', '/content-governance/reports/index', NULL, 'codex:dot-circle', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('content_governance_comments', (SELECT "id" FROM "admin_menu" WHERE "code" = 'content_governance'), 'menu', '评论处理', '/content-governance/comments', 'ContentGovernanceComments', '/content-governance/comments/index', NULL, 'codex:dot-circle', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('forum', NULL, 'catalog', '论坛管理', '/forum', 'Forum', NULL, '/forum/topic', 'lucide:layout-dashboard', 40, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('forum_topic', (SELECT "id" FROM "admin_menu" WHERE "code" = 'forum'), 'menu', '帖子管理', '/forum/topic', 'ForumTopic', '/forum/topic/index', NULL, 'codex:dot-circle', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('forum_moderators', (SELECT "id" FROM "admin_menu" WHERE "code" = 'forum'), 'menu', '版主管理', '/forum/moderators', 'ForumModerators', '/forum/moderators/index', NULL, 'codex:dot-circle', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('forum_sections', (SELECT "id" FROM "admin_menu" WHERE "code" = 'forum'), 'menu', '板块管理', '/forum/sections', 'ForumSections', '/forum/sections/index', NULL, 'codex:dot-circle', 30, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('forum_tags', (SELECT "id" FROM "admin_menu" WHERE "code" = 'forum'), 'menu', '话题管理', '/forum/tags', 'ForumTags', '/forum/tags/index', NULL, 'codex:dot-circle', 40, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('forum_sensitive_word', (SELECT "id" FROM "admin_menu" WHERE "code" = 'forum'), 'menu', '敏感词管理', '/forum/sensitive-word', 'ForumSensitiveWord', '/forum/sensitive-word/index', NULL, 'codex:dot-circle', 50, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('forum_sensitive_word_statistics', (SELECT "id" FROM "admin_menu" WHERE "code" = 'forum'), 'menu', '敏感词统计', '/forum/sensitive-word-statistics', 'ForumSensitiveWordStatistics', '/forum/sensitive-word-statistics/index', NULL, 'codex:dot-circle', 60, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('user_manager', NULL, 'catalog', '用户管理', '/user-manager', 'UserManager', NULL, '/user-manager/profile', 'majesticons:user-line', 50, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('user_profile', (SELECT "id" FROM "admin_menu" WHERE "code" = 'user_manager'), 'menu', '用户信息', '/user-manager/profile', 'UserProfile', '/user-manager/profile/index', NULL, 'codex:dot-circle', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('user_check_in', (SELECT "id" FROM "admin_menu" WHERE "code" = 'user_manager'), 'menu', '签到管理', '/user-manager/check-in', 'UserCheckIn', '/user-manager/check-in/index', NULL, 'codex:dot-circle', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('user_tasks', (SELECT "id" FROM "admin_menu" WHERE "code" = 'user_manager'), 'menu', '任务管理', '/user-manager/tasks', 'UserTasks', '/user-manager/tasks/index', NULL, 'codex:dot-circle', 30, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('user_growth_points', (SELECT "id" FROM "admin_menu" WHERE "code" = 'user_manager'), 'menu', '积分管理', '/user-manager/growth/points', 'UserGrowthPoints', '/user-manager/growth/points/index', NULL, 'codex:dot-circle', 40, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('user_growth_experience', (SELECT "id" FROM "admin_menu" WHERE "code" = 'user_manager'), 'menu', '经验管理', '/user-manager/growth/experience', 'UserGrowthExperience', '/user-manager/growth/experience/index', NULL, 'codex:dot-circle', 50, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('user_growth_level_rules', (SELECT "id" FROM "admin_menu" WHERE "code" = 'user_manager'), 'menu', '等级管理', '/user-manager/growth/level-rules', 'UserGrowthLevelRules', '/user-manager/growth/level-rules/index', NULL, 'codex:dot-circle', 60, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('user_growth_badges', (SELECT "id" FROM "admin_menu" WHERE "code" = 'user_manager'), 'menu', '徽章管理', '/user-manager/growth/badges', 'UserGrowthBadges', '/user-manager/growth/badges/index', NULL, 'codex:dot-circle', 70, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('user_growth_operations', (SELECT "id" FROM "admin_menu" WHERE "code" = 'user_manager'), 'menu', '成长运营', '/user-manager/growth/operations', 'UserGrowthOperations', '/user-manager/growth/operations/index', NULL, 'codex:dot-circle', 80, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('payment_rights', NULL, 'catalog', '支付与权益', '/payment-rights', 'PaymentRightsManager', NULL, '/payment-rights/currency-package', 'majesticons:creditcard-line', 60, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('wallet_currency_package', (SELECT "id" FROM "admin_menu" WHERE "code" = 'payment_rights'), 'menu', '虚拟币充值包', '/payment-rights/currency-package', 'WalletCurrencyPackage', '/payment-rights/currency-package/index', NULL, 'codex:dot-circle', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('coupon_definition', (SELECT "id" FROM "admin_menu" WHERE "code" = 'payment_rights'), 'menu', '券定义', '/payment-rights/coupon-definition', 'CouponDefinition', '/payment-rights/coupon-definition/index', NULL, 'codex:dot-circle', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('payment_order', (SELECT "id" FROM "admin_menu" WHERE "code" = 'payment_rights'), 'menu', '支付订单', '/payment-rights/payment-order', 'PaymentOrder', '/payment-rights/payment-order/index', NULL, 'codex:dot-circle', 30, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('payment_reconcile', (SELECT "id" FROM "admin_menu" WHERE "code" = 'payment_rights'), 'menu', '支付对账', '/payment-rights/payment-reconcile', 'PaymentReconcile', '/payment-rights/payment-reconcile/index', NULL, 'codex:dot-circle', 40, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('membership_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'payment_rights'), 'menu', '会员管理', '/payment-rights/membership', 'MembershipManager', '/payment-rights/membership/index', NULL, 'codex:dot-circle', 50, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('message_manager', NULL, 'catalog', '消息管理', '/message', 'MessageManager', NULL, '/message/notification-templates', 'lucide:message-square-text', 70, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('message_notification_templates', (SELECT "id" FROM "admin_menu" WHERE "code" = 'message_manager'), 'menu', '通知模板', '/message/notification-templates', 'MessageNotificationTemplates', '/message/notification-templates/index', NULL, 'codex:dot-circle', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('message_monitor', (SELECT "id" FROM "admin_menu" WHERE "code" = 'message_manager'), 'menu', '消息运行', '/message/monitor', 'MessageMonitor', '/message/monitor/index', NULL, 'codex:dot-circle', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('message_chat_investigation', (SELECT "id" FROM "admin_menu" WHERE "code" = 'message_manager'), 'menu', '聊天排查', '/message/chat-investigation', 'MessageChatInvestigation', '/message/chat-investigation/index', NULL, 'codex:dot-circle', 30, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('app_manager', NULL, 'catalog', 'APP管理', '/app-manager', 'AppManager', NULL, '/app-manager/announcement', 'majesticons:device-mobile-line', 80, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('app_announcement', (SELECT "id" FROM "admin_menu" WHERE "code" = 'app_manager'), 'menu', '公告管理', '/app-manager/announcement', 'Announcement', '/app-manager/announcement/index', NULL, 'codex:dot-circle', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('app_agreement', (SELECT "id" FROM "admin_menu" WHERE "code" = 'app_manager'), 'menu', '协议管理', '/app-manager/agreement', 'Agreement', '/app-manager/agreement/index', NULL, 'codex:dot-circle', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('app_page_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'app_manager'), 'menu', '页面配置', '/app-manager/page-manager', 'PageManager', '/app-manager/page-manager/index', NULL, 'codex:dot-circle', 30, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('app_config', (SELECT "id" FROM "admin_menu" WHERE "code" = 'app_manager'), 'menu', '应用配置', '/app-manager/app-config', 'AppConfig', '/app-manager/app-config/index', NULL, 'codex:dot-circle', 40, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('app_update', (SELECT "id" FROM "admin_menu" WHERE "code" = 'app_manager'), 'menu', '版本更新', '/app-manager/app-update', 'AppUpdate', '/app-manager/app-update/index', NULL, 'codex:dot-circle', 50, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('statistics', NULL, 'catalog', '统计管理', '/statistics', 'StatisticsManager', NULL, '/statistics/comic', 'lucide:layout-dashboard', 90, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('statistics_comic', (SELECT "id" FROM "admin_menu" WHERE "code" = 'statistics'), 'menu', '漫画统计', '/statistics/comic', 'ComicStatistics', '/statistics/comic/index', NULL, 'lucide:area-chart', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('statistics_novel', (SELECT "id" FROM "admin_menu" WHERE "code" = 'statistics'), 'menu', '小说统计', '/statistics/novel', 'NovelStatistics', '/statistics/novel/index', NULL, 'lucide:area-chart', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('statistics_forum', (SELECT "id" FROM "admin_menu" WHERE "code" = 'statistics'), 'menu', '论坛统计', '/statistics/forum', 'ForumStatistics', '/statistics/forum/index', NULL, 'lucide:area-chart', 30, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('config_manager', NULL, 'catalog', '配置管理', '/config-manager', 'ConfigManager', NULL, '/config-manager/system-config', 'lucide:sliders-horizontal', 100, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('config_system', (SELECT "id" FROM "admin_menu" WHERE "code" = 'config_manager'), 'menu', '系统配置', '/config-manager/system-config', 'SystemConfig', '/config-manager/system-config/index', NULL, 'codex:dot-circle', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('config_payment', (SELECT "id" FROM "admin_menu" WHERE "code" = 'config_manager'), 'menu', '支付配置', '/config-manager/payment-config', 'PaymentConfig', '/config-manager/payment-config/index', NULL, 'codex:dot-circle', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('config_ad', (SELECT "id" FROM "admin_menu" WHERE "code" = 'config_manager'), 'menu', '广告配置', '/config-manager/ad-config', 'AdConfig', '/config-manager/ad-config/index', NULL, 'codex:dot-circle', 30, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_manager', NULL, 'catalog', '系统管理', '/system-manager', 'SystemManager', NULL, '/system-manager/profile', 'majesticons:cog-line', 110, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_profile', (SELECT "id" FROM "admin_menu" WHERE "code" = 'system_manager'), 'menu', '个人中心', '/system-manager/profile', 'Profile', '/system-manager/profile/index', NULL, 'codex:dot-circle', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_data_dictionary', (SELECT "id" FROM "admin_menu" WHERE "code" = 'system_manager'), 'menu', '数据字典', '/system-manager/data-dictionary', 'DataDictionary', '/system-manager/data-dictionary/index', NULL, 'codex:dot-circle', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_role_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'system_manager'), 'menu', '角色管理', '/system-manager/roles', 'SystemRoleManager', '/system-manager/role-manager/index', NULL, 'codex:dot-circle', 30, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_menu_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'system_manager'), 'menu', '菜单管理', '/system-manager/menus', 'SystemMenuManager', '/system-manager/menu-manager/index', NULL, 'codex:dot-circle', 40, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_permission_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'system_manager'), 'menu', '权限清单', '/system-manager/permissions', 'SystemPermissionManager', '/system-manager/permission-manager/index', NULL, 'codex:dot-circle', 50, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_accounts', (SELECT "id" FROM "admin_menu" WHERE "code" = 'system_manager'), 'menu', '后台账号', '/system-manager/accounts', 'SystemAccountManager', '/system-manager/account-manager/index', NULL, 'codex:dot-circle', 60, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_log_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'system_manager'), 'catalog', '日志管理', '/system-manager/log-manager', 'LogManager', NULL, NULL, 'codex:dot-circle', 70, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_login_log', (SELECT "id" FROM "admin_menu" WHERE "code" = 'system_log_manager'), 'menu', '登录日志', '/system-manager/log-manager/login-log', 'LoginLog', '/system-manager/log-manager/login-log/index', NULL, 'codex:dot-circle', 10, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_operation_log', (SELECT "id" FROM "admin_menu" WHERE "code" = 'system_log_manager'), 'menu', '操作日志', '/system-manager/log-manager/operation-log', 'OperationLog', '/system-manager/log-manager/operation-log/index', NULL, 'codex:dot-circle', 20, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_workflow_manager', (SELECT "id" FROM "admin_menu" WHERE "code" = 'system_manager'), 'menu', '工作流任务', '/system-manager/workflow', 'WorkflowManager', '/system-manager/workflow/index', NULL, 'codex:dot-circle', 80, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_menu" ("code", "parent_id", "type", "title", "path", "name", "component", "redirect", "icon", "sort_order", "is_visible", "is_enabled", "keep_alive", "external_link", "updated_at") VALUES ('system_ip_geolocation', (SELECT "id" FROM "admin_menu" WHERE "code" = 'system_manager'), 'menu', 'IP 属地库', '/system-manager/ip-geolocation', 'IpGeolocationManager', '/system-manager/ip-geolocation/index', NULL, 'codex:dot-circle', 90, true, true, true, NULL, now()) ON CONFLICT ("code") DO UPDATE SET "parent_id" = EXCLUDED."parent_id", "type" = EXCLUDED."type", "title" = EXCLUDED."title", "path" = EXCLUDED."path", "name" = EXCLUDED."name", "component" = EXCLUDED."component", "redirect" = EXCLUDED."redirect", "icon" = EXCLUDED."icon", "sort_order" = EXCLUDED."sort_order", "is_visible" = EXCLUDED."is_visible", "is_enabled" = EXCLUDED."is_enabled", "keep_alive" = EXCLUDED."keep_alive", "external_link" = EXCLUDED."external_link", "updated_at" = now();--> statement-breakpoint
INSERT INTO "admin_role_menu" ("role_id", "menu_id") SELECT "admin_role"."id", "admin_menu"."id" FROM "admin_role" CROSS JOIN "admin_menu" WHERE "admin_role"."code" = 'super_admin' ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "admin_role_menu" ("role_id", "menu_id") SELECT "admin_role"."id", "admin_menu"."id" FROM "admin_role" INNER JOIN "admin_menu" ON "admin_menu"."code" = 'system_profile' WHERE "admin_role"."code" = 'normal_admin' ON CONFLICT DO NOTHING;--> statement-breakpoint
ALTER TABLE "admin_user" DROP CONSTRAINT "admin_user_role_valid_chk";--> statement-breakpoint
DROP INDEX "admin_user_role_idx";--> statement-breakpoint
ALTER TABLE "admin_user" DROP COLUMN "role";--> statement-breakpoint
CREATE INDEX "admin_menu_parent_sort_idx" ON "admin_menu" ("parent_id","sort_order");--> statement-breakpoint
CREATE INDEX "admin_menu_is_enabled_idx" ON "admin_menu" ("is_enabled");--> statement-breakpoint
CREATE INDEX "admin_permission_group_code_idx" ON "admin_permission" ("group_code");--> statement-breakpoint
CREATE INDEX "admin_permission_is_enabled_idx" ON "admin_permission" ("is_enabled");--> statement-breakpoint
CREATE INDEX "admin_role_is_enabled_idx" ON "admin_role" ("is_enabled");--> statement-breakpoint
CREATE INDEX "admin_role_sort_order_idx" ON "admin_role" ("sort_order");--> statement-breakpoint
CREATE INDEX "admin_role_menu_role_id_idx" ON "admin_role_menu" ("role_id");--> statement-breakpoint
CREATE INDEX "admin_role_menu_menu_id_idx" ON "admin_role_menu" ("menu_id");--> statement-breakpoint
CREATE INDEX "admin_role_permission_role_id_idx" ON "admin_role_permission" ("role_id");--> statement-breakpoint
CREATE INDEX "admin_role_permission_permission_id_idx" ON "admin_role_permission" ("permission_id");--> statement-breakpoint
CREATE INDEX "admin_user_role_admin_user_id_idx" ON "admin_user_role" ("admin_user_id");--> statement-breakpoint
CREATE INDEX "admin_user_role_role_id_idx" ON "admin_user_role" ("role_id");