import type { GrowthRuleTypeKey } from '../growth-rule.constant'
import type {
  EventDefinition,
  EventDefinitionDraft,
  EventDefinitionMap,
} from './event-definition.type'
import {
  GROWTH_RULE_TYPE_VALUES,
  GrowthRuleTypeEnum,
} from '../growth-rule.constant'
import {
  EventDefinitionConsumerEnum,
  EventDefinitionDomainEnum,
  EventDefinitionEntityTypeEnum,
  EventDefinitionGovernanceGateEnum,
  EventDefinitionImplStatusEnum,
} from './event-definition.constant'

const GROWTH_ONLY = [EventDefinitionConsumerEnum.GROWTH] as const
const GROWTH_TASK = [
  EventDefinitionConsumerEnum.GROWTH,
  EventDefinitionConsumerEnum.TASK,
] as const
const GROWTH_TASK_NOTIFICATION = [
  EventDefinitionConsumerEnum.GROWTH,
  EventDefinitionConsumerEnum.TASK,
  EventDefinitionConsumerEnum.NOTIFICATION,
] as const
const GROWTH_TASK_NOTIFICATION_GOVERNANCE = [
  EventDefinitionConsumerEnum.GROWTH,
  EventDefinitionConsumerEnum.TASK,
  EventDefinitionConsumerEnum.NOTIFICATION,
  EventDefinitionConsumerEnum.GOVERNANCE,
] as const
const GROWTH_TASK_GOVERNANCE = [
  EventDefinitionConsumerEnum.GROWTH,
  EventDefinitionConsumerEnum.TASK,
  EventDefinitionConsumerEnum.GOVERNANCE,
] as const

// 统一补齐事件编码、稳定 key、默认账本备注和消费者数组拷贝。
function createEventDefinition(
  code: GrowthRuleTypeEnum,
  definition: EventDefinitionDraft,
): EventDefinition {
  return {
    code,
    key: GrowthRuleTypeEnum[code] as GrowthRuleTypeKey,
    ledgerRemark: definition.ledgerRemark ?? definition.label,
    ...definition,
    consumers: [...definition.consumers],
  }
}

/**
 * 成长事件定义映射表。
 * 统一维护稳定编码、业务域、治理要求、可配置性和当前实现状态。
 */
export const EVENT_DEFINITION_MAP = {
  [GrowthRuleTypeEnum.CREATE_TOPIC]: createEventDefinition(
    GrowthRuleTypeEnum.CREATE_TOPIC,
    {
      label: '发表主题',
      ledgerRemark: '发表帖子',
      domain: EventDefinitionDomainEnum.FORUM,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.FORUM_TOPIC,
      governanceGate: EventDefinitionGovernanceGateEnum.TOPIC_APPROVAL,
      consumers: GROWTH_TASK_GOVERNANCE,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.CREATE_REPLY]: createEventDefinition(
    GrowthRuleTypeEnum.CREATE_REPLY,
    {
      label: '发表回复',
      domain: EventDefinitionDomainEnum.FORUM,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.FORUM_REPLY,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.TOPIC_LIKED]: createEventDefinition(
    GrowthRuleTypeEnum.TOPIC_LIKED,
    {
      label: '主题被点赞',
      ledgerRemark: '点赞帖子',
      domain: EventDefinitionDomainEnum.FORUM,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.FORUM_TOPIC,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.REPLY_LIKED]: createEventDefinition(
    GrowthRuleTypeEnum.REPLY_LIKED,
    {
      label: '回复被点赞',
      domain: EventDefinitionDomainEnum.FORUM,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.FORUM_REPLY,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.TOPIC_FAVORITED]: createEventDefinition(
    GrowthRuleTypeEnum.TOPIC_FAVORITED,
    {
      label: '主题被收藏',
      ledgerRemark: '收藏帖子',
      domain: EventDefinitionDomainEnum.FORUM,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.FORUM_TOPIC,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.DAILY_CHECK_IN]: createEventDefinition(
    GrowthRuleTypeEnum.DAILY_CHECK_IN,
    {
      label: '每日签到（预留）',
      ledgerRemark: '每日签到',
      domain: EventDefinitionDomainEnum.ENGAGEMENT,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.CHECK_IN,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_ONLY,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: false,
    },
  ),
  [GrowthRuleTypeEnum.ADMIN]: createEventDefinition(GrowthRuleTypeEnum.ADMIN, {
    label: '管理端人工调整',
    ledgerRemark: '管理端人工调整',
    domain: EventDefinitionDomainEnum.SYSTEM,
    subjectType: EventDefinitionEntityTypeEnum.ADMIN_OPERATION,
    targetType: EventDefinitionEntityTypeEnum.USER,
    governanceGate: EventDefinitionGovernanceGateEnum.NONE,
    consumers: GROWTH_ONLY,
    implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
    isRuleConfigurable: false,
  }),
  [GrowthRuleTypeEnum.TOPIC_VIEW]: createEventDefinition(
    GrowthRuleTypeEnum.TOPIC_VIEW,
    {
      label: '主题浏览',
      ledgerRemark: '浏览帖子',
      domain: EventDefinitionDomainEnum.FORUM,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.FORUM_TOPIC,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.TOPIC_REPORT]: createEventDefinition(
    GrowthRuleTypeEnum.TOPIC_REPORT,
    {
      label: '主题举报提交（历史兼容）',
      ledgerRemark: '举报帖子',
      domain: EventDefinitionDomainEnum.FORUM,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.REPORTED_TARGET,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_GOVERNANCE,
      implStatus: EventDefinitionImplStatusEnum.LEGACY_COMPAT,
      isRuleConfigurable: false,
    },
  ),
  [GrowthRuleTypeEnum.TOPIC_COMMENT]: createEventDefinition(
    GrowthRuleTypeEnum.TOPIC_COMMENT,
    {
      label: '主题被评论',
      ledgerRemark: '帖子被评论',
      domain: EventDefinitionDomainEnum.FORUM,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.FORUM_TOPIC,
      governanceGate: EventDefinitionGovernanceGateEnum.COMMENT_APPROVAL,
      consumers: GROWTH_TASK_NOTIFICATION_GOVERNANCE,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.CREATE_COMMENT]: createEventDefinition(
    GrowthRuleTypeEnum.CREATE_COMMENT,
    {
      label: '发表评论',
      domain: EventDefinitionDomainEnum.COMMENT,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMMENT,
      governanceGate: EventDefinitionGovernanceGateEnum.COMMENT_APPROVAL,
      consumers: GROWTH_TASK_NOTIFICATION_GOVERNANCE,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.COMMENT_LIKED]: createEventDefinition(
    GrowthRuleTypeEnum.COMMENT_LIKED,
    {
      label: '评论被点赞',
      domain: EventDefinitionDomainEnum.COMMENT,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMMENT,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.COMMENT_REPORT]: createEventDefinition(
    GrowthRuleTypeEnum.COMMENT_REPORT,
    {
      label: '评论举报提交（历史兼容）',
      ledgerRemark: '举报评论',
      domain: EventDefinitionDomainEnum.COMMENT,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.REPORTED_TARGET,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_GOVERNANCE,
      implStatus: EventDefinitionImplStatusEnum.LEGACY_COMPAT,
      isRuleConfigurable: false,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_WORK_VIEW]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_WORK_VIEW,
    {
      label: '漫画作品浏览',
      ledgerRemark: '浏览漫画作品',
      domain: EventDefinitionDomainEnum.COMIC_WORK,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMIC_WORK,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_WORK_LIKE]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_WORK_LIKE,
    {
      label: '漫画作品点赞',
      ledgerRemark: '点赞漫画作品',
      domain: EventDefinitionDomainEnum.COMIC_WORK,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMIC_WORK,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_WORK_FAVORITE]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_WORK_FAVORITE,
    {
      label: '漫画作品收藏',
      ledgerRemark: '收藏漫画作品',
      domain: EventDefinitionDomainEnum.COMIC_WORK,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMIC_WORK,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_WORK_REPORT]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_WORK_REPORT,
    {
      label: '漫画作品举报提交（历史兼容）',
      ledgerRemark: '举报漫画作品',
      domain: EventDefinitionDomainEnum.COMIC_WORK,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.REPORTED_TARGET,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_GOVERNANCE,
      implStatus: EventDefinitionImplStatusEnum.LEGACY_COMPAT,
      isRuleConfigurable: false,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_WORK_COMMENT]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_WORK_COMMENT,
    {
      label: '漫画作品被评论',
      domain: EventDefinitionDomainEnum.COMIC_WORK,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMIC_WORK,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_WORK_VIEW]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_WORK_VIEW,
    {
      label: '小说作品浏览',
      ledgerRemark: '浏览小说作品',
      domain: EventDefinitionDomainEnum.NOVEL_WORK,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.NOVEL_WORK,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_WORK_LIKE]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_WORK_LIKE,
    {
      label: '小说作品点赞',
      ledgerRemark: '点赞小说作品',
      domain: EventDefinitionDomainEnum.NOVEL_WORK,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.NOVEL_WORK,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_WORK_FAVORITE]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_WORK_FAVORITE,
    {
      label: '小说作品收藏',
      ledgerRemark: '收藏小说作品',
      domain: EventDefinitionDomainEnum.NOVEL_WORK,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.NOVEL_WORK,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_WORK_REPORT]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_WORK_REPORT,
    {
      label: '小说作品举报提交（历史兼容）',
      ledgerRemark: '举报小说作品',
      domain: EventDefinitionDomainEnum.NOVEL_WORK,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.REPORTED_TARGET,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_GOVERNANCE,
      implStatus: EventDefinitionImplStatusEnum.LEGACY_COMPAT,
      isRuleConfigurable: false,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_WORK_COMMENT]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_WORK_COMMENT,
    {
      label: '小说作品被评论',
      domain: EventDefinitionDomainEnum.NOVEL_WORK,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.NOVEL_WORK,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_CHAPTER_READ]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_CHAPTER_READ,
    {
      label: '漫画章节阅读',
      ledgerRemark: '阅读漫画章节',
      domain: EventDefinitionDomainEnum.COMIC_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMIC_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_CHAPTER_LIKE]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_CHAPTER_LIKE,
    {
      label: '漫画章节点赞',
      ledgerRemark: '点赞漫画章节',
      domain: EventDefinitionDomainEnum.COMIC_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMIC_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_CHAPTER_PURCHASE]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_CHAPTER_PURCHASE,
    {
      label: '漫画章节购买',
      ledgerRemark: '购买漫画章节',
      domain: EventDefinitionDomainEnum.COMIC_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMIC_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_CHAPTER_DOWNLOAD]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_CHAPTER_DOWNLOAD,
    {
      label: '漫画章节下载',
      ledgerRemark: '下载漫画章节',
      domain: EventDefinitionDomainEnum.COMIC_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMIC_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_CHAPTER_EXCHANGE]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_CHAPTER_EXCHANGE,
    {
      label: '漫画章节兑换',
      ledgerRemark: '兑换漫画章节',
      domain: EventDefinitionDomainEnum.COMIC_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMIC_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_CHAPTER_REPORT]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_CHAPTER_REPORT,
    {
      label: '漫画章节举报提交（历史兼容）',
      ledgerRemark: '举报漫画章节',
      domain: EventDefinitionDomainEnum.COMIC_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.REPORTED_TARGET,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_GOVERNANCE,
      implStatus: EventDefinitionImplStatusEnum.LEGACY_COMPAT,
      isRuleConfigurable: false,
    },
  ),
  [GrowthRuleTypeEnum.COMIC_CHAPTER_COMMENT]: createEventDefinition(
    GrowthRuleTypeEnum.COMIC_CHAPTER_COMMENT,
    {
      label: '漫画章节被评论',
      domain: EventDefinitionDomainEnum.COMIC_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.COMIC_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_CHAPTER_READ]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_CHAPTER_READ,
    {
      label: '小说章节阅读',
      ledgerRemark: '阅读小说章节',
      domain: EventDefinitionDomainEnum.NOVEL_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.NOVEL_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_CHAPTER_LIKE]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_CHAPTER_LIKE,
    {
      label: '小说章节点赞',
      ledgerRemark: '点赞小说章节',
      domain: EventDefinitionDomainEnum.NOVEL_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.NOVEL_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_CHAPTER_PURCHASE]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_CHAPTER_PURCHASE,
    {
      label: '小说章节购买',
      ledgerRemark: '购买小说章节',
      domain: EventDefinitionDomainEnum.NOVEL_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.NOVEL_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_CHAPTER_DOWNLOAD]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_CHAPTER_DOWNLOAD,
    {
      label: '小说章节下载',
      ledgerRemark: '下载小说章节',
      domain: EventDefinitionDomainEnum.NOVEL_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.NOVEL_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_CHAPTER_EXCHANGE]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_CHAPTER_EXCHANGE,
    {
      label: '小说章节兑换',
      ledgerRemark: '兑换小说章节',
      domain: EventDefinitionDomainEnum.NOVEL_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.NOVEL_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_CHAPTER_REPORT]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_CHAPTER_REPORT,
    {
      label: '小说章节举报提交（历史兼容）',
      ledgerRemark: '举报小说章节',
      domain: EventDefinitionDomainEnum.NOVEL_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.REPORTED_TARGET,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_GOVERNANCE,
      implStatus: EventDefinitionImplStatusEnum.LEGACY_COMPAT,
      isRuleConfigurable: false,
    },
  ),
  [GrowthRuleTypeEnum.NOVEL_CHAPTER_COMMENT]: createEventDefinition(
    GrowthRuleTypeEnum.NOVEL_CHAPTER_COMMENT,
    {
      label: '小说章节被评论',
      domain: EventDefinitionDomainEnum.NOVEL_CHAPTER,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.NOVEL_CHAPTER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.BADGE_EARNED]: createEventDefinition(
    GrowthRuleTypeEnum.BADGE_EARNED,
    {
      label: '获得徽章',
      ledgerRemark: '获得徽章',
      domain: EventDefinitionDomainEnum.BADGE,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.BADGE,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.PROFILE_COMPLETE]: createEventDefinition(
    GrowthRuleTypeEnum.PROFILE_COMPLETE,
    {
      label: '完善个人资料',
      ledgerRemark: '完善个人资料',
      domain: EventDefinitionDomainEnum.PROFILE,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.USER_PROFILE,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.AVATAR_UPLOAD]: createEventDefinition(
    GrowthRuleTypeEnum.AVATAR_UPLOAD,
    {
      label: '上传头像',
      ledgerRemark: '上传头像',
      domain: EventDefinitionDomainEnum.PROFILE,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.USER_PROFILE,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.FOLLOW_USER]: createEventDefinition(
    GrowthRuleTypeEnum.FOLLOW_USER,
    {
      label: '关注用户',
      ledgerRemark: '关注用户',
      domain: EventDefinitionDomainEnum.SOCIAL,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.USER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.BE_FOLLOWED]: createEventDefinition(
    GrowthRuleTypeEnum.BE_FOLLOWED,
    {
      label: '被关注',
      ledgerRemark: '被关注',
      domain: EventDefinitionDomainEnum.SOCIAL,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.USER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK_NOTIFICATION,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.SHARE_CONTENT]: createEventDefinition(
    GrowthRuleTypeEnum.SHARE_CONTENT,
    {
      label: '分享内容',
      ledgerRemark: '分享内容',
      domain: EventDefinitionDomainEnum.SOCIAL,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.CONTENT,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.INVITE_USER]: createEventDefinition(
    GrowthRuleTypeEnum.INVITE_USER,
    {
      label: '邀请用户',
      ledgerRemark: '邀请用户',
      domain: EventDefinitionDomainEnum.SOCIAL,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.USER,
      governanceGate: EventDefinitionGovernanceGateEnum.NONE,
      consumers: GROWTH_TASK,
      implStatus: EventDefinitionImplStatusEnum.DECLARED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.REPORT_VALID]: createEventDefinition(
    GrowthRuleTypeEnum.REPORT_VALID,
    {
      label: '举报裁决有效',
      ledgerRemark: '举报裁决有效',
      domain: EventDefinitionDomainEnum.REPORT,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.REPORT,
      governanceGate: EventDefinitionGovernanceGateEnum.REPORT_JUDGEMENT,
      consumers: GROWTH_TASK_GOVERNANCE,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
  [GrowthRuleTypeEnum.REPORT_INVALID]: createEventDefinition(
    GrowthRuleTypeEnum.REPORT_INVALID,
    {
      label: '举报裁决无效',
      ledgerRemark: '举报裁决无效',
      domain: EventDefinitionDomainEnum.REPORT,
      subjectType: EventDefinitionEntityTypeEnum.USER,
      targetType: EventDefinitionEntityTypeEnum.REPORT,
      governanceGate: EventDefinitionGovernanceGateEnum.REPORT_JUDGEMENT,
      consumers: GROWTH_TASK_GOVERNANCE,
      implStatus: EventDefinitionImplStatusEnum.IMPLEMENTED,
      isRuleConfigurable: true,
    },
  ),
} satisfies EventDefinitionMap

/**
 * 按稳定编码升序输出的事件定义列表。
 * 供服务层做枚举、筛选与文档复用，避免依赖对象遍历细节。
 */
export const EVENT_DEFINITIONS = GROWTH_RULE_TYPE_VALUES.map(
  (code) => EVENT_DEFINITION_MAP[code],
)
