import { AdminMenuType } from './admin-rbac.constant'

/** 管理端首次 bootstrap 使用的默认菜单配置。 */
export interface AdminDefaultMenu {
  /** 菜单编码。 */
  code: string
  /** 父级菜单编码。 */
  parentCode?: string
  /** 菜单类型（1=目录，2=菜单）。 */
  type: AdminMenuType
  /** 菜单标题。 */
  title: string
  /** 路由路径。 */
  path: string
  /** 路由名称。 */
  name: string
  /** 前端组件键。 */
  component?: string
  /** 重定向路径。 */
  redirect?: string
  /** 菜单图标。 */
  icon?: string
  /** 排序值。 */
  sortOrder: number
  /** 是否显示。 */
  isVisible?: boolean
  /** 是否缓存页面。 */
  keepAlive?: boolean
}

/**
 * 管理端首次启动时补齐的默认菜单骨架。
 */
export const ADMIN_DEFAULT_MENUS: AdminDefaultMenu[] = [
  {
    code: 'dashboard',
    type: AdminMenuType.CATALOG,
    title: '仪表盘',
    path: '/dashboard',
    name: 'Dashboard',
    redirect: '/dashboard/analytics',
    icon: 'lucide:layout-dashboard',
    sortOrder: 10,
  },
  {
    code: 'dashboard_analytics',
    parentCode: 'dashboard',
    type: AdminMenuType.MENU,
    title: '分析页',
    path: '/dashboard/analytics',
    name: 'Analytics',
    component: '/dashboard/analytics/index',
    icon: 'lucide:area-chart',
    sortOrder: 10,
  },
  {
    code: 'dashboard_workspace',
    parentCode: 'dashboard',
    type: AdminMenuType.MENU,
    title: '工作台',
    path: '/dashboard/workspace',
    name: 'Workspace',
    component: '/dashboard/workspace/index',
    icon: 'carbon:workspace',
    sortOrder: 20,
  },
  {
    code: 'content_manager',
    type: AdminMenuType.CATALOG,
    title: '内容管理',
    path: '/content-manager',
    name: 'ContentManager',
    redirect: '/content-manager/comic-manager',
    icon: 'majesticons:book-open-line',
    sortOrder: 20,
  },
  {
    code: 'content_comic_manager',
    parentCode: 'content_manager',
    type: AdminMenuType.MENU,
    title: '漫画',
    path: '/content-manager/comic-manager',
    name: 'ComicManager',
    component: '/content-manager/comic-manager/core/index',
    icon: 'codex:dot-circle',
    sortOrder: 10,
  },
  {
    code: 'content_novel_manager',
    parentCode: 'content_manager',
    type: AdminMenuType.MENU,
    title: '小说',
    path: '/content-manager/novel-manager',
    name: 'NovelManager',
    component: '/content-manager/novel-manager/core/index',
    icon: 'codex:dot-circle',
    sortOrder: 20,
  },
  {
    code: 'content_author_manager',
    parentCode: 'content_manager',
    type: AdminMenuType.MENU,
    title: '作者管理',
    path: '/content-manager/author-manager',
    name: 'AuthorManager',
    component: '/content-manager/author-manager/index',
    icon: 'codex:dot-circle',
    sortOrder: 30,
  },
  {
    code: 'content_category_manager',
    parentCode: 'content_manager',
    type: AdminMenuType.MENU,
    title: '分类管理',
    path: '/content-manager/category-manager',
    name: 'CategoryManager',
    component: '/content-manager/category-manager/index',
    icon: 'codex:dot-circle',
    sortOrder: 40,
  },
  {
    code: 'content_tag_manager',
    parentCode: 'content_manager',
    type: AdminMenuType.MENU,
    title: '标签管理',
    path: '/content-manager/tag-manager',
    name: 'TagManager',
    component: '/content-manager/tag-manager/index',
    icon: 'codex:dot-circle',
    sortOrder: 50,
  },
  {
    code: 'content_emoji_manager',
    parentCode: 'content_manager',
    type: AdminMenuType.MENU,
    title: '表情管理',
    path: '/content-manager/emoji-manager',
    name: 'ContentEmojiManager',
    component: '/content-manager/emoji-manager/index',
    icon: 'codex:dot-circle',
    sortOrder: 60,
  },
  {
    code: 'content_governance',
    type: AdminMenuType.CATALOG,
    title: '内容治理',
    path: '/content-governance',
    name: 'ContentGovernance',
    redirect: '/content-governance/reports',
    icon: 'lucide:shield-check',
    sortOrder: 30,
  },
  {
    code: 'content_governance_reports',
    parentCode: 'content_governance',
    type: AdminMenuType.MENU,
    title: '举报处理',
    path: '/content-governance/reports',
    name: 'ContentGovernanceReports',
    component: '/content-governance/reports/index',
    icon: 'codex:dot-circle',
    sortOrder: 10,
  },
  {
    code: 'content_governance_comments',
    parentCode: 'content_governance',
    type: AdminMenuType.MENU,
    title: '评论处理',
    path: '/content-governance/comments',
    name: 'ContentGovernanceComments',
    component: '/content-governance/comments/index',
    icon: 'codex:dot-circle',
    sortOrder: 20,
  },
  {
    code: 'forum',
    type: AdminMenuType.CATALOG,
    title: '论坛管理',
    path: '/forum',
    name: 'Forum',
    redirect: '/forum/topic',
    icon: 'lucide:layout-dashboard',
    sortOrder: 40,
  },
  {
    code: 'forum_topic',
    parentCode: 'forum',
    type: AdminMenuType.MENU,
    title: '帖子管理',
    path: '/forum/topic',
    name: 'ForumTopic',
    component: '/forum/topic/index',
    icon: 'codex:dot-circle',
    sortOrder: 10,
  },
  {
    code: 'forum_moderators',
    parentCode: 'forum',
    type: AdminMenuType.MENU,
    title: '版主管理',
    path: '/forum/moderators',
    name: 'ForumModerators',
    component: '/forum/moderators/index',
    icon: 'codex:dot-circle',
    sortOrder: 20,
  },
  {
    code: 'forum_sections',
    parentCode: 'forum',
    type: AdminMenuType.MENU,
    title: '板块管理',
    path: '/forum/sections',
    name: 'ForumSections',
    component: '/forum/sections/index',
    icon: 'codex:dot-circle',
    sortOrder: 30,
  },
  {
    code: 'forum_tags',
    parentCode: 'forum',
    type: AdminMenuType.MENU,
    title: '话题管理',
    path: '/forum/tags',
    name: 'ForumTags',
    component: '/forum/tags/index',
    icon: 'codex:dot-circle',
    sortOrder: 40,
  },
  {
    code: 'forum_sensitive_word',
    parentCode: 'forum',
    type: AdminMenuType.MENU,
    title: '敏感词管理',
    path: '/forum/sensitive-word',
    name: 'ForumSensitiveWord',
    component: '/forum/sensitive-word/index',
    icon: 'codex:dot-circle',
    sortOrder: 50,
  },
  {
    code: 'forum_sensitive_word_statistics',
    parentCode: 'forum',
    type: AdminMenuType.MENU,
    title: '敏感词统计',
    path: '/forum/sensitive-word-statistics',
    name: 'ForumSensitiveWordStatistics',
    component: '/forum/sensitive-word-statistics/index',
    icon: 'codex:dot-circle',
    sortOrder: 60,
  },
  {
    code: 'user_manager',
    type: AdminMenuType.CATALOG,
    title: '用户管理',
    path: '/user-manager',
    name: 'UserManager',
    redirect: '/user-manager/profile',
    icon: 'majesticons:user-line',
    sortOrder: 50,
  },
  {
    code: 'user_profile',
    parentCode: 'user_manager',
    type: AdminMenuType.MENU,
    title: '用户信息',
    path: '/user-manager/profile',
    name: 'UserProfile',
    component: '/user-manager/profile/index',
    icon: 'codex:dot-circle',
    sortOrder: 10,
  },
  {
    code: 'user_check_in',
    parentCode: 'user_manager',
    type: AdminMenuType.MENU,
    title: '签到管理',
    path: '/user-manager/check-in',
    name: 'UserCheckIn',
    component: '/user-manager/check-in/index',
    icon: 'codex:dot-circle',
    sortOrder: 20,
  },
  {
    code: 'user_tasks',
    parentCode: 'user_manager',
    type: AdminMenuType.MENU,
    title: '任务管理',
    path: '/user-manager/tasks',
    name: 'UserTasks',
    component: '/user-manager/tasks/index',
    icon: 'codex:dot-circle',
    sortOrder: 30,
  },
  {
    code: 'user_growth_points',
    parentCode: 'user_manager',
    type: AdminMenuType.MENU,
    title: '积分管理',
    path: '/user-manager/growth/points',
    name: 'UserGrowthPoints',
    component: '/user-manager/growth/points/index',
    icon: 'codex:dot-circle',
    sortOrder: 40,
  },
  {
    code: 'user_growth_experience',
    parentCode: 'user_manager',
    type: AdminMenuType.MENU,
    title: '经验管理',
    path: '/user-manager/growth/experience',
    name: 'UserGrowthExperience',
    component: '/user-manager/growth/experience/index',
    icon: 'codex:dot-circle',
    sortOrder: 50,
  },
  {
    code: 'user_growth_level_rules',
    parentCode: 'user_manager',
    type: AdminMenuType.MENU,
    title: '等级管理',
    path: '/user-manager/growth/level-rules',
    name: 'UserGrowthLevelRules',
    component: '/user-manager/growth/level-rules/index',
    icon: 'codex:dot-circle',
    sortOrder: 60,
  },
  {
    code: 'user_growth_badges',
    parentCode: 'user_manager',
    type: AdminMenuType.MENU,
    title: '徽章管理',
    path: '/user-manager/growth/badges',
    name: 'UserGrowthBadges',
    component: '/user-manager/growth/badges/index',
    icon: 'codex:dot-circle',
    sortOrder: 70,
  },
  {
    code: 'user_growth_operations',
    parentCode: 'user_manager',
    type: AdminMenuType.MENU,
    title: '成长运营',
    path: '/user-manager/growth/operations',
    name: 'UserGrowthOperations',
    component: '/user-manager/growth/operations/index',
    icon: 'codex:dot-circle',
    sortOrder: 80,
  },
  {
    code: 'payment_rights',
    type: AdminMenuType.CATALOG,
    title: '支付与权益',
    path: '/payment-rights',
    name: 'PaymentRightsManager',
    redirect: '/payment-rights/currency-package',
    icon: 'majesticons:creditcard-line',
    sortOrder: 60,
  },
  {
    code: 'wallet_currency_package',
    parentCode: 'payment_rights',
    type: AdminMenuType.MENU,
    title: '虚拟币充值包',
    path: '/payment-rights/currency-package',
    name: 'WalletCurrencyPackage',
    component: '/payment-rights/currency-package/index',
    icon: 'codex:dot-circle',
    sortOrder: 10,
  },
  {
    code: 'coupon_definition',
    parentCode: 'payment_rights',
    type: AdminMenuType.MENU,
    title: '券定义',
    path: '/payment-rights/coupon-definition',
    name: 'CouponDefinition',
    component: '/payment-rights/coupon-definition/index',
    icon: 'codex:dot-circle',
    sortOrder: 20,
  },
  {
    code: 'payment_order',
    parentCode: 'payment_rights',
    type: AdminMenuType.MENU,
    title: '支付订单',
    path: '/payment-rights/payment-order',
    name: 'PaymentOrder',
    component: '/payment-rights/payment-order/index',
    icon: 'codex:dot-circle',
    sortOrder: 30,
  },
  {
    code: 'payment_reconcile',
    parentCode: 'payment_rights',
    type: AdminMenuType.MENU,
    title: '支付对账',
    path: '/payment-rights/payment-reconcile',
    name: 'PaymentReconcile',
    component: '/payment-rights/payment-reconcile/index',
    icon: 'codex:dot-circle',
    sortOrder: 40,
  },
  {
    code: 'membership_manager',
    parentCode: 'payment_rights',
    type: AdminMenuType.MENU,
    title: '会员管理',
    path: '/payment-rights/membership',
    name: 'MembershipManager',
    component: '/payment-rights/membership/index',
    icon: 'codex:dot-circle',
    sortOrder: 50,
  },
  {
    code: 'message_manager',
    type: AdminMenuType.CATALOG,
    title: '消息管理',
    path: '/message',
    name: 'MessageManager',
    redirect: '/message/notification-templates',
    icon: 'lucide:message-square-text',
    sortOrder: 70,
  },
  {
    code: 'message_notification_templates',
    parentCode: 'message_manager',
    type: AdminMenuType.MENU,
    title: '通知模板',
    path: '/message/notification-templates',
    name: 'MessageNotificationTemplates',
    component: '/message/notification-templates/index',
    icon: 'codex:dot-circle',
    sortOrder: 10,
  },
  {
    code: 'message_monitor',
    parentCode: 'message_manager',
    type: AdminMenuType.MENU,
    title: '消息运行',
    path: '/message/monitor',
    name: 'MessageMonitor',
    component: '/message/monitor/index',
    icon: 'codex:dot-circle',
    sortOrder: 20,
  },
  {
    code: 'message_chat_investigation',
    parentCode: 'message_manager',
    type: AdminMenuType.MENU,
    title: '聊天排查',
    path: '/message/chat-investigation',
    name: 'MessageChatInvestigation',
    component: '/message/chat-investigation/index',
    icon: 'codex:dot-circle',
    sortOrder: 30,
  },
  {
    code: 'app_manager',
    type: AdminMenuType.CATALOG,
    title: 'APP管理',
    path: '/app-manager',
    name: 'AppManager',
    redirect: '/app-manager/announcement',
    icon: 'majesticons:device-mobile-line',
    sortOrder: 80,
  },
  {
    code: 'app_announcement',
    parentCode: 'app_manager',
    type: AdminMenuType.MENU,
    title: '公告管理',
    path: '/app-manager/announcement',
    name: 'Announcement',
    component: '/app-manager/announcement/index',
    icon: 'codex:dot-circle',
    sortOrder: 10,
  },
  {
    code: 'app_agreement',
    parentCode: 'app_manager',
    type: AdminMenuType.MENU,
    title: '协议管理',
    path: '/app-manager/agreement',
    name: 'Agreement',
    component: '/app-manager/agreement/index',
    icon: 'codex:dot-circle',
    sortOrder: 20,
  },
  {
    code: 'app_page_manager',
    parentCode: 'app_manager',
    type: AdminMenuType.MENU,
    title: '页面配置',
    path: '/app-manager/page-manager',
    name: 'PageManager',
    component: '/app-manager/page-manager/index',
    icon: 'codex:dot-circle',
    sortOrder: 30,
  },
  {
    code: 'app_config',
    parentCode: 'app_manager',
    type: AdminMenuType.MENU,
    title: '应用配置',
    path: '/app-manager/app-config',
    name: 'AppConfig',
    component: '/app-manager/app-config/index',
    icon: 'codex:dot-circle',
    sortOrder: 40,
  },
  {
    code: 'app_update',
    parentCode: 'app_manager',
    type: AdminMenuType.MENU,
    title: '版本更新',
    path: '/app-manager/app-update',
    name: 'AppUpdate',
    component: '/app-manager/app-update/index',
    icon: 'codex:dot-circle',
    sortOrder: 50,
  },
  {
    code: 'statistics',
    type: AdminMenuType.CATALOG,
    title: '统计管理',
    path: '/statistics',
    name: 'StatisticsManager',
    redirect: '/statistics/comic',
    icon: 'lucide:layout-dashboard',
    sortOrder: 90,
  },
  {
    code: 'statistics_comic',
    parentCode: 'statistics',
    type: AdminMenuType.MENU,
    title: '漫画统计',
    path: '/statistics/comic',
    name: 'ComicStatistics',
    component: '/statistics/comic/index',
    icon: 'lucide:area-chart',
    sortOrder: 10,
  },
  {
    code: 'statistics_novel',
    parentCode: 'statistics',
    type: AdminMenuType.MENU,
    title: '小说统计',
    path: '/statistics/novel',
    name: 'NovelStatistics',
    component: '/statistics/novel/index',
    icon: 'lucide:area-chart',
    sortOrder: 20,
  },
  {
    code: 'statistics_forum',
    parentCode: 'statistics',
    type: AdminMenuType.MENU,
    title: '论坛统计',
    path: '/statistics/forum',
    name: 'ForumStatistics',
    component: '/statistics/forum/index',
    icon: 'lucide:area-chart',
    sortOrder: 30,
  },
  {
    code: 'config_manager',
    type: AdminMenuType.CATALOG,
    title: '配置管理',
    path: '/config-manager',
    name: 'ConfigManager',
    redirect: '/config-manager/system-config',
    icon: 'lucide:sliders-horizontal',
    sortOrder: 100,
  },
  {
    code: 'config_system',
    parentCode: 'config_manager',
    type: AdminMenuType.MENU,
    title: '系统配置',
    path: '/config-manager/system-config',
    name: 'SystemConfig',
    component: '/config-manager/system-config/index',
    icon: 'codex:dot-circle',
    sortOrder: 10,
  },
  {
    code: 'config_payment',
    parentCode: 'config_manager',
    type: AdminMenuType.MENU,
    title: '支付配置',
    path: '/config-manager/payment-config',
    name: 'PaymentConfig',
    component: '/config-manager/payment-config/index',
    icon: 'codex:dot-circle',
    sortOrder: 20,
  },
  {
    code: 'config_ad',
    parentCode: 'config_manager',
    type: AdminMenuType.MENU,
    title: '广告配置',
    path: '/config-manager/ad-config',
    name: 'AdConfig',
    component: '/config-manager/ad-config/index',
    icon: 'codex:dot-circle',
    sortOrder: 30,
  },
  {
    code: 'system_manager',
    type: AdminMenuType.CATALOG,
    title: '系统管理',
    path: '/system-manager',
    name: 'SystemManager',
    redirect: '/system-manager/profile',
    icon: 'majesticons:cog-line',
    sortOrder: 110,
  },
  {
    code: 'system_profile',
    parentCode: 'system_manager',
    type: AdminMenuType.MENU,
    title: '个人中心',
    path: '/system-manager/profile',
    name: 'Profile',
    component: '/system-manager/profile/index',
    icon: 'codex:dot-circle',
    sortOrder: 10,
  },
  {
    code: 'system_data_dictionary',
    parentCode: 'system_manager',
    type: AdminMenuType.MENU,
    title: '数据字典',
    path: '/system-manager/data-dictionary',
    name: 'DataDictionary',
    component: '/system-manager/data-dictionary/index',
    icon: 'codex:dot-circle',
    sortOrder: 20,
  },
  {
    code: 'system_role_manager',
    parentCode: 'system_manager',
    type: AdminMenuType.MENU,
    title: '角色管理',
    path: '/system-manager/roles',
    name: 'SystemRoleManager',
    component: '/system-manager/role-manager/index',
    icon: 'codex:dot-circle',
    sortOrder: 30,
  },
  {
    code: 'system_menu_manager',
    parentCode: 'system_manager',
    type: AdminMenuType.MENU,
    title: '菜单管理',
    path: '/system-manager/menus',
    name: 'SystemMenuManager',
    component: '/system-manager/menu-manager/index',
    icon: 'codex:dot-circle',
    sortOrder: 40,
  },
  {
    code: 'system_permission_manager',
    parentCode: 'system_manager',
    type: AdminMenuType.MENU,
    title: '权限清单',
    path: '/system-manager/permissions',
    name: 'SystemPermissionManager',
    component: '/system-manager/permission-manager/index',
    icon: 'codex:dot-circle',
    sortOrder: 50,
  },
  {
    code: 'system_accounts',
    parentCode: 'system_manager',
    type: AdminMenuType.MENU,
    title: '后台账号',
    path: '/system-manager/accounts',
    name: 'SystemAccountManager',
    component: '/system-manager/account-manager/index',
    icon: 'codex:dot-circle',
    sortOrder: 60,
  },
  {
    code: 'system_log_manager',
    parentCode: 'system_manager',
    type: AdminMenuType.CATALOG,
    title: '日志管理',
    path: '/system-manager/log-manager',
    name: 'LogManager',
    icon: 'codex:dot-circle',
    sortOrder: 70,
  },
  {
    code: 'system_login_log',
    parentCode: 'system_log_manager',
    type: AdminMenuType.MENU,
    title: '登录日志',
    path: '/system-manager/log-manager/login-log',
    name: 'LoginLog',
    component: '/system-manager/log-manager/login-log/index',
    icon: 'codex:dot-circle',
    sortOrder: 10,
  },
  {
    code: 'system_operation_log',
    parentCode: 'system_log_manager',
    type: AdminMenuType.MENU,
    title: '操作日志',
    path: '/system-manager/log-manager/operation-log',
    name: 'OperationLog',
    component: '/system-manager/log-manager/operation-log/index',
    icon: 'codex:dot-circle',
    sortOrder: 20,
  },
  {
    code: 'system_workflow_manager',
    parentCode: 'system_manager',
    type: AdminMenuType.MENU,
    title: '工作流任务',
    path: '/system-manager/workflow',
    name: 'WorkflowManager',
    component: '/system-manager/workflow/index',
    icon: 'codex:dot-circle',
    sortOrder: 80,
  },
  {
    code: 'system_ip_geolocation',
    parentCode: 'system_manager',
    type: AdminMenuType.MENU,
    title: 'IP 属地库',
    path: '/system-manager/ip-geolocation',
    name: 'IpGeolocationManager',
    component: '/system-manager/ip-geolocation/index',
    icon: 'codex:dot-circle',
    sortOrder: 90,
  },
]
