name: Build and Package

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master

jobs:
  docker-build:
    runs-on: es
    env:
      NODE_VERSION: '22'
      IMAGE_NAME: es-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image tag
        id: vars
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build image with cache (Dockerfile)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
          cache-from: type=local,src=/data/cache/server/buildx
          cache-to: type=local,dest=/data/cache/server/buildx,mode=max
          load: true

      - name: Run container (smoke test)
        run: |
          set -e
          CONTAINER_NAME=${{ env.IMAGE_NAME }}-${{ steps.vars.outputs.tag }}
          docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true
          docker run -d --name "$CONTAINER_NAME" \
            -e NODE_ENV=production \
            -e PORT=8080 \
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}

          echo "Waiting for app to become healthy..."
          for i in $(seq 1 30); do
            if docker exec "$CONTAINER_NAME" sh -lc 'curl -fsS http://127.0.0.1:8080/api/health >/dev/null'; then
              echo "Health check passed."
              break
            fi
            sleep 2
          done

          # Re-check and fail if unhealthy
          if ! docker exec "$CONTAINER_NAME" sh -lc 'curl -fsS http://127.0.0.1:8080/api/health >/dev/null'; then
            echo "Container did not become healthy in time. Logs:"
            docker logs "$CONTAINER_NAME" || true
            exit 1
          fi

      - name: Cleanup container
        if: always()
        run: |
          CONTAINER_NAME=${{ env.IMAGE_NAME }}-${{ steps.vars.outputs.tag }}
          docker rm -f "$CONTAINER_NAME" || true
