name: Build and Package

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master

jobs:
  docker-build:
    runs-on: es
    env:
      NODE_VERSION: '22'
      IMAGE_NAME: es-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 设置镜像标签与容器名
        id: vars
        run: |
          set -e
          IMAGE_TAG=latest
          echo "IMAGE_TAG=$IMAGE_TAG" &gt;&gt; $GITHUB_ENV
          echo "CANDIDATE_TAG=${IMAGE_TAG}-candidate" &gt;&gt; $GITHUB_ENV
          echo "CONTAINER_NAME=${IMAGE_NAME}-${IMAGE_TAG}-candidate" &gt;&gt; $GITHUB_ENV

      - name: 打包镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ env.CANDIDATE_TAG }}
          cache-from: type=local,src=/data/cache/server/buildx
          cache-to: type=local,dest=/data/cache/server/buildx,mode=max
          load: true