name: Build and Package

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master

jobs:
  docker-build:
    runs-on: es
    env:
      NODE_VERSION: '22'
      IMAGE_NAME: es-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 构建前清理悬空镜像（安全）
        run: |
          set -e
          # 仅清理悬空（dangling）镜像，避免误删正在使用的镜像或容器
          DANGLING=$(docker images -f "dangling=true" -q | sort -u || true)
          if [ -n "$DANGLING" ]; then
            echo "Pruning dangling images before build..."
            docker rmi -f $DANGLING || true
          else
            echo "No dangling images to prune."
          fi

      - name: 打包镜像
        id: build_image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=local,src=/data/cache/server/buildx
          cache-to: type=local,dest=/data/cache/server/buildx,mode=max
          load: true

      - name: 构建后清理悬空镜像
        run: |
          # 清理构建过程中产生的悬空镜像，避免出现 <none> 标签占用空间
          docker image prune -f || true