name: CI Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: es
    steps:
      # Gitea Runner 已自动将仓库克隆到工作目录，移除 checkout 与 setup-node 以避免 Node 依赖

      - name: Build in Node container (pnpm install + type-check + build)
        run: |
          docker run --rm \
            -v "$PWD":/workspace \
            -w /workspace \
            node:22 bash -lc '
              corepack enable && \
              corepack prepare pnpm@9.15.4 --activate && \
              pnpm install --frozen-lockfile && \
              pnpm type-check && \
              pnpm build
            '

      # 如需产物归档，可在 runner 主机侧压缩，或在后续加回上传逻辑

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: es-server:latest
          load: true
