name: Build and Package

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master

jobs:
  docker-build:
    runs-on: es
    env:
      NODE_VERSION: '22'
      IMAGE_NAME: es-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 替换已有镜像（若存在）
        run: |
          if docker image inspect ${{ env.IMAGE_NAME }}:latest > /dev/null 2>&1; then
            echo "Found existing image ${{ env.IMAGE_NAME }}:latest. Removing to replace..."
            docker rmi -f ${{ env.IMAGE_NAME }}:latest || echo "Force remove failed, will overwrite tag during load."
          else
            echo "No existing image with tag ${{ env.IMAGE_NAME }}:latest. Proceeding with normal build."
          fi

      - name: 打包镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=local,src=/data/cache/server/buildx
          cache-to: type=local,dest=/data/cache/server/buildx,mode=max
          load: true