name: Build and Package

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master

jobs:
  docker-build:
    runs-on: es
    env:
      NODE_VERSION: '22'
      IMAGE_NAME: es-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 设置镜像标签与容器名
        id: vars
        run: |
          set -e
          PKG_VERSION=$(node -p "require('./package.json').version || ''")
          IMAGE_TAG="$PKG_VERSION"
          if [ -z "$IMAGE_TAG" ]; then IMAGE_TAG=latest; fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "CONTAINER_NAME=${IMAGE_NAME}-${IMAGE_TAG}" >> $GITHUB_ENV

      - name: 清理同名镜像
        run: |
          echo "清理镜像 ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          docker rmi -f "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" || true

      - name: 打包镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=local,src=/data/cache/server/buildx
          cache-to: type=local,dest=/data/cache/server/buildx,mode=max
          load: true

      - name: 运行镜像
        run: |
          set -e
          docker run -d --name "${{ env.CONTAINER_NAME }}" \
            -e NODE_ENV=production \
            -e PORT=8080 \
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          echo "Waiting for app to become healthy..."
          for i in $(seq 1 3); do
            if docker exec "${{ env.CONTAINER_NAME }}" sh -lc 'curl -fsS http://127.0.0.1:8080/api/health >/dev/null'; then
              echo "Health check passed."
              break
            fi
            sleep 2
          done
