name: Build and Package

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master

jobs:
  docker-build:
    runs-on: es
    env:
      NODE_VERSION: '22'
      IMAGE_NAME: es-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image tag
        id: vars
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build image with cache (Dockerfile)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
          cache-from: type=local,src=/data/cache/server/buildx
          cache-to: type=local,dest=/data/cache/server/buildx,mode=max
          load: true

      - name: Save Docker image as tar
        run: docker save ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }} -o ${{ env.IMAGE_NAME }}-${{ steps.vars.outputs.tag }}.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ${{ env.IMAGE_NAME }}-${{ steps.vars.outputs.tag }}.tar
