name: Build and Package

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master

jobs:
  docker-build:
    runs-on: es
    env:
      NODE_VERSION: '22'
      IMAGE_NAME: es-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 设置镜像标签与容器名
        id: vars
        run: |
          set -e
          PKG_VERSION=$(node -p "require('./package.json').version || ''")
          IMAGE_TAG="$PKG_VERSION"
          if [ -z "$IMAGE_TAG" ]; then IMAGE_TAG=latest; fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "CANDIDATE_TAG=${IMAGE_TAG}-candidate" >> $GITHUB_ENV
          echo "CONTAINER_NAME=${IMAGE_NAME}-${IMAGE_TAG}-candidate" >> $GITHUB_ENV

      # 不再在构建前删除同名镜像，避免构建失败导致镜像缺失

      - name: 打包镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ env.CANDIDATE_TAG }}
          cache-from: type=local,src=/data/cache/server/buildx
          cache-to: type=local,dest=/data/cache/server/buildx,mode=max
          load: true

      - name: 运行镜像
        run: |
          set -e
          docker run -d --name "${{ env.CONTAINER_NAME }}" \
            -e NODE_ENV=production \
            -e PORT=8080 \
            ${{ env.IMAGE_NAME }}:${{ env.CANDIDATE_TAG }}

          echo "Waiting for app to become healthy..."
          for i in $(seq 1 3); do
            if docker exec "${{ env.CONTAINER_NAME }}" sh -lc 'curl -fsS http://127.0.0.1:8080/api/health >/dev/null'; then
              echo "Health check passed."
              break
            fi
            sleep 2
          done

          # Re-check and fail if unhealthy
          if ! docker exec "${{ env.CONTAINER_NAME }}" sh -lc 'curl -fsS http://127.0.0.1:8080/api/health >/dev/null'; then
            echo "Container did not become healthy in time. Logs:"
            docker logs "${{ env.CONTAINER_NAME }}" || true
            exit 1
          fi

      - name: 覆盖正式标签（候选镜像健康后）
        run: |
          set -e
          docker tag "${{ env.IMAGE_NAME }}:${{ env.CANDIDATE_TAG }}" "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

      - name: 清理候选容器与镜像
        if: always()
        run: |
          docker rm -f "${{ env.CONTAINER_NAME }}" || true
          docker rmi -f "${{ env.IMAGE_NAME }}:${{ env.CANDIDATE_TAG }}" || true
