name: Build and Package

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master

jobs:
  docker-build:
    runs-on: es
    env:
      NODE_VERSION: '22'
      IMAGE_NAME: es-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 设置镜像名称
        id: vars
        run: |
          set -e
          PKG_VERSION=$(node -p "require('./package.json').version || 'latest'")
          CONTAINER_NAME=${{ env.IMAGE_NAME }}-${{ env.PKG_VERSION }}

      - name: 清理同名镜像
        run: |
          docker rmi -f ${{ env.CONTAINER_NAME }} || true

      - name: 打包镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.CONTAINER_NAME }}
          cache-from: type=local,src=/data/cache/server/buildx
          cache-to: type=local,dest=/data/cache/server/buildx,mode=max
          load: true

      - name: 运行镜像
        run: |
          set -e
          docker run -d --name "$CONTAINER_NAME" \
            -e NODE_ENV=production \
            -e PORT=8080 \
            ${{ env.CONTAINER_NAME }}

          echo "Waiting for app to become healthy..."
          for i in $(seq 1 3); do
            if docker exec "$CONTAINER_NAME" sh -lc 'curl -fsS http://127.0.0.1:8080/api/health >/dev/null'; then
              echo "Health check passed."
              break
            fi
            sleep 2
          done
