
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  AdminUserToken: 'AdminUserToken',
  AdminUser: 'AdminUser',
  AppAgreement: 'AppAgreement',
  AppAgreementLog: 'AppAgreementLog',
  AppConfig: 'AppConfig',
  AppExperienceRecord: 'AppExperienceRecord',
  AppExperienceRule: 'AppExperienceRule',
  AppLevelRule: 'AppLevelRule',
  AppNoticeRead: 'AppNoticeRead',
  AppNotice: 'AppNotice',
  AppPage: 'AppPage',
  AppPointRecord: 'AppPointRecord',
  AppPointRule: 'AppPointRule',
  AppUserToken: 'AppUserToken',
  AppUser: 'AppUser',
  ForumBadge: 'ForumBadge',
  ForumConfigHistory: 'ForumConfigHistory',
  ForumConfig: 'ForumConfig',
  ForumModeratorActionLog: 'ForumModeratorActionLog',
  ForumModeratorApplication: 'ForumModeratorApplication',
  ForumModeratorSection: 'ForumModeratorSection',
  ForumModerator: 'ForumModerator',
  ForumNotification: 'ForumNotification',
  ForumProfileBadge: 'ForumProfileBadge',
  ForumProfile: 'ForumProfile',
  ForumReplyLike: 'ForumReplyLike',
  ForumReply: 'ForumReply',
  ForumReport: 'ForumReport',
  ForumSectionGroup: 'ForumSectionGroup',
  ForumSection: 'ForumSection',
  ForumSensitiveWord: 'ForumSensitiveWord',
  ForumTag: 'ForumTag',
  ForumTopicFavorite: 'ForumTopicFavorite',
  ForumTopicLike: 'ForumTopicLike',
  ForumTopicTag: 'ForumTopicTag',
  ForumTopic: 'ForumTopic',
  ForumUserActionLog: 'ForumUserActionLog',
  ForumView: 'ForumView',
  RequestLog: 'RequestLog',
  SystemConfig: 'SystemConfig',
  Dictionary: 'Dictionary',
  DictionaryItem: 'DictionaryItem',
  WorkAuthor: 'WorkAuthor',
  WorkComicAuthor: 'WorkComicAuthor',
  WorkComicCategory: 'WorkComicCategory',
  WorkComicChapter: 'WorkComicChapter',
  WorkComicTag: 'WorkComicTag',
  WorkComic: 'WorkComic',
  WorkCategory: 'WorkCategory',
  WorkTag: 'WorkTag'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AdminUserTokenScalarFieldEnum = {
  id: 'id',
  jti: 'jti',
  userId: 'userId',
  tokenType: 'tokenType',
  expiresAt: 'expiresAt',
  revokedAt: 'revokedAt',
  revokeReason: 'revokeReason',
  deviceInfo: 'deviceInfo',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AdminUserTokenScalarFieldEnum = (typeof AdminUserTokenScalarFieldEnum)[keyof typeof AdminUserTokenScalarFieldEnum]


export const RelationLoadStrategy = {
  query: 'query',
  join: 'join'
} as const

export type RelationLoadStrategy = (typeof RelationLoadStrategy)[keyof typeof RelationLoadStrategy]


export const AdminUserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  mobile: 'mobile',
  avatar: 'avatar',
  role: 'role',
  isEnabled: 'isEnabled',
  lastLoginAt: 'lastLoginAt',
  lastLoginIp: 'lastLoginIp',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AdminUserScalarFieldEnum = (typeof AdminUserScalarFieldEnum)[keyof typeof AdminUserScalarFieldEnum]


export const AppAgreementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  version: 'version',
  isForce: 'isForce',
  showInAuth: 'showInAuth',
  isPublished: 'isPublished',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppAgreementScalarFieldEnum = (typeof AppAgreementScalarFieldEnum)[keyof typeof AppAgreementScalarFieldEnum]


export const AppAgreementLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  agreementId: 'agreementId',
  version: 'version',
  agreedAt: 'agreedAt',
  ipAddress: 'ipAddress',
  deviceInfo: 'deviceInfo'
} as const

export type AppAgreementLogScalarFieldEnum = (typeof AppAgreementLogScalarFieldEnum)[keyof typeof AppAgreementLogScalarFieldEnum]


export const AppConfigScalarFieldEnum = {
  id: 'id',
  appName: 'appName',
  appDesc: 'appDesc',
  appLogo: 'appLogo',
  onboardingImage: 'onboardingImage',
  themeColor: 'themeColor',
  secondaryColor: 'secondaryColor',
  optionalThemeColors: 'optionalThemeColors',
  enableMaintenanceMode: 'enableMaintenanceMode',
  maintenanceMessage: 'maintenanceMessage',
  version: 'version',
  updatedById: 'updatedById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppConfigScalarFieldEnum = (typeof AppConfigScalarFieldEnum)[keyof typeof AppConfigScalarFieldEnum]


export const AppExperienceRecordScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  ruleId: 'ruleId',
  experience: 'experience',
  beforeExperience: 'beforeExperience',
  afterExperience: 'afterExperience',
  remark: 'remark',
  createdAt: 'createdAt'
} as const

export type AppExperienceRecordScalarFieldEnum = (typeof AppExperienceRecordScalarFieldEnum)[keyof typeof AppExperienceRecordScalarFieldEnum]


export const AppExperienceRuleScalarFieldEnum = {
  id: 'id',
  type: 'type',
  experience: 'experience',
  dailyLimit: 'dailyLimit',
  isEnabled: 'isEnabled',
  remark: 'remark',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppExperienceRuleScalarFieldEnum = (typeof AppExperienceRuleScalarFieldEnum)[keyof typeof AppExperienceRuleScalarFieldEnum]


export const AppLevelRuleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  requiredExperience: 'requiredExperience',
  loginDays: 'loginDays',
  description: 'description',
  icon: 'icon',
  badge: 'badge',
  color: 'color',
  sortOrder: 'sortOrder',
  isEnabled: 'isEnabled',
  dailyTopicLimit: 'dailyTopicLimit',
  dailyReplyCommentLimit: 'dailyReplyCommentLimit',
  postInterval: 'postInterval',
  dailyLikeLimit: 'dailyLikeLimit',
  dailyFavoriteLimit: 'dailyFavoriteLimit',
  blacklistLimit: 'blacklistLimit',
  workCollectionLimit: 'workCollectionLimit',
  discount: 'discount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppLevelRuleScalarFieldEnum = (typeof AppLevelRuleScalarFieldEnum)[keyof typeof AppLevelRuleScalarFieldEnum]


export const AppNoticeReadScalarFieldEnum = {
  id: 'id',
  noticeId: 'noticeId',
  userId: 'userId',
  readAt: 'readAt'
} as const

export type AppNoticeReadScalarFieldEnum = (typeof AppNoticeReadScalarFieldEnum)[keyof typeof AppNoticeReadScalarFieldEnum]


export const AppNoticeScalarFieldEnum = {
  id: 'id',
  pageId: 'pageId',
  title: 'title',
  content: 'content',
  noticeType: 'noticeType',
  priorityLevel: 'priorityLevel',
  publishStartTime: 'publishStartTime',
  publishEndTime: 'publishEndTime',
  popupBackgroundImage: 'popupBackgroundImage',
  isPublished: 'isPublished',
  isPinned: 'isPinned',
  showAsPopup: 'showAsPopup',
  enablePlatform: 'enablePlatform',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppNoticeScalarFieldEnum = (typeof AppNoticeScalarFieldEnum)[keyof typeof AppNoticeScalarFieldEnum]


export const AppPageScalarFieldEnum = {
  id: 'id',
  code: 'code',
  path: 'path',
  name: 'name',
  title: 'title',
  description: 'description',
  accessLevel: 'accessLevel',
  isEnabled: 'isEnabled',
  enablePlatform: 'enablePlatform',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppPageScalarFieldEnum = (typeof AppPageScalarFieldEnum)[keyof typeof AppPageScalarFieldEnum]


export const AppPointRecordScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  ruleId: 'ruleId',
  points: 'points',
  beforePoints: 'beforePoints',
  afterPoints: 'afterPoints',
  remark: 'remark',
  createdAt: 'createdAt'
} as const

export type AppPointRecordScalarFieldEnum = (typeof AppPointRecordScalarFieldEnum)[keyof typeof AppPointRecordScalarFieldEnum]


export const AppPointRuleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  points: 'points',
  dailyLimit: 'dailyLimit',
  isEnabled: 'isEnabled',
  remark: 'remark',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppPointRuleScalarFieldEnum = (typeof AppPointRuleScalarFieldEnum)[keyof typeof AppPointRuleScalarFieldEnum]


export const AppUserTokenScalarFieldEnum = {
  id: 'id',
  jti: 'jti',
  userId: 'userId',
  tokenType: 'tokenType',
  expiresAt: 'expiresAt',
  revokedAt: 'revokedAt',
  revokeReason: 'revokeReason',
  deviceInfo: 'deviceInfo',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppUserTokenScalarFieldEnum = (typeof AppUserTokenScalarFieldEnum)[keyof typeof AppUserTokenScalarFieldEnum]


export const AppUserScalarFieldEnum = {
  id: 'id',
  account: 'account',
  phone: 'phone',
  email: 'email',
  levelId: 'levelId',
  nickname: 'nickname',
  password: 'password',
  avatar: 'avatar',
  isEnabled: 'isEnabled',
  gender: 'gender',
  birthDate: 'birthDate',
  points: 'points',
  experience: 'experience',
  status: 'status',
  banReason: 'banReason',
  banUntil: 'banUntil',
  lastLoginAt: 'lastLoginAt',
  lastLoginIp: 'lastLoginIp',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type AppUserScalarFieldEnum = (typeof AppUserScalarFieldEnum)[keyof typeof AppUserScalarFieldEnum]


export const ForumBadgeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  description: 'description',
  icon: 'icon',
  sortOrder: 'sortOrder',
  isEnabled: 'isEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ForumBadgeScalarFieldEnum = (typeof ForumBadgeScalarFieldEnum)[keyof typeof ForumBadgeScalarFieldEnum]


export const ForumConfigHistoryScalarFieldEnum = {
  id: 'id',
  configId: 'configId',
  operatedById: 'operatedById',
  changes: 'changes',
  changeType: 'changeType',
  reason: 'reason',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  operatedAt: 'operatedAt'
} as const

export type ForumConfigHistoryScalarFieldEnum = (typeof ForumConfigHistoryScalarFieldEnum)[keyof typeof ForumConfigHistoryScalarFieldEnum]


export const ForumConfigScalarFieldEnum = {
  id: 'id',
  updatedById: 'updatedById',
  siteName: 'siteName',
  siteDescription: 'siteDescription',
  siteKeywords: 'siteKeywords',
  siteLogo: 'siteLogo',
  siteFavicon: 'siteFavicon',
  contactEmail: 'contactEmail',
  icpNumber: 'icpNumber',
  topicTitleMaxLength: 'topicTitleMaxLength',
  topicContentMaxLength: 'topicContentMaxLength',
  replyContentMaxLength: 'replyContentMaxLength',
  reviewPolicy: 'reviewPolicy',
  allowAnonymousView: 'allowAnonymousView',
  allowAnonymousPost: 'allowAnonymousPost',
  allowAnonymousReply: 'allowAnonymousReply',
  allowUserRegister: 'allowUserRegister',
  registerRequireEmailVerify: 'registerRequireEmailVerify',
  registerRequirePhoneVerify: 'registerRequirePhoneVerify',
  usernameMinLength: 'usernameMinLength',
  usernameMaxLength: 'usernameMaxLength',
  signatureMaxLength: 'signatureMaxLength',
  bioMaxLength: 'bioMaxLength',
  defaultPointsForNewUser: 'defaultPointsForNewUser',
  enableEmailNotification: 'enableEmailNotification',
  enableInAppNotification: 'enableInAppNotification',
  enableNewTopicNotification: 'enableNewTopicNotification',
  enableNewReplyNotification: 'enableNewReplyNotification',
  enableLikeNotification: 'enableLikeNotification',
  enableFavoriteNotification: 'enableFavoriteNotification',
  enableSystemNotification: 'enableSystemNotification',
  enableMaintenanceMode: 'enableMaintenanceMode',
  maintenanceMessage: 'maintenanceMessage',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ForumConfigScalarFieldEnum = (typeof ForumConfigScalarFieldEnum)[keyof typeof ForumConfigScalarFieldEnum]


export const ForumModeratorActionLogScalarFieldEnum = {
  id: 'id',
  moderatorId: 'moderatorId',
  targetId: 'targetId',
  actionType: 'actionType',
  targetType: 'targetType',
  actionDescription: 'actionDescription',
  beforeData: 'beforeData',
  afterData: 'afterData',
  createdAt: 'createdAt'
} as const

export type ForumModeratorActionLogScalarFieldEnum = (typeof ForumModeratorActionLogScalarFieldEnum)[keyof typeof ForumModeratorActionLogScalarFieldEnum]


export const ForumModeratorApplicationScalarFieldEnum = {
  id: 'id',
  applicantId: 'applicantId',
  sectionId: 'sectionId',
  auditById: 'auditById',
  status: 'status',
  permissions: 'permissions',
  reason: 'reason',
  auditReason: 'auditReason',
  remark: 'remark',
  auditAt: 'auditAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type ForumModeratorApplicationScalarFieldEnum = (typeof ForumModeratorApplicationScalarFieldEnum)[keyof typeof ForumModeratorApplicationScalarFieldEnum]


export const ForumModeratorSectionScalarFieldEnum = {
  id: 'id',
  moderatorId: 'moderatorId',
  sectionId: 'sectionId',
  permissions: 'permissions',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ForumModeratorSectionScalarFieldEnum = (typeof ForumModeratorSectionScalarFieldEnum)[keyof typeof ForumModeratorSectionScalarFieldEnum]


export const ForumModeratorScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  groupId: 'groupId',
  roleType: 'roleType',
  permissions: 'permissions',
  isEnabled: 'isEnabled',
  remark: 'remark',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type ForumModeratorScalarFieldEnum = (typeof ForumModeratorScalarFieldEnum)[keyof typeof ForumModeratorScalarFieldEnum]


export const ForumNotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  topicId: 'topicId',
  replyId: 'replyId',
  type: 'type',
  title: 'title',
  content: 'content',
  priority: 'priority',
  isRead: 'isRead',
  readAt: 'readAt',
  expiredAt: 'expiredAt',
  createdAt: 'createdAt'
} as const

export type ForumNotificationScalarFieldEnum = (typeof ForumNotificationScalarFieldEnum)[keyof typeof ForumNotificationScalarFieldEnum]


export const ForumProfileBadgeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  badgeId: 'badgeId',
  createdAt: 'createdAt'
} as const

export type ForumProfileBadgeScalarFieldEnum = (typeof ForumProfileBadgeScalarFieldEnum)[keyof typeof ForumProfileBadgeScalarFieldEnum]


export const ForumProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  topicCount: 'topicCount',
  replyCount: 'replyCount',
  likeCount: 'likeCount',
  favoriteCount: 'favoriteCount',
  signature: 'signature',
  bio: 'bio',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type ForumProfileScalarFieldEnum = (typeof ForumProfileScalarFieldEnum)[keyof typeof ForumProfileScalarFieldEnum]


export const ForumReplyLikeScalarFieldEnum = {
  id: 'id',
  replyId: 'replyId',
  userId: 'userId',
  createdAt: 'createdAt'
} as const

export type ForumReplyLikeScalarFieldEnum = (typeof ForumReplyLikeScalarFieldEnum)[keyof typeof ForumReplyLikeScalarFieldEnum]


export const ForumReplyScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  userId: 'userId',
  content: 'content',
  floor: 'floor',
  replyToId: 'replyToId',
  actualReplyToId: 'actualReplyToId',
  isHidden: 'isHidden',
  auditStatus: 'auditStatus',
  auditReason: 'auditReason',
  auditAt: 'auditAt',
  auditById: 'auditById',
  auditRole: 'auditRole',
  likeCount: 'likeCount',
  version: 'version',
  sensitiveWordHits: 'sensitiveWordHits',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type ForumReplyScalarFieldEnum = (typeof ForumReplyScalarFieldEnum)[keyof typeof ForumReplyScalarFieldEnum]


export const ForumReportScalarFieldEnum = {
  id: 'id',
  reporterId: 'reporterId',
  handlerId: 'handlerId',
  targetId: 'targetId',
  type: 'type',
  reason: 'reason',
  description: 'description',
  evidenceUrl: 'evidenceUrl',
  status: 'status',
  handlingNote: 'handlingNote',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ForumReportScalarFieldEnum = (typeof ForumReportScalarFieldEnum)[keyof typeof ForumReportScalarFieldEnum]


export const ForumSectionGroupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  sortOrder: 'sortOrder',
  isEnabled: 'isEnabled',
  maxModerators: 'maxModerators',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type ForumSectionGroupScalarFieldEnum = (typeof ForumSectionGroupScalarFieldEnum)[keyof typeof ForumSectionGroupScalarFieldEnum]


export const ForumSectionScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  userLevelRuleId: 'userLevelRuleId',
  lastTopicId: 'lastTopicId',
  name: 'name',
  description: 'description',
  icon: 'icon',
  sortOrder: 'sortOrder',
  isEnabled: 'isEnabled',
  topicReviewPolicy: 'topicReviewPolicy',
  topicCount: 'topicCount',
  replyCount: 'replyCount',
  lastPostAt: 'lastPostAt',
  remark: 'remark',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type ForumSectionScalarFieldEnum = (typeof ForumSectionScalarFieldEnum)[keyof typeof ForumSectionScalarFieldEnum]


export const ForumSensitiveWordScalarFieldEnum = {
  id: 'id',
  word: 'word',
  replaceWord: 'replaceWord',
  level: 'level',
  type: 'type',
  matchMode: 'matchMode',
  isEnabled: 'isEnabled',
  hitCount: 'hitCount',
  lastHitAt: 'lastHitAt',
  version: 'version',
  remark: 'remark',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ForumSensitiveWordScalarFieldEnum = (typeof ForumSensitiveWordScalarFieldEnum)[keyof typeof ForumSensitiveWordScalarFieldEnum]


export const ForumTagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  icon: 'icon',
  useCount: 'useCount',
  sortOrder: 'sortOrder',
  isEnabled: 'isEnabled',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ForumTagScalarFieldEnum = (typeof ForumTagScalarFieldEnum)[keyof typeof ForumTagScalarFieldEnum]


export const ForumTopicFavoriteScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  userId: 'userId',
  createdAt: 'createdAt'
} as const

export type ForumTopicFavoriteScalarFieldEnum = (typeof ForumTopicFavoriteScalarFieldEnum)[keyof typeof ForumTopicFavoriteScalarFieldEnum]


export const ForumTopicLikeScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  userId: 'userId',
  createdAt: 'createdAt'
} as const

export type ForumTopicLikeScalarFieldEnum = (typeof ForumTopicLikeScalarFieldEnum)[keyof typeof ForumTopicLikeScalarFieldEnum]


export const ForumTopicTagScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  tagId: 'tagId',
  createdAt: 'createdAt'
} as const

export type ForumTopicTagScalarFieldEnum = (typeof ForumTopicTagScalarFieldEnum)[keyof typeof ForumTopicTagScalarFieldEnum]


export const ForumTopicScalarFieldEnum = {
  id: 'id',
  sectionId: 'sectionId',
  userId: 'userId',
  lastReplyUserId: 'lastReplyUserId',
  auditById: 'auditById',
  title: 'title',
  content: 'content',
  isPinned: 'isPinned',
  isFeatured: 'isFeatured',
  isLocked: 'isLocked',
  isHidden: 'isHidden',
  auditStatus: 'auditStatus',
  auditReason: 'auditReason',
  auditAt: 'auditAt',
  auditRole: 'auditRole',
  viewCount: 'viewCount',
  replyCount: 'replyCount',
  likeCount: 'likeCount',
  favoriteCount: 'favoriteCount',
  lastReplyAt: 'lastReplyAt',
  version: 'version',
  sensitiveWordHits: 'sensitiveWordHits',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type ForumTopicScalarFieldEnum = (typeof ForumTopicScalarFieldEnum)[keyof typeof ForumTopicScalarFieldEnum]


export const ForumUserActionLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  targetId: 'targetId',
  actionType: 'actionType',
  targetType: 'targetType',
  beforeData: 'beforeData',
  afterData: 'afterData',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
} as const

export type ForumUserActionLogScalarFieldEnum = (typeof ForumUserActionLogScalarFieldEnum)[keyof typeof ForumUserActionLogScalarFieldEnum]


export const ForumViewScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  replyId: 'replyId',
  userId: 'userId',
  type: 'type',
  duration: 'duration',
  device: 'device',
  ipAddress: 'ipAddress',
  viewedAt: 'viewedAt'
} as const

export type ForumViewScalarFieldEnum = (typeof ForumViewScalarFieldEnum)[keyof typeof ForumViewScalarFieldEnum]


export const RequestLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  username: 'username',
  apiType: 'apiType',
  method: 'method',
  path: 'path',
  params: 'params',
  ip: 'ip',
  userAgent: 'userAgent',
  device: 'device',
  actionType: 'actionType',
  isSuccess: 'isSuccess',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RequestLogScalarFieldEnum = (typeof RequestLogScalarFieldEnum)[keyof typeof RequestLogScalarFieldEnum]


export const SystemConfigScalarFieldEnum = {
  id: 'id',
  aliyunConfig: 'aliyunConfig',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SystemConfigScalarFieldEnum = (typeof SystemConfigScalarFieldEnum)[keyof typeof SystemConfigScalarFieldEnum]


export const DictionaryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  cover: 'cover',
  isEnabled: 'isEnabled',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type DictionaryScalarFieldEnum = (typeof DictionaryScalarFieldEnum)[keyof typeof DictionaryScalarFieldEnum]


export const DictionaryItemScalarFieldEnum = {
  id: 'id',
  dictionaryCode: 'dictionaryCode',
  name: 'name',
  code: 'code',
  order: 'order',
  cover: 'cover',
  isEnabled: 'isEnabled',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type DictionaryItemScalarFieldEnum = (typeof DictionaryItemScalarFieldEnum)[keyof typeof DictionaryItemScalarFieldEnum]


export const WorkAuthorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  avatar: 'avatar',
  description: 'description',
  nationality: 'nationality',
  gender: 'gender',
  type: 'type',
  isEnabled: 'isEnabled',
  isRecommended: 'isRecommended',
  worksCount: 'worksCount',
  followersCount: 'followersCount',
  remark: 'remark',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type WorkAuthorScalarFieldEnum = (typeof WorkAuthorScalarFieldEnum)[keyof typeof WorkAuthorScalarFieldEnum]


export const WorkComicAuthorScalarFieldEnum = {
  id: 'id',
  comicId: 'comicId',
  authorId: 'authorId',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkComicAuthorScalarFieldEnum = (typeof WorkComicAuthorScalarFieldEnum)[keyof typeof WorkComicAuthorScalarFieldEnum]


export const WorkComicCategoryScalarFieldEnum = {
  comicId: 'comicId',
  categoryId: 'categoryId',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkComicCategoryScalarFieldEnum = (typeof WorkComicCategoryScalarFieldEnum)[keyof typeof WorkComicCategoryScalarFieldEnum]


export const WorkComicChapterScalarFieldEnum = {
  id: 'id',
  comicId: 'comicId',
  requiredReadLevelId: 'requiredReadLevelId',
  requiredDownloadLevelId: 'requiredDownloadLevelId',
  title: 'title',
  subtitle: 'subtitle',
  description: 'description',
  contents: 'contents',
  sortOrder: 'sortOrder',
  readRule: 'readRule',
  downloadRule: 'downloadRule',
  readPoints: 'readPoints',
  downloadPoints: 'downloadPoints',
  isPublished: 'isPublished',
  isPreview: 'isPreview',
  canComment: 'canComment',
  publishAt: 'publishAt',
  viewCount: 'viewCount',
  likeCount: 'likeCount',
  commentCount: 'commentCount',
  purchaseCount: 'purchaseCount',
  remark: 'remark',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type WorkComicChapterScalarFieldEnum = (typeof WorkComicChapterScalarFieldEnum)[keyof typeof WorkComicChapterScalarFieldEnum]


export const WorkComicTagScalarFieldEnum = {
  comicId: 'comicId',
  tagId: 'tagId',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkComicTagScalarFieldEnum = (typeof WorkComicTagScalarFieldEnum)[keyof typeof WorkComicTagScalarFieldEnum]


export const WorkComicScalarFieldEnum = {
  id: 'id',
  name: 'name',
  alias: 'alias',
  cover: 'cover',
  description: 'description',
  publisher: 'publisher',
  originalSource: 'originalSource',
  copyright: 'copyright',
  disclaimer: 'disclaimer',
  language: 'language',
  region: 'region',
  ageRating: 'ageRating',
  serialStatus: 'serialStatus',
  isPublished: 'isPublished',
  isRecommended: 'isRecommended',
  isHot: 'isHot',
  isNew: 'isNew',
  popularity: 'popularity',
  rating: 'rating',
  recommendWeight: 'recommendWeight',
  viewCount: 'viewCount',
  favoriteCount: 'favoriteCount',
  likeCount: 'likeCount',
  ratingCount: 'ratingCount',
  publishAt: 'publishAt',
  lastUpdated: 'lastUpdated',
  remark: 'remark',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type WorkComicScalarFieldEnum = (typeof WorkComicScalarFieldEnum)[keyof typeof WorkComicScalarFieldEnum]


export const WorkCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  icon: 'icon',
  contentType: 'contentType',
  popularity: 'popularity',
  order: 'order',
  isEnabled: 'isEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkCategoryScalarFieldEnum = (typeof WorkCategoryScalarFieldEnum)[keyof typeof WorkCategoryScalarFieldEnum]


export const WorkTagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  icon: 'icon',
  description: 'description',
  popularity: 'popularity',
  order: 'order',
  isEnabled: 'isEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkTagScalarFieldEnum = (typeof WorkTagScalarFieldEnum)[keyof typeof WorkTagScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

