
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TaskAssignment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TaskAssignment
 * 任务分配记录
 */
export type TaskAssignmentModel = runtime.Types.Result.DefaultSelection<Prisma.$TaskAssignmentPayload>

export type AggregateTaskAssignment = {
  _count: TaskAssignmentCountAggregateOutputType | null
  _avg: TaskAssignmentAvgAggregateOutputType | null
  _sum: TaskAssignmentSumAggregateOutputType | null
  _min: TaskAssignmentMinAggregateOutputType | null
  _max: TaskAssignmentMaxAggregateOutputType | null
}

export type TaskAssignmentAvgAggregateOutputType = {
  id: number | null
  taskId: number | null
  userId: number | null
  status: number | null
  progress: number | null
  target: number | null
  version: number | null
}

export type TaskAssignmentSumAggregateOutputType = {
  id: number | null
  taskId: number | null
  userId: number | null
  status: number | null
  progress: number | null
  target: number | null
  version: number | null
}

export type TaskAssignmentMinAggregateOutputType = {
  id: number | null
  taskId: number | null
  userId: number | null
  cycleKey: string | null
  status: number | null
  progress: number | null
  target: number | null
  claimedAt: Date | null
  completedAt: Date | null
  expiredAt: Date | null
  version: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type TaskAssignmentMaxAggregateOutputType = {
  id: number | null
  taskId: number | null
  userId: number | null
  cycleKey: string | null
  status: number | null
  progress: number | null
  target: number | null
  claimedAt: Date | null
  completedAt: Date | null
  expiredAt: Date | null
  version: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type TaskAssignmentCountAggregateOutputType = {
  id: number
  taskId: number
  userId: number
  cycleKey: number
  status: number
  progress: number
  target: number
  claimedAt: number
  completedAt: number
  expiredAt: number
  taskSnapshot: number
  context: number
  version: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type TaskAssignmentAvgAggregateInputType = {
  id?: true
  taskId?: true
  userId?: true
  status?: true
  progress?: true
  target?: true
  version?: true
}

export type TaskAssignmentSumAggregateInputType = {
  id?: true
  taskId?: true
  userId?: true
  status?: true
  progress?: true
  target?: true
  version?: true
}

export type TaskAssignmentMinAggregateInputType = {
  id?: true
  taskId?: true
  userId?: true
  cycleKey?: true
  status?: true
  progress?: true
  target?: true
  claimedAt?: true
  completedAt?: true
  expiredAt?: true
  version?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type TaskAssignmentMaxAggregateInputType = {
  id?: true
  taskId?: true
  userId?: true
  cycleKey?: true
  status?: true
  progress?: true
  target?: true
  claimedAt?: true
  completedAt?: true
  expiredAt?: true
  version?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type TaskAssignmentCountAggregateInputType = {
  id?: true
  taskId?: true
  userId?: true
  cycleKey?: true
  status?: true
  progress?: true
  target?: true
  claimedAt?: true
  completedAt?: true
  expiredAt?: true
  taskSnapshot?: true
  context?: true
  version?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type TaskAssignmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaskAssignment to aggregate.
   */
  where?: Prisma.TaskAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskAssignments to fetch.
   */
  orderBy?: Prisma.TaskAssignmentOrderByWithRelationInput | Prisma.TaskAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TaskAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskAssignments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TaskAssignments
  **/
  _count?: true | TaskAssignmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TaskAssignmentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TaskAssignmentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TaskAssignmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TaskAssignmentMaxAggregateInputType
}

export type GetTaskAssignmentAggregateType<T extends TaskAssignmentAggregateArgs> = {
      [P in keyof T & keyof AggregateTaskAssignment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTaskAssignment[P]>
    : Prisma.GetScalarType<T[P], AggregateTaskAssignment[P]>
}




export type TaskAssignmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaskAssignmentWhereInput
  orderBy?: Prisma.TaskAssignmentOrderByWithAggregationInput | Prisma.TaskAssignmentOrderByWithAggregationInput[]
  by: Prisma.TaskAssignmentScalarFieldEnum[] | Prisma.TaskAssignmentScalarFieldEnum
  having?: Prisma.TaskAssignmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TaskAssignmentCountAggregateInputType | true
  _avg?: TaskAssignmentAvgAggregateInputType
  _sum?: TaskAssignmentSumAggregateInputType
  _min?: TaskAssignmentMinAggregateInputType
  _max?: TaskAssignmentMaxAggregateInputType
}

export type TaskAssignmentGroupByOutputType = {
  id: number
  taskId: number
  userId: number
  cycleKey: string
  status: number
  progress: number
  target: number
  claimedAt: Date | null
  completedAt: Date | null
  expiredAt: Date | null
  taskSnapshot: runtime.JsonValue | null
  context: runtime.JsonValue | null
  version: number
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: TaskAssignmentCountAggregateOutputType | null
  _avg: TaskAssignmentAvgAggregateOutputType | null
  _sum: TaskAssignmentSumAggregateOutputType | null
  _min: TaskAssignmentMinAggregateOutputType | null
  _max: TaskAssignmentMaxAggregateOutputType | null
}

type GetTaskAssignmentGroupByPayload<T extends TaskAssignmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TaskAssignmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TaskAssignmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TaskAssignmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TaskAssignmentGroupByOutputType[P]>
      }
    >
  >



export type TaskAssignmentWhereInput = {
  AND?: Prisma.TaskAssignmentWhereInput | Prisma.TaskAssignmentWhereInput[]
  OR?: Prisma.TaskAssignmentWhereInput[]
  NOT?: Prisma.TaskAssignmentWhereInput | Prisma.TaskAssignmentWhereInput[]
  id?: Prisma.IntFilter<"TaskAssignment"> | number
  taskId?: Prisma.IntFilter<"TaskAssignment"> | number
  userId?: Prisma.IntFilter<"TaskAssignment"> | number
  cycleKey?: Prisma.StringFilter<"TaskAssignment"> | string
  status?: Prisma.IntFilter<"TaskAssignment"> | number
  progress?: Prisma.IntFilter<"TaskAssignment"> | number
  target?: Prisma.IntFilter<"TaskAssignment"> | number
  claimedAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
  expiredAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
  taskSnapshot?: Prisma.JsonNullableFilter<"TaskAssignment">
  context?: Prisma.JsonNullableFilter<"TaskAssignment">
  version?: Prisma.IntFilter<"TaskAssignment"> | number
  createdAt?: Prisma.DateTimeFilter<"TaskAssignment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TaskAssignment"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
  user?: Prisma.XOR<Prisma.AppUserScalarRelationFilter, Prisma.AppUserWhereInput>
  progressLogs?: Prisma.TaskProgressLogListRelationFilter
}

export type TaskAssignmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  cycleKey?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  target?: Prisma.SortOrder
  claimedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  expiredAt?: Prisma.SortOrderInput | Prisma.SortOrder
  taskSnapshot?: Prisma.SortOrderInput | Prisma.SortOrder
  context?: Prisma.SortOrderInput | Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  task?: Prisma.TaskOrderByWithRelationInput
  user?: Prisma.AppUserOrderByWithRelationInput
  progressLogs?: Prisma.TaskProgressLogOrderByRelationAggregateInput
}

export type TaskAssignmentWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  taskId_userId_cycleKey?: Prisma.TaskAssignmentTaskIdUserIdCycleKeyCompoundUniqueInput
  AND?: Prisma.TaskAssignmentWhereInput | Prisma.TaskAssignmentWhereInput[]
  OR?: Prisma.TaskAssignmentWhereInput[]
  NOT?: Prisma.TaskAssignmentWhereInput | Prisma.TaskAssignmentWhereInput[]
  taskId?: Prisma.IntFilter<"TaskAssignment"> | number
  userId?: Prisma.IntFilter<"TaskAssignment"> | number
  cycleKey?: Prisma.StringFilter<"TaskAssignment"> | string
  status?: Prisma.IntFilter<"TaskAssignment"> | number
  progress?: Prisma.IntFilter<"TaskAssignment"> | number
  target?: Prisma.IntFilter<"TaskAssignment"> | number
  claimedAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
  expiredAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
  taskSnapshot?: Prisma.JsonNullableFilter<"TaskAssignment">
  context?: Prisma.JsonNullableFilter<"TaskAssignment">
  version?: Prisma.IntFilter<"TaskAssignment"> | number
  createdAt?: Prisma.DateTimeFilter<"TaskAssignment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TaskAssignment"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
  user?: Prisma.XOR<Prisma.AppUserScalarRelationFilter, Prisma.AppUserWhereInput>
  progressLogs?: Prisma.TaskProgressLogListRelationFilter
}, "id" | "taskId_userId_cycleKey">

export type TaskAssignmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  cycleKey?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  target?: Prisma.SortOrder
  claimedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  expiredAt?: Prisma.SortOrderInput | Prisma.SortOrder
  taskSnapshot?: Prisma.SortOrderInput | Prisma.SortOrder
  context?: Prisma.SortOrderInput | Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TaskAssignmentCountOrderByAggregateInput
  _avg?: Prisma.TaskAssignmentAvgOrderByAggregateInput
  _max?: Prisma.TaskAssignmentMaxOrderByAggregateInput
  _min?: Prisma.TaskAssignmentMinOrderByAggregateInput
  _sum?: Prisma.TaskAssignmentSumOrderByAggregateInput
}

export type TaskAssignmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.TaskAssignmentScalarWhereWithAggregatesInput | Prisma.TaskAssignmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.TaskAssignmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TaskAssignmentScalarWhereWithAggregatesInput | Prisma.TaskAssignmentScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"TaskAssignment"> | number
  taskId?: Prisma.IntWithAggregatesFilter<"TaskAssignment"> | number
  userId?: Prisma.IntWithAggregatesFilter<"TaskAssignment"> | number
  cycleKey?: Prisma.StringWithAggregatesFilter<"TaskAssignment"> | string
  status?: Prisma.IntWithAggregatesFilter<"TaskAssignment"> | number
  progress?: Prisma.IntWithAggregatesFilter<"TaskAssignment"> | number
  target?: Prisma.IntWithAggregatesFilter<"TaskAssignment"> | number
  claimedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TaskAssignment"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TaskAssignment"> | Date | string | null
  expiredAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TaskAssignment"> | Date | string | null
  taskSnapshot?: Prisma.JsonNullableWithAggregatesFilter<"TaskAssignment">
  context?: Prisma.JsonNullableWithAggregatesFilter<"TaskAssignment">
  version?: Prisma.IntWithAggregatesFilter<"TaskAssignment"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TaskAssignment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TaskAssignment"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TaskAssignment"> | Date | string | null
}

export type TaskAssignmentCreateInput = {
  cycleKey: string
  status: number
  progress?: number
  target?: number
  claimedAt?: Date | string | null
  completedAt?: Date | string | null
  expiredAt?: Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  task: Prisma.TaskCreateNestedOneWithoutAssignmentsInput
  user: Prisma.AppUserCreateNestedOneWithoutTaskAssignmentsInput
  progressLogs?: Prisma.TaskProgressLogCreateNestedManyWithoutAssignmentInput
}

export type TaskAssignmentUncheckedCreateInput = {
  id?: number
  taskId: number
  userId: number
  cycleKey: string
  status: number
  progress?: number
  target?: number
  claimedAt?: Date | string | null
  completedAt?: Date | string | null
  expiredAt?: Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  progressLogs?: Prisma.TaskProgressLogUncheckedCreateNestedManyWithoutAssignmentInput
}

export type TaskAssignmentUpdateInput = {
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  task?: Prisma.TaskUpdateOneRequiredWithoutAssignmentsNestedInput
  user?: Prisma.AppUserUpdateOneRequiredWithoutTaskAssignmentsNestedInput
  progressLogs?: Prisma.TaskProgressLogUpdateManyWithoutAssignmentNestedInput
}

export type TaskAssignmentUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  taskId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  progressLogs?: Prisma.TaskProgressLogUncheckedUpdateManyWithoutAssignmentNestedInput
}

export type TaskAssignmentCreateManyInput = {
  id?: number
  taskId: number
  userId: number
  cycleKey: string
  status: number
  progress?: number
  target?: number
  claimedAt?: Date | string | null
  completedAt?: Date | string | null
  expiredAt?: Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type TaskAssignmentUpdateManyMutationInput = {
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TaskAssignmentUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  taskId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TaskAssignmentListRelationFilter = {
  every?: Prisma.TaskAssignmentWhereInput
  some?: Prisma.TaskAssignmentWhereInput
  none?: Prisma.TaskAssignmentWhereInput
}

export type TaskAssignmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TaskAssignmentTaskIdUserIdCycleKeyCompoundUniqueInput = {
  taskId: number
  userId: number
  cycleKey: string
}

export type TaskAssignmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  cycleKey?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  target?: Prisma.SortOrder
  claimedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  taskSnapshot?: Prisma.SortOrder
  context?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TaskAssignmentAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  target?: Prisma.SortOrder
  version?: Prisma.SortOrder
}

export type TaskAssignmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  cycleKey?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  target?: Prisma.SortOrder
  claimedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TaskAssignmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  cycleKey?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  target?: Prisma.SortOrder
  claimedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TaskAssignmentSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  target?: Prisma.SortOrder
  version?: Prisma.SortOrder
}

export type TaskAssignmentScalarRelationFilter = {
  is?: Prisma.TaskAssignmentWhereInput
  isNot?: Prisma.TaskAssignmentWhereInput
}

export type TaskAssignmentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutUserInput, Prisma.TaskAssignmentUncheckedCreateWithoutUserInput> | Prisma.TaskAssignmentCreateWithoutUserInput[] | Prisma.TaskAssignmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TaskAssignmentCreateOrConnectWithoutUserInput | Prisma.TaskAssignmentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TaskAssignmentCreateManyUserInputEnvelope
  connect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
}

export type TaskAssignmentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutUserInput, Prisma.TaskAssignmentUncheckedCreateWithoutUserInput> | Prisma.TaskAssignmentCreateWithoutUserInput[] | Prisma.TaskAssignmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TaskAssignmentCreateOrConnectWithoutUserInput | Prisma.TaskAssignmentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TaskAssignmentCreateManyUserInputEnvelope
  connect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
}

export type TaskAssignmentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutUserInput, Prisma.TaskAssignmentUncheckedCreateWithoutUserInput> | Prisma.TaskAssignmentCreateWithoutUserInput[] | Prisma.TaskAssignmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TaskAssignmentCreateOrConnectWithoutUserInput | Prisma.TaskAssignmentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TaskAssignmentUpsertWithWhereUniqueWithoutUserInput | Prisma.TaskAssignmentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TaskAssignmentCreateManyUserInputEnvelope
  set?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  disconnect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  delete?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  connect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  update?: Prisma.TaskAssignmentUpdateWithWhereUniqueWithoutUserInput | Prisma.TaskAssignmentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TaskAssignmentUpdateManyWithWhereWithoutUserInput | Prisma.TaskAssignmentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TaskAssignmentScalarWhereInput | Prisma.TaskAssignmentScalarWhereInput[]
}

export type TaskAssignmentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutUserInput, Prisma.TaskAssignmentUncheckedCreateWithoutUserInput> | Prisma.TaskAssignmentCreateWithoutUserInput[] | Prisma.TaskAssignmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TaskAssignmentCreateOrConnectWithoutUserInput | Prisma.TaskAssignmentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TaskAssignmentUpsertWithWhereUniqueWithoutUserInput | Prisma.TaskAssignmentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TaskAssignmentCreateManyUserInputEnvelope
  set?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  disconnect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  delete?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  connect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  update?: Prisma.TaskAssignmentUpdateWithWhereUniqueWithoutUserInput | Prisma.TaskAssignmentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TaskAssignmentUpdateManyWithWhereWithoutUserInput | Prisma.TaskAssignmentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TaskAssignmentScalarWhereInput | Prisma.TaskAssignmentScalarWhereInput[]
}

export type TaskAssignmentCreateNestedOneWithoutProgressLogsInput = {
  create?: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutProgressLogsInput, Prisma.TaskAssignmentUncheckedCreateWithoutProgressLogsInput>
  connectOrCreate?: Prisma.TaskAssignmentCreateOrConnectWithoutProgressLogsInput
  connect?: Prisma.TaskAssignmentWhereUniqueInput
}

export type TaskAssignmentUpdateOneRequiredWithoutProgressLogsNestedInput = {
  create?: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutProgressLogsInput, Prisma.TaskAssignmentUncheckedCreateWithoutProgressLogsInput>
  connectOrCreate?: Prisma.TaskAssignmentCreateOrConnectWithoutProgressLogsInput
  upsert?: Prisma.TaskAssignmentUpsertWithoutProgressLogsInput
  connect?: Prisma.TaskAssignmentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TaskAssignmentUpdateToOneWithWhereWithoutProgressLogsInput, Prisma.TaskAssignmentUpdateWithoutProgressLogsInput>, Prisma.TaskAssignmentUncheckedUpdateWithoutProgressLogsInput>
}

export type TaskAssignmentCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutTaskInput, Prisma.TaskAssignmentUncheckedCreateWithoutTaskInput> | Prisma.TaskAssignmentCreateWithoutTaskInput[] | Prisma.TaskAssignmentUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TaskAssignmentCreateOrConnectWithoutTaskInput | Prisma.TaskAssignmentCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.TaskAssignmentCreateManyTaskInputEnvelope
  connect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
}

export type TaskAssignmentUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutTaskInput, Prisma.TaskAssignmentUncheckedCreateWithoutTaskInput> | Prisma.TaskAssignmentCreateWithoutTaskInput[] | Prisma.TaskAssignmentUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TaskAssignmentCreateOrConnectWithoutTaskInput | Prisma.TaskAssignmentCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.TaskAssignmentCreateManyTaskInputEnvelope
  connect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
}

export type TaskAssignmentUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutTaskInput, Prisma.TaskAssignmentUncheckedCreateWithoutTaskInput> | Prisma.TaskAssignmentCreateWithoutTaskInput[] | Prisma.TaskAssignmentUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TaskAssignmentCreateOrConnectWithoutTaskInput | Prisma.TaskAssignmentCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.TaskAssignmentUpsertWithWhereUniqueWithoutTaskInput | Prisma.TaskAssignmentUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.TaskAssignmentCreateManyTaskInputEnvelope
  set?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  disconnect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  delete?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  connect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  update?: Prisma.TaskAssignmentUpdateWithWhereUniqueWithoutTaskInput | Prisma.TaskAssignmentUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.TaskAssignmentUpdateManyWithWhereWithoutTaskInput | Prisma.TaskAssignmentUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.TaskAssignmentScalarWhereInput | Prisma.TaskAssignmentScalarWhereInput[]
}

export type TaskAssignmentUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutTaskInput, Prisma.TaskAssignmentUncheckedCreateWithoutTaskInput> | Prisma.TaskAssignmentCreateWithoutTaskInput[] | Prisma.TaskAssignmentUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TaskAssignmentCreateOrConnectWithoutTaskInput | Prisma.TaskAssignmentCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.TaskAssignmentUpsertWithWhereUniqueWithoutTaskInput | Prisma.TaskAssignmentUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.TaskAssignmentCreateManyTaskInputEnvelope
  set?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  disconnect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  delete?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  connect?: Prisma.TaskAssignmentWhereUniqueInput | Prisma.TaskAssignmentWhereUniqueInput[]
  update?: Prisma.TaskAssignmentUpdateWithWhereUniqueWithoutTaskInput | Prisma.TaskAssignmentUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.TaskAssignmentUpdateManyWithWhereWithoutTaskInput | Prisma.TaskAssignmentUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.TaskAssignmentScalarWhereInput | Prisma.TaskAssignmentScalarWhereInput[]
}

export type TaskAssignmentCreateWithoutUserInput = {
  cycleKey: string
  status: number
  progress?: number
  target?: number
  claimedAt?: Date | string | null
  completedAt?: Date | string | null
  expiredAt?: Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  task: Prisma.TaskCreateNestedOneWithoutAssignmentsInput
  progressLogs?: Prisma.TaskProgressLogCreateNestedManyWithoutAssignmentInput
}

export type TaskAssignmentUncheckedCreateWithoutUserInput = {
  id?: number
  taskId: number
  cycleKey: string
  status: number
  progress?: number
  target?: number
  claimedAt?: Date | string | null
  completedAt?: Date | string | null
  expiredAt?: Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  progressLogs?: Prisma.TaskProgressLogUncheckedCreateNestedManyWithoutAssignmentInput
}

export type TaskAssignmentCreateOrConnectWithoutUserInput = {
  where: Prisma.TaskAssignmentWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutUserInput, Prisma.TaskAssignmentUncheckedCreateWithoutUserInput>
}

export type TaskAssignmentCreateManyUserInputEnvelope = {
  data: Prisma.TaskAssignmentCreateManyUserInput | Prisma.TaskAssignmentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type TaskAssignmentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TaskAssignmentWhereUniqueInput
  update: Prisma.XOR<Prisma.TaskAssignmentUpdateWithoutUserInput, Prisma.TaskAssignmentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutUserInput, Prisma.TaskAssignmentUncheckedCreateWithoutUserInput>
}

export type TaskAssignmentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TaskAssignmentWhereUniqueInput
  data: Prisma.XOR<Prisma.TaskAssignmentUpdateWithoutUserInput, Prisma.TaskAssignmentUncheckedUpdateWithoutUserInput>
}

export type TaskAssignmentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TaskAssignmentScalarWhereInput
  data: Prisma.XOR<Prisma.TaskAssignmentUpdateManyMutationInput, Prisma.TaskAssignmentUncheckedUpdateManyWithoutUserInput>
}

export type TaskAssignmentScalarWhereInput = {
  AND?: Prisma.TaskAssignmentScalarWhereInput | Prisma.TaskAssignmentScalarWhereInput[]
  OR?: Prisma.TaskAssignmentScalarWhereInput[]
  NOT?: Prisma.TaskAssignmentScalarWhereInput | Prisma.TaskAssignmentScalarWhereInput[]
  id?: Prisma.IntFilter<"TaskAssignment"> | number
  taskId?: Prisma.IntFilter<"TaskAssignment"> | number
  userId?: Prisma.IntFilter<"TaskAssignment"> | number
  cycleKey?: Prisma.StringFilter<"TaskAssignment"> | string
  status?: Prisma.IntFilter<"TaskAssignment"> | number
  progress?: Prisma.IntFilter<"TaskAssignment"> | number
  target?: Prisma.IntFilter<"TaskAssignment"> | number
  claimedAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
  expiredAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
  taskSnapshot?: Prisma.JsonNullableFilter<"TaskAssignment">
  context?: Prisma.JsonNullableFilter<"TaskAssignment">
  version?: Prisma.IntFilter<"TaskAssignment"> | number
  createdAt?: Prisma.DateTimeFilter<"TaskAssignment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TaskAssignment"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"TaskAssignment"> | Date | string | null
}

export type TaskAssignmentCreateWithoutProgressLogsInput = {
  cycleKey: string
  status: number
  progress?: number
  target?: number
  claimedAt?: Date | string | null
  completedAt?: Date | string | null
  expiredAt?: Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  task: Prisma.TaskCreateNestedOneWithoutAssignmentsInput
  user: Prisma.AppUserCreateNestedOneWithoutTaskAssignmentsInput
}

export type TaskAssignmentUncheckedCreateWithoutProgressLogsInput = {
  id?: number
  taskId: number
  userId: number
  cycleKey: string
  status: number
  progress?: number
  target?: number
  claimedAt?: Date | string | null
  completedAt?: Date | string | null
  expiredAt?: Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type TaskAssignmentCreateOrConnectWithoutProgressLogsInput = {
  where: Prisma.TaskAssignmentWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutProgressLogsInput, Prisma.TaskAssignmentUncheckedCreateWithoutProgressLogsInput>
}

export type TaskAssignmentUpsertWithoutProgressLogsInput = {
  update: Prisma.XOR<Prisma.TaskAssignmentUpdateWithoutProgressLogsInput, Prisma.TaskAssignmentUncheckedUpdateWithoutProgressLogsInput>
  create: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutProgressLogsInput, Prisma.TaskAssignmentUncheckedCreateWithoutProgressLogsInput>
  where?: Prisma.TaskAssignmentWhereInput
}

export type TaskAssignmentUpdateToOneWithWhereWithoutProgressLogsInput = {
  where?: Prisma.TaskAssignmentWhereInput
  data: Prisma.XOR<Prisma.TaskAssignmentUpdateWithoutProgressLogsInput, Prisma.TaskAssignmentUncheckedUpdateWithoutProgressLogsInput>
}

export type TaskAssignmentUpdateWithoutProgressLogsInput = {
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  task?: Prisma.TaskUpdateOneRequiredWithoutAssignmentsNestedInput
  user?: Prisma.AppUserUpdateOneRequiredWithoutTaskAssignmentsNestedInput
}

export type TaskAssignmentUncheckedUpdateWithoutProgressLogsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  taskId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TaskAssignmentCreateWithoutTaskInput = {
  cycleKey: string
  status: number
  progress?: number
  target?: number
  claimedAt?: Date | string | null
  completedAt?: Date | string | null
  expiredAt?: Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  user: Prisma.AppUserCreateNestedOneWithoutTaskAssignmentsInput
  progressLogs?: Prisma.TaskProgressLogCreateNestedManyWithoutAssignmentInput
}

export type TaskAssignmentUncheckedCreateWithoutTaskInput = {
  id?: number
  userId: number
  cycleKey: string
  status: number
  progress?: number
  target?: number
  claimedAt?: Date | string | null
  completedAt?: Date | string | null
  expiredAt?: Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  progressLogs?: Prisma.TaskProgressLogUncheckedCreateNestedManyWithoutAssignmentInput
}

export type TaskAssignmentCreateOrConnectWithoutTaskInput = {
  where: Prisma.TaskAssignmentWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutTaskInput, Prisma.TaskAssignmentUncheckedCreateWithoutTaskInput>
}

export type TaskAssignmentCreateManyTaskInputEnvelope = {
  data: Prisma.TaskAssignmentCreateManyTaskInput | Prisma.TaskAssignmentCreateManyTaskInput[]
  skipDuplicates?: boolean
}

export type TaskAssignmentUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.TaskAssignmentWhereUniqueInput
  update: Prisma.XOR<Prisma.TaskAssignmentUpdateWithoutTaskInput, Prisma.TaskAssignmentUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.TaskAssignmentCreateWithoutTaskInput, Prisma.TaskAssignmentUncheckedCreateWithoutTaskInput>
}

export type TaskAssignmentUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.TaskAssignmentWhereUniqueInput
  data: Prisma.XOR<Prisma.TaskAssignmentUpdateWithoutTaskInput, Prisma.TaskAssignmentUncheckedUpdateWithoutTaskInput>
}

export type TaskAssignmentUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.TaskAssignmentScalarWhereInput
  data: Prisma.XOR<Prisma.TaskAssignmentUpdateManyMutationInput, Prisma.TaskAssignmentUncheckedUpdateManyWithoutTaskInput>
}

export type TaskAssignmentCreateManyUserInput = {
  id?: number
  taskId: number
  cycleKey: string
  status: number
  progress?: number
  target?: number
  claimedAt?: Date | string | null
  completedAt?: Date | string | null
  expiredAt?: Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type TaskAssignmentUpdateWithoutUserInput = {
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  task?: Prisma.TaskUpdateOneRequiredWithoutAssignmentsNestedInput
  progressLogs?: Prisma.TaskProgressLogUpdateManyWithoutAssignmentNestedInput
}

export type TaskAssignmentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  taskId?: Prisma.IntFieldUpdateOperationsInput | number
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  progressLogs?: Prisma.TaskProgressLogUncheckedUpdateManyWithoutAssignmentNestedInput
}

export type TaskAssignmentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  taskId?: Prisma.IntFieldUpdateOperationsInput | number
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TaskAssignmentCreateManyTaskInput = {
  id?: number
  userId: number
  cycleKey: string
  status: number
  progress?: number
  target?: number
  claimedAt?: Date | string | null
  completedAt?: Date | string | null
  expiredAt?: Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type TaskAssignmentUpdateWithoutTaskInput = {
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.AppUserUpdateOneRequiredWithoutTaskAssignmentsNestedInput
  progressLogs?: Prisma.TaskProgressLogUpdateManyWithoutAssignmentNestedInput
}

export type TaskAssignmentUncheckedUpdateWithoutTaskInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  progressLogs?: Prisma.TaskProgressLogUncheckedUpdateManyWithoutAssignmentNestedInput
}

export type TaskAssignmentUncheckedUpdateManyWithoutTaskInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  cycleKey?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  target?: Prisma.IntFieldUpdateOperationsInput | number
  claimedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskSnapshot?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  context?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type TaskAssignmentCountOutputType
 */

export type TaskAssignmentCountOutputType = {
  progressLogs: number
}

export type TaskAssignmentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  progressLogs?: boolean | TaskAssignmentCountOutputTypeCountProgressLogsArgs
}

/**
 * TaskAssignmentCountOutputType without action
 */
export type TaskAssignmentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignmentCountOutputType
   */
  select?: Prisma.TaskAssignmentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TaskAssignmentCountOutputType without action
 */
export type TaskAssignmentCountOutputTypeCountProgressLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaskProgressLogWhereInput
}


export type TaskAssignmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskId?: boolean
  userId?: boolean
  cycleKey?: boolean
  status?: boolean
  progress?: boolean
  target?: boolean
  claimedAt?: boolean
  completedAt?: boolean
  expiredAt?: boolean
  taskSnapshot?: boolean
  context?: boolean
  version?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.AppUserDefaultArgs<ExtArgs>
  progressLogs?: boolean | Prisma.TaskAssignment$progressLogsArgs<ExtArgs>
  _count?: boolean | Prisma.TaskAssignmentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taskAssignment"]>

export type TaskAssignmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskId?: boolean
  userId?: boolean
  cycleKey?: boolean
  status?: boolean
  progress?: boolean
  target?: boolean
  claimedAt?: boolean
  completedAt?: boolean
  expiredAt?: boolean
  taskSnapshot?: boolean
  context?: boolean
  version?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.AppUserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taskAssignment"]>

export type TaskAssignmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskId?: boolean
  userId?: boolean
  cycleKey?: boolean
  status?: boolean
  progress?: boolean
  target?: boolean
  claimedAt?: boolean
  completedAt?: boolean
  expiredAt?: boolean
  taskSnapshot?: boolean
  context?: boolean
  version?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.AppUserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taskAssignment"]>

export type TaskAssignmentSelectScalar = {
  id?: boolean
  taskId?: boolean
  userId?: boolean
  cycleKey?: boolean
  status?: boolean
  progress?: boolean
  target?: boolean
  claimedAt?: boolean
  completedAt?: boolean
  expiredAt?: boolean
  taskSnapshot?: boolean
  context?: boolean
  version?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type TaskAssignmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "taskId" | "userId" | "cycleKey" | "status" | "progress" | "target" | "claimedAt" | "completedAt" | "expiredAt" | "taskSnapshot" | "context" | "version" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["taskAssignment"]>
export type TaskAssignmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.AppUserDefaultArgs<ExtArgs>
  progressLogs?: boolean | Prisma.TaskAssignment$progressLogsArgs<ExtArgs>
  _count?: boolean | Prisma.TaskAssignmentCountOutputTypeDefaultArgs<ExtArgs>
}
export type TaskAssignmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.AppUserDefaultArgs<ExtArgs>
}
export type TaskAssignmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.AppUserDefaultArgs<ExtArgs>
}

export type $TaskAssignmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TaskAssignment"
  objects: {
    /**
     * 任务关联
     */
    task: Prisma.$TaskPayload<ExtArgs>
    /**
     * 用户关联
     */
    user: Prisma.$AppUserPayload<ExtArgs>
    /**
     * 任务进度日志关联
     */
    progressLogs: Prisma.$TaskProgressLogPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    /**
     * 主键id
     */
    id: number
    /**
     * 任务ID
     */
    taskId: number
    /**
     * 用户ID
     */
    userId: number
    /**
     * 周期标识
     */
    cycleKey: string
    /**
     * 分配状态
     */
    status: number
    /**
     * 当前进度
     */
    progress: number
    /**
     * 目标次数
     */
    target: number
    /**
     * 领取时间
     */
    claimedAt: Date | null
    /**
     * 完成时间
     */
    completedAt: Date | null
    /**
     * 过期时间
     */
    expiredAt: Date | null
    /**
     * 任务快照
     */
    taskSnapshot: runtime.JsonValue | null
    /**
     * 任务上下文
     */
    context: runtime.JsonValue | null
    /**
     * 版本号
     */
    version: number
    /**
     * 创建时间
     */
    createdAt: Date
    /**
     * 更新时间
     */
    updatedAt: Date
    /**
     * 删除时间
     */
    deletedAt: Date | null
  }, ExtArgs["result"]["taskAssignment"]>
  composites: {}
}

export type TaskAssignmentGetPayload<S extends boolean | null | undefined | TaskAssignmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload, S>

export type TaskAssignmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TaskAssignmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: TaskAssignmentCountAggregateInputType | true
  }

export interface TaskAssignmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TaskAssignment'], meta: { name: 'TaskAssignment' } }
  /**
   * Find zero or one TaskAssignment that matches the filter.
   * @param {TaskAssignmentFindUniqueArgs} args - Arguments to find a TaskAssignment
   * @example
   * // Get one TaskAssignment
   * const taskAssignment = await prisma.taskAssignment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TaskAssignmentFindUniqueArgs>(args: Prisma.SelectSubset<T, TaskAssignmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TaskAssignmentClient<runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TaskAssignment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TaskAssignmentFindUniqueOrThrowArgs} args - Arguments to find a TaskAssignment
   * @example
   * // Get one TaskAssignment
   * const taskAssignment = await prisma.taskAssignment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TaskAssignmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TaskAssignmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaskAssignmentClient<runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaskAssignment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskAssignmentFindFirstArgs} args - Arguments to find a TaskAssignment
   * @example
   * // Get one TaskAssignment
   * const taskAssignment = await prisma.taskAssignment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TaskAssignmentFindFirstArgs>(args?: Prisma.SelectSubset<T, TaskAssignmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__TaskAssignmentClient<runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaskAssignment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskAssignmentFindFirstOrThrowArgs} args - Arguments to find a TaskAssignment
   * @example
   * // Get one TaskAssignment
   * const taskAssignment = await prisma.taskAssignment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TaskAssignmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TaskAssignmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaskAssignmentClient<runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TaskAssignments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskAssignmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TaskAssignments
   * const taskAssignments = await prisma.taskAssignment.findMany()
   * 
   * // Get first 10 TaskAssignments
   * const taskAssignments = await prisma.taskAssignment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const taskAssignmentWithIdOnly = await prisma.taskAssignment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TaskAssignmentFindManyArgs>(args?: Prisma.SelectSubset<T, TaskAssignmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TaskAssignment.
   * @param {TaskAssignmentCreateArgs} args - Arguments to create a TaskAssignment.
   * @example
   * // Create one TaskAssignment
   * const TaskAssignment = await prisma.taskAssignment.create({
   *   data: {
   *     // ... data to create a TaskAssignment
   *   }
   * })
   * 
   */
  create<T extends TaskAssignmentCreateArgs>(args: Prisma.SelectSubset<T, TaskAssignmentCreateArgs<ExtArgs>>): Prisma.Prisma__TaskAssignmentClient<runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TaskAssignments.
   * @param {TaskAssignmentCreateManyArgs} args - Arguments to create many TaskAssignments.
   * @example
   * // Create many TaskAssignments
   * const taskAssignment = await prisma.taskAssignment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TaskAssignmentCreateManyArgs>(args?: Prisma.SelectSubset<T, TaskAssignmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TaskAssignments and returns the data saved in the database.
   * @param {TaskAssignmentCreateManyAndReturnArgs} args - Arguments to create many TaskAssignments.
   * @example
   * // Create many TaskAssignments
   * const taskAssignment = await prisma.taskAssignment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TaskAssignments and only return the `id`
   * const taskAssignmentWithIdOnly = await prisma.taskAssignment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TaskAssignmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TaskAssignmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TaskAssignment.
   * @param {TaskAssignmentDeleteArgs} args - Arguments to delete one TaskAssignment.
   * @example
   * // Delete one TaskAssignment
   * const TaskAssignment = await prisma.taskAssignment.delete({
   *   where: {
   *     // ... filter to delete one TaskAssignment
   *   }
   * })
   * 
   */
  delete<T extends TaskAssignmentDeleteArgs>(args: Prisma.SelectSubset<T, TaskAssignmentDeleteArgs<ExtArgs>>): Prisma.Prisma__TaskAssignmentClient<runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TaskAssignment.
   * @param {TaskAssignmentUpdateArgs} args - Arguments to update one TaskAssignment.
   * @example
   * // Update one TaskAssignment
   * const taskAssignment = await prisma.taskAssignment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TaskAssignmentUpdateArgs>(args: Prisma.SelectSubset<T, TaskAssignmentUpdateArgs<ExtArgs>>): Prisma.Prisma__TaskAssignmentClient<runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TaskAssignments.
   * @param {TaskAssignmentDeleteManyArgs} args - Arguments to filter TaskAssignments to delete.
   * @example
   * // Delete a few TaskAssignments
   * const { count } = await prisma.taskAssignment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TaskAssignmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, TaskAssignmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaskAssignments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskAssignmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TaskAssignments
   * const taskAssignment = await prisma.taskAssignment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TaskAssignmentUpdateManyArgs>(args: Prisma.SelectSubset<T, TaskAssignmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaskAssignments and returns the data updated in the database.
   * @param {TaskAssignmentUpdateManyAndReturnArgs} args - Arguments to update many TaskAssignments.
   * @example
   * // Update many TaskAssignments
   * const taskAssignment = await prisma.taskAssignment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TaskAssignments and only return the `id`
   * const taskAssignmentWithIdOnly = await prisma.taskAssignment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TaskAssignmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TaskAssignmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TaskAssignment.
   * @param {TaskAssignmentUpsertArgs} args - Arguments to update or create a TaskAssignment.
   * @example
   * // Update or create a TaskAssignment
   * const taskAssignment = await prisma.taskAssignment.upsert({
   *   create: {
   *     // ... data to create a TaskAssignment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TaskAssignment we want to update
   *   }
   * })
   */
  upsert<T extends TaskAssignmentUpsertArgs>(args: Prisma.SelectSubset<T, TaskAssignmentUpsertArgs<ExtArgs>>): Prisma.Prisma__TaskAssignmentClient<runtime.Types.Result.GetResult<Prisma.$TaskAssignmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TaskAssignments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskAssignmentCountArgs} args - Arguments to filter TaskAssignments to count.
   * @example
   * // Count the number of TaskAssignments
   * const count = await prisma.taskAssignment.count({
   *   where: {
   *     // ... the filter for the TaskAssignments we want to count
   *   }
   * })
  **/
  count<T extends TaskAssignmentCountArgs>(
    args?: Prisma.Subset<T, TaskAssignmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TaskAssignmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TaskAssignment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskAssignmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TaskAssignmentAggregateArgs>(args: Prisma.Subset<T, TaskAssignmentAggregateArgs>): Prisma.PrismaPromise<GetTaskAssignmentAggregateType<T>>

  /**
   * Group by TaskAssignment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskAssignmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TaskAssignmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TaskAssignmentGroupByArgs['orderBy'] }
      : { orderBy?: TaskAssignmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TaskAssignmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTaskAssignmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TaskAssignment model
 */
readonly fields: TaskAssignmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TaskAssignment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TaskAssignmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  task<T extends Prisma.TaskDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.AppUserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppUserDefaultArgs<ExtArgs>>): Prisma.Prisma__AppUserClient<runtime.Types.Result.GetResult<Prisma.$AppUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  progressLogs<T extends Prisma.TaskAssignment$progressLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskAssignment$progressLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskProgressLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TaskAssignment model
 */
export interface TaskAssignmentFieldRefs {
  readonly id: Prisma.FieldRef<"TaskAssignment", 'Int'>
  readonly taskId: Prisma.FieldRef<"TaskAssignment", 'Int'>
  readonly userId: Prisma.FieldRef<"TaskAssignment", 'Int'>
  readonly cycleKey: Prisma.FieldRef<"TaskAssignment", 'String'>
  readonly status: Prisma.FieldRef<"TaskAssignment", 'Int'>
  readonly progress: Prisma.FieldRef<"TaskAssignment", 'Int'>
  readonly target: Prisma.FieldRef<"TaskAssignment", 'Int'>
  readonly claimedAt: Prisma.FieldRef<"TaskAssignment", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"TaskAssignment", 'DateTime'>
  readonly expiredAt: Prisma.FieldRef<"TaskAssignment", 'DateTime'>
  readonly taskSnapshot: Prisma.FieldRef<"TaskAssignment", 'Json'>
  readonly context: Prisma.FieldRef<"TaskAssignment", 'Json'>
  readonly version: Prisma.FieldRef<"TaskAssignment", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TaskAssignment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TaskAssignment", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"TaskAssignment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TaskAssignment findUnique
 */
export type TaskAssignmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which TaskAssignment to fetch.
   */
  where: Prisma.TaskAssignmentWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TaskAssignment findUniqueOrThrow
 */
export type TaskAssignmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which TaskAssignment to fetch.
   */
  where: Prisma.TaskAssignmentWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TaskAssignment findFirst
 */
export type TaskAssignmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which TaskAssignment to fetch.
   */
  where?: Prisma.TaskAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskAssignments to fetch.
   */
  orderBy?: Prisma.TaskAssignmentOrderByWithRelationInput | Prisma.TaskAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaskAssignments.
   */
  cursor?: Prisma.TaskAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskAssignments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaskAssignments.
   */
  distinct?: Prisma.TaskAssignmentScalarFieldEnum | Prisma.TaskAssignmentScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TaskAssignment findFirstOrThrow
 */
export type TaskAssignmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which TaskAssignment to fetch.
   */
  where?: Prisma.TaskAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskAssignments to fetch.
   */
  orderBy?: Prisma.TaskAssignmentOrderByWithRelationInput | Prisma.TaskAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaskAssignments.
   */
  cursor?: Prisma.TaskAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskAssignments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaskAssignments.
   */
  distinct?: Prisma.TaskAssignmentScalarFieldEnum | Prisma.TaskAssignmentScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TaskAssignment findMany
 */
export type TaskAssignmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which TaskAssignments to fetch.
   */
  where?: Prisma.TaskAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskAssignments to fetch.
   */
  orderBy?: Prisma.TaskAssignmentOrderByWithRelationInput | Prisma.TaskAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TaskAssignments.
   */
  cursor?: Prisma.TaskAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskAssignments.
   */
  skip?: number
  distinct?: Prisma.TaskAssignmentScalarFieldEnum | Prisma.TaskAssignmentScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TaskAssignment create
 */
export type TaskAssignmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentInclude<ExtArgs> | null
  /**
   * The data needed to create a TaskAssignment.
   */
  data: Prisma.XOR<Prisma.TaskAssignmentCreateInput, Prisma.TaskAssignmentUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TaskAssignment createMany
 */
export type TaskAssignmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TaskAssignments.
   */
  data: Prisma.TaskAssignmentCreateManyInput | Prisma.TaskAssignmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TaskAssignment createManyAndReturn
 */
export type TaskAssignmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * The data used to create many TaskAssignments.
   */
  data: Prisma.TaskAssignmentCreateManyInput | Prisma.TaskAssignmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TaskAssignment update
 */
export type TaskAssignmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentInclude<ExtArgs> | null
  /**
   * The data needed to update a TaskAssignment.
   */
  data: Prisma.XOR<Prisma.TaskAssignmentUpdateInput, Prisma.TaskAssignmentUncheckedUpdateInput>
  /**
   * Choose, which TaskAssignment to update.
   */
  where: Prisma.TaskAssignmentWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TaskAssignment updateMany
 */
export type TaskAssignmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TaskAssignments.
   */
  data: Prisma.XOR<Prisma.TaskAssignmentUpdateManyMutationInput, Prisma.TaskAssignmentUncheckedUpdateManyInput>
  /**
   * Filter which TaskAssignments to update
   */
  where?: Prisma.TaskAssignmentWhereInput
  /**
   * Limit how many TaskAssignments to update.
   */
  limit?: number
}

/**
 * TaskAssignment updateManyAndReturn
 */
export type TaskAssignmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * The data used to update TaskAssignments.
   */
  data: Prisma.XOR<Prisma.TaskAssignmentUpdateManyMutationInput, Prisma.TaskAssignmentUncheckedUpdateManyInput>
  /**
   * Filter which TaskAssignments to update
   */
  where?: Prisma.TaskAssignmentWhereInput
  /**
   * Limit how many TaskAssignments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TaskAssignment upsert
 */
export type TaskAssignmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentInclude<ExtArgs> | null
  /**
   * The filter to search for the TaskAssignment to update in case it exists.
   */
  where: Prisma.TaskAssignmentWhereUniqueInput
  /**
   * In case the TaskAssignment found by the `where` argument doesn't exist, create a new TaskAssignment with this data.
   */
  create: Prisma.XOR<Prisma.TaskAssignmentCreateInput, Prisma.TaskAssignmentUncheckedCreateInput>
  /**
   * In case the TaskAssignment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TaskAssignmentUpdateInput, Prisma.TaskAssignmentUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TaskAssignment delete
 */
export type TaskAssignmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentInclude<ExtArgs> | null
  /**
   * Filter which TaskAssignment to delete.
   */
  where: Prisma.TaskAssignmentWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TaskAssignment deleteMany
 */
export type TaskAssignmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaskAssignments to delete
   */
  where?: Prisma.TaskAssignmentWhereInput
  /**
   * Limit how many TaskAssignments to delete.
   */
  limit?: number
}

/**
 * TaskAssignment.progressLogs
 */
export type TaskAssignment$progressLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskProgressLog
   */
  select?: Prisma.TaskProgressLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskProgressLog
   */
  omit?: Prisma.TaskProgressLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskProgressLogInclude<ExtArgs> | null
  where?: Prisma.TaskProgressLogWhereInput
  orderBy?: Prisma.TaskProgressLogOrderByWithRelationInput | Prisma.TaskProgressLogOrderByWithRelationInput[]
  cursor?: Prisma.TaskProgressLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TaskProgressLogScalarFieldEnum | Prisma.TaskProgressLogScalarFieldEnum[]
}

/**
 * TaskAssignment without action
 */
export type TaskAssignmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskAssignment
   */
  select?: Prisma.TaskAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskAssignment
   */
  omit?: Prisma.TaskAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskAssignmentInclude<ExtArgs> | null
}
