
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ForumModerator` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ForumModerator
 * 论坛版主表 - 管理论坛版主信息，包括角色类型、权限设置、启用状态等
 */
export type ForumModeratorModel = runtime.Types.Result.DefaultSelection<Prisma.$ForumModeratorPayload>

export type AggregateForumModerator = {
  _count: ForumModeratorCountAggregateOutputType | null
  _avg: ForumModeratorAvgAggregateOutputType | null
  _sum: ForumModeratorSumAggregateOutputType | null
  _min: ForumModeratorMinAggregateOutputType | null
  _max: ForumModeratorMaxAggregateOutputType | null
}

export type ForumModeratorAvgAggregateOutputType = {
  id: number | null
  userId: number | null
  roleType: number | null
  groupId: number | null
  permissions: number | null
}

export type ForumModeratorSumAggregateOutputType = {
  id: number | null
  userId: number | null
  roleType: number | null
  groupId: number | null
  permissions: number[]
}

export type ForumModeratorMinAggregateOutputType = {
  id: number | null
  userId: number | null
  roleType: number | null
  groupId: number | null
  isEnabled: boolean | null
  remark: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type ForumModeratorMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  roleType: number | null
  groupId: number | null
  isEnabled: boolean | null
  remark: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type ForumModeratorCountAggregateOutputType = {
  id: number
  userId: number
  roleType: number
  groupId: number
  permissions: number
  isEnabled: number
  remark: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type ForumModeratorAvgAggregateInputType = {
  id?: true
  userId?: true
  roleType?: true
  groupId?: true
  permissions?: true
}

export type ForumModeratorSumAggregateInputType = {
  id?: true
  userId?: true
  roleType?: true
  groupId?: true
  permissions?: true
}

export type ForumModeratorMinAggregateInputType = {
  id?: true
  userId?: true
  roleType?: true
  groupId?: true
  isEnabled?: true
  remark?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type ForumModeratorMaxAggregateInputType = {
  id?: true
  userId?: true
  roleType?: true
  groupId?: true
  isEnabled?: true
  remark?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type ForumModeratorCountAggregateInputType = {
  id?: true
  userId?: true
  roleType?: true
  groupId?: true
  permissions?: true
  isEnabled?: true
  remark?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type ForumModeratorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ForumModerator to aggregate.
   */
  where?: Prisma.ForumModeratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumModerators to fetch.
   */
  orderBy?: Prisma.ForumModeratorOrderByWithRelationInput | Prisma.ForumModeratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ForumModeratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumModerators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumModerators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ForumModerators
  **/
  _count?: true | ForumModeratorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ForumModeratorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ForumModeratorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ForumModeratorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ForumModeratorMaxAggregateInputType
}

export type GetForumModeratorAggregateType<T extends ForumModeratorAggregateArgs> = {
      [P in keyof T & keyof AggregateForumModerator]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateForumModerator[P]>
    : Prisma.GetScalarType<T[P], AggregateForumModerator[P]>
}




export type ForumModeratorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ForumModeratorWhereInput
  orderBy?: Prisma.ForumModeratorOrderByWithAggregationInput | Prisma.ForumModeratorOrderByWithAggregationInput[]
  by: Prisma.ForumModeratorScalarFieldEnum[] | Prisma.ForumModeratorScalarFieldEnum
  having?: Prisma.ForumModeratorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ForumModeratorCountAggregateInputType | true
  _avg?: ForumModeratorAvgAggregateInputType
  _sum?: ForumModeratorSumAggregateInputType
  _min?: ForumModeratorMinAggregateInputType
  _max?: ForumModeratorMaxAggregateInputType
}

export type ForumModeratorGroupByOutputType = {
  id: number
  userId: number
  roleType: number
  groupId: number | null
  permissions: number[]
  isEnabled: boolean
  remark: string | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: ForumModeratorCountAggregateOutputType | null
  _avg: ForumModeratorAvgAggregateOutputType | null
  _sum: ForumModeratorSumAggregateOutputType | null
  _min: ForumModeratorMinAggregateOutputType | null
  _max: ForumModeratorMaxAggregateOutputType | null
}

type GetForumModeratorGroupByPayload<T extends ForumModeratorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ForumModeratorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ForumModeratorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ForumModeratorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ForumModeratorGroupByOutputType[P]>
      }
    >
  >



export type ForumModeratorWhereInput = {
  AND?: Prisma.ForumModeratorWhereInput | Prisma.ForumModeratorWhereInput[]
  OR?: Prisma.ForumModeratorWhereInput[]
  NOT?: Prisma.ForumModeratorWhereInput | Prisma.ForumModeratorWhereInput[]
  id?: Prisma.IntFilter<"ForumModerator"> | number
  userId?: Prisma.IntFilter<"ForumModerator"> | number
  roleType?: Prisma.IntFilter<"ForumModerator"> | number
  groupId?: Prisma.IntNullableFilter<"ForumModerator"> | number | null
  permissions?: Prisma.IntNullableListFilter<"ForumModerator">
  isEnabled?: Prisma.BoolFilter<"ForumModerator"> | boolean
  remark?: Prisma.StringNullableFilter<"ForumModerator"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ForumModerator"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ForumModerator"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"ForumModerator"> | Date | string | null
  profile?: Prisma.XOR<Prisma.ForumProfileScalarRelationFilter, Prisma.ForumProfileWhereInput>
  group?: Prisma.XOR<Prisma.ForumSectionGroupNullableScalarRelationFilter, Prisma.ForumSectionGroupWhereInput> | null
  actionLogs?: Prisma.ForumModeratorActionLogListRelationFilter
  sections?: Prisma.ForumModeratorSectionListRelationFilter
}

export type ForumModeratorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleType?: Prisma.SortOrder
  groupId?: Prisma.SortOrderInput | Prisma.SortOrder
  permissions?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  remark?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  profile?: Prisma.ForumProfileOrderByWithRelationInput
  group?: Prisma.ForumSectionGroupOrderByWithRelationInput
  actionLogs?: Prisma.ForumModeratorActionLogOrderByRelationAggregateInput
  sections?: Prisma.ForumModeratorSectionOrderByRelationAggregateInput
}

export type ForumModeratorWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  userId?: number
  AND?: Prisma.ForumModeratorWhereInput | Prisma.ForumModeratorWhereInput[]
  OR?: Prisma.ForumModeratorWhereInput[]
  NOT?: Prisma.ForumModeratorWhereInput | Prisma.ForumModeratorWhereInput[]
  roleType?: Prisma.IntFilter<"ForumModerator"> | number
  groupId?: Prisma.IntNullableFilter<"ForumModerator"> | number | null
  permissions?: Prisma.IntNullableListFilter<"ForumModerator">
  isEnabled?: Prisma.BoolFilter<"ForumModerator"> | boolean
  remark?: Prisma.StringNullableFilter<"ForumModerator"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ForumModerator"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ForumModerator"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"ForumModerator"> | Date | string | null
  profile?: Prisma.XOR<Prisma.ForumProfileScalarRelationFilter, Prisma.ForumProfileWhereInput>
  group?: Prisma.XOR<Prisma.ForumSectionGroupNullableScalarRelationFilter, Prisma.ForumSectionGroupWhereInput> | null
  actionLogs?: Prisma.ForumModeratorActionLogListRelationFilter
  sections?: Prisma.ForumModeratorSectionListRelationFilter
}, "id" | "userId">

export type ForumModeratorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleType?: Prisma.SortOrder
  groupId?: Prisma.SortOrderInput | Prisma.SortOrder
  permissions?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  remark?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ForumModeratorCountOrderByAggregateInput
  _avg?: Prisma.ForumModeratorAvgOrderByAggregateInput
  _max?: Prisma.ForumModeratorMaxOrderByAggregateInput
  _min?: Prisma.ForumModeratorMinOrderByAggregateInput
  _sum?: Prisma.ForumModeratorSumOrderByAggregateInput
}

export type ForumModeratorScalarWhereWithAggregatesInput = {
  AND?: Prisma.ForumModeratorScalarWhereWithAggregatesInput | Prisma.ForumModeratorScalarWhereWithAggregatesInput[]
  OR?: Prisma.ForumModeratorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ForumModeratorScalarWhereWithAggregatesInput | Prisma.ForumModeratorScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ForumModerator"> | number
  userId?: Prisma.IntWithAggregatesFilter<"ForumModerator"> | number
  roleType?: Prisma.IntWithAggregatesFilter<"ForumModerator"> | number
  groupId?: Prisma.IntNullableWithAggregatesFilter<"ForumModerator"> | number | null
  permissions?: Prisma.IntNullableListFilter<"ForumModerator">
  isEnabled?: Prisma.BoolWithAggregatesFilter<"ForumModerator"> | boolean
  remark?: Prisma.StringNullableWithAggregatesFilter<"ForumModerator"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ForumModerator"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ForumModerator"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ForumModerator"> | Date | string | null
}

export type ForumModeratorCreateInput = {
  roleType?: number
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  profile: Prisma.ForumProfileCreateNestedOneWithoutModeratorInput
  group?: Prisma.ForumSectionGroupCreateNestedOneWithoutModeratorsInput
  actionLogs?: Prisma.ForumModeratorActionLogCreateNestedManyWithoutModeratorInput
  sections?: Prisma.ForumModeratorSectionCreateNestedManyWithoutModeratorInput
}

export type ForumModeratorUncheckedCreateInput = {
  id?: number
  userId: number
  roleType?: number
  groupId?: number | null
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  actionLogs?: Prisma.ForumModeratorActionLogUncheckedCreateNestedManyWithoutModeratorInput
  sections?: Prisma.ForumModeratorSectionUncheckedCreateNestedManyWithoutModeratorInput
}

export type ForumModeratorUpdateInput = {
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  profile?: Prisma.ForumProfileUpdateOneRequiredWithoutModeratorNestedInput
  group?: Prisma.ForumSectionGroupUpdateOneWithoutModeratorsNestedInput
  actionLogs?: Prisma.ForumModeratorActionLogUpdateManyWithoutModeratorNestedInput
  sections?: Prisma.ForumModeratorSectionUpdateManyWithoutModeratorNestedInput
}

export type ForumModeratorUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  groupId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  actionLogs?: Prisma.ForumModeratorActionLogUncheckedUpdateManyWithoutModeratorNestedInput
  sections?: Prisma.ForumModeratorSectionUncheckedUpdateManyWithoutModeratorNestedInput
}

export type ForumModeratorCreateManyInput = {
  id?: number
  userId: number
  roleType?: number
  groupId?: number | null
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type ForumModeratorUpdateManyMutationInput = {
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ForumModeratorUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  groupId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ForumModeratorScalarRelationFilter = {
  is?: Prisma.ForumModeratorWhereInput
  isNot?: Prisma.ForumModeratorWhereInput
}

export type ForumModeratorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleType?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  remark?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ForumModeratorAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleType?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
}

export type ForumModeratorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleType?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  remark?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ForumModeratorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleType?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  remark?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ForumModeratorSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleType?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
}

export type ForumModeratorNullableScalarRelationFilter = {
  is?: Prisma.ForumModeratorWhereInput | null
  isNot?: Prisma.ForumModeratorWhereInput | null
}

export type ForumModeratorListRelationFilter = {
  every?: Prisma.ForumModeratorWhereInput
  some?: Prisma.ForumModeratorWhereInput
  none?: Prisma.ForumModeratorWhereInput
}

export type ForumModeratorOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ForumModeratorCreateNestedOneWithoutActionLogsInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutActionLogsInput, Prisma.ForumModeratorUncheckedCreateWithoutActionLogsInput>
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutActionLogsInput
  connect?: Prisma.ForumModeratorWhereUniqueInput
}

export type ForumModeratorUpdateOneRequiredWithoutActionLogsNestedInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutActionLogsInput, Prisma.ForumModeratorUncheckedCreateWithoutActionLogsInput>
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutActionLogsInput
  upsert?: Prisma.ForumModeratorUpsertWithoutActionLogsInput
  connect?: Prisma.ForumModeratorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ForumModeratorUpdateToOneWithWhereWithoutActionLogsInput, Prisma.ForumModeratorUpdateWithoutActionLogsInput>, Prisma.ForumModeratorUncheckedUpdateWithoutActionLogsInput>
}

export type ForumModeratorCreateNestedOneWithoutSectionsInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutSectionsInput, Prisma.ForumModeratorUncheckedCreateWithoutSectionsInput>
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutSectionsInput
  connect?: Prisma.ForumModeratorWhereUniqueInput
}

export type ForumModeratorUpdateOneRequiredWithoutSectionsNestedInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutSectionsInput, Prisma.ForumModeratorUncheckedCreateWithoutSectionsInput>
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutSectionsInput
  upsert?: Prisma.ForumModeratorUpsertWithoutSectionsInput
  connect?: Prisma.ForumModeratorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ForumModeratorUpdateToOneWithWhereWithoutSectionsInput, Prisma.ForumModeratorUpdateWithoutSectionsInput>, Prisma.ForumModeratorUncheckedUpdateWithoutSectionsInput>
}

export type ForumModeratorCreatepermissionsInput = {
  set: number[]
}

export type ForumModeratorUpdatepermissionsInput = {
  set?: number[]
  push?: number | number[]
}

export type ForumModeratorCreateNestedOneWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutProfileInput, Prisma.ForumModeratorUncheckedCreateWithoutProfileInput>
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutProfileInput
  connect?: Prisma.ForumModeratorWhereUniqueInput
}

export type ForumModeratorUncheckedCreateNestedOneWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutProfileInput, Prisma.ForumModeratorUncheckedCreateWithoutProfileInput>
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutProfileInput
  connect?: Prisma.ForumModeratorWhereUniqueInput
}

export type ForumModeratorUpdateOneWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutProfileInput, Prisma.ForumModeratorUncheckedCreateWithoutProfileInput>
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutProfileInput
  upsert?: Prisma.ForumModeratorUpsertWithoutProfileInput
  disconnect?: Prisma.ForumModeratorWhereInput | boolean
  delete?: Prisma.ForumModeratorWhereInput | boolean
  connect?: Prisma.ForumModeratorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ForumModeratorUpdateToOneWithWhereWithoutProfileInput, Prisma.ForumModeratorUpdateWithoutProfileInput>, Prisma.ForumModeratorUncheckedUpdateWithoutProfileInput>
}

export type ForumModeratorUncheckedUpdateOneWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutProfileInput, Prisma.ForumModeratorUncheckedCreateWithoutProfileInput>
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutProfileInput
  upsert?: Prisma.ForumModeratorUpsertWithoutProfileInput
  disconnect?: Prisma.ForumModeratorWhereInput | boolean
  delete?: Prisma.ForumModeratorWhereInput | boolean
  connect?: Prisma.ForumModeratorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ForumModeratorUpdateToOneWithWhereWithoutProfileInput, Prisma.ForumModeratorUpdateWithoutProfileInput>, Prisma.ForumModeratorUncheckedUpdateWithoutProfileInput>
}

export type ForumModeratorCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutGroupInput, Prisma.ForumModeratorUncheckedCreateWithoutGroupInput> | Prisma.ForumModeratorCreateWithoutGroupInput[] | Prisma.ForumModeratorUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutGroupInput | Prisma.ForumModeratorCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.ForumModeratorCreateManyGroupInputEnvelope
  connect?: Prisma.ForumModeratorWhereUniqueInput | Prisma.ForumModeratorWhereUniqueInput[]
}

export type ForumModeratorUncheckedCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutGroupInput, Prisma.ForumModeratorUncheckedCreateWithoutGroupInput> | Prisma.ForumModeratorCreateWithoutGroupInput[] | Prisma.ForumModeratorUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutGroupInput | Prisma.ForumModeratorCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.ForumModeratorCreateManyGroupInputEnvelope
  connect?: Prisma.ForumModeratorWhereUniqueInput | Prisma.ForumModeratorWhereUniqueInput[]
}

export type ForumModeratorUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutGroupInput, Prisma.ForumModeratorUncheckedCreateWithoutGroupInput> | Prisma.ForumModeratorCreateWithoutGroupInput[] | Prisma.ForumModeratorUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutGroupInput | Prisma.ForumModeratorCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.ForumModeratorUpsertWithWhereUniqueWithoutGroupInput | Prisma.ForumModeratorUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.ForumModeratorCreateManyGroupInputEnvelope
  set?: Prisma.ForumModeratorWhereUniqueInput | Prisma.ForumModeratorWhereUniqueInput[]
  disconnect?: Prisma.ForumModeratorWhereUniqueInput | Prisma.ForumModeratorWhereUniqueInput[]
  delete?: Prisma.ForumModeratorWhereUniqueInput | Prisma.ForumModeratorWhereUniqueInput[]
  connect?: Prisma.ForumModeratorWhereUniqueInput | Prisma.ForumModeratorWhereUniqueInput[]
  update?: Prisma.ForumModeratorUpdateWithWhereUniqueWithoutGroupInput | Prisma.ForumModeratorUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.ForumModeratorUpdateManyWithWhereWithoutGroupInput | Prisma.ForumModeratorUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.ForumModeratorScalarWhereInput | Prisma.ForumModeratorScalarWhereInput[]
}

export type ForumModeratorUncheckedUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorCreateWithoutGroupInput, Prisma.ForumModeratorUncheckedCreateWithoutGroupInput> | Prisma.ForumModeratorCreateWithoutGroupInput[] | Prisma.ForumModeratorUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.ForumModeratorCreateOrConnectWithoutGroupInput | Prisma.ForumModeratorCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.ForumModeratorUpsertWithWhereUniqueWithoutGroupInput | Prisma.ForumModeratorUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.ForumModeratorCreateManyGroupInputEnvelope
  set?: Prisma.ForumModeratorWhereUniqueInput | Prisma.ForumModeratorWhereUniqueInput[]
  disconnect?: Prisma.ForumModeratorWhereUniqueInput | Prisma.ForumModeratorWhereUniqueInput[]
  delete?: Prisma.ForumModeratorWhereUniqueInput | Prisma.ForumModeratorWhereUniqueInput[]
  connect?: Prisma.ForumModeratorWhereUniqueInput | Prisma.ForumModeratorWhereUniqueInput[]
  update?: Prisma.ForumModeratorUpdateWithWhereUniqueWithoutGroupInput | Prisma.ForumModeratorUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.ForumModeratorUpdateManyWithWhereWithoutGroupInput | Prisma.ForumModeratorUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.ForumModeratorScalarWhereInput | Prisma.ForumModeratorScalarWhereInput[]
}

export type ForumModeratorCreateWithoutActionLogsInput = {
  roleType?: number
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  profile: Prisma.ForumProfileCreateNestedOneWithoutModeratorInput
  group?: Prisma.ForumSectionGroupCreateNestedOneWithoutModeratorsInput
  sections?: Prisma.ForumModeratorSectionCreateNestedManyWithoutModeratorInput
}

export type ForumModeratorUncheckedCreateWithoutActionLogsInput = {
  id?: number
  userId: number
  roleType?: number
  groupId?: number | null
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  sections?: Prisma.ForumModeratorSectionUncheckedCreateNestedManyWithoutModeratorInput
}

export type ForumModeratorCreateOrConnectWithoutActionLogsInput = {
  where: Prisma.ForumModeratorWhereUniqueInput
  create: Prisma.XOR<Prisma.ForumModeratorCreateWithoutActionLogsInput, Prisma.ForumModeratorUncheckedCreateWithoutActionLogsInput>
}

export type ForumModeratorUpsertWithoutActionLogsInput = {
  update: Prisma.XOR<Prisma.ForumModeratorUpdateWithoutActionLogsInput, Prisma.ForumModeratorUncheckedUpdateWithoutActionLogsInput>
  create: Prisma.XOR<Prisma.ForumModeratorCreateWithoutActionLogsInput, Prisma.ForumModeratorUncheckedCreateWithoutActionLogsInput>
  where?: Prisma.ForumModeratorWhereInput
}

export type ForumModeratorUpdateToOneWithWhereWithoutActionLogsInput = {
  where?: Prisma.ForumModeratorWhereInput
  data: Prisma.XOR<Prisma.ForumModeratorUpdateWithoutActionLogsInput, Prisma.ForumModeratorUncheckedUpdateWithoutActionLogsInput>
}

export type ForumModeratorUpdateWithoutActionLogsInput = {
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  profile?: Prisma.ForumProfileUpdateOneRequiredWithoutModeratorNestedInput
  group?: Prisma.ForumSectionGroupUpdateOneWithoutModeratorsNestedInput
  sections?: Prisma.ForumModeratorSectionUpdateManyWithoutModeratorNestedInput
}

export type ForumModeratorUncheckedUpdateWithoutActionLogsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  groupId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sections?: Prisma.ForumModeratorSectionUncheckedUpdateManyWithoutModeratorNestedInput
}

export type ForumModeratorCreateWithoutSectionsInput = {
  roleType?: number
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  profile: Prisma.ForumProfileCreateNestedOneWithoutModeratorInput
  group?: Prisma.ForumSectionGroupCreateNestedOneWithoutModeratorsInput
  actionLogs?: Prisma.ForumModeratorActionLogCreateNestedManyWithoutModeratorInput
}

export type ForumModeratorUncheckedCreateWithoutSectionsInput = {
  id?: number
  userId: number
  roleType?: number
  groupId?: number | null
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  actionLogs?: Prisma.ForumModeratorActionLogUncheckedCreateNestedManyWithoutModeratorInput
}

export type ForumModeratorCreateOrConnectWithoutSectionsInput = {
  where: Prisma.ForumModeratorWhereUniqueInput
  create: Prisma.XOR<Prisma.ForumModeratorCreateWithoutSectionsInput, Prisma.ForumModeratorUncheckedCreateWithoutSectionsInput>
}

export type ForumModeratorUpsertWithoutSectionsInput = {
  update: Prisma.XOR<Prisma.ForumModeratorUpdateWithoutSectionsInput, Prisma.ForumModeratorUncheckedUpdateWithoutSectionsInput>
  create: Prisma.XOR<Prisma.ForumModeratorCreateWithoutSectionsInput, Prisma.ForumModeratorUncheckedCreateWithoutSectionsInput>
  where?: Prisma.ForumModeratorWhereInput
}

export type ForumModeratorUpdateToOneWithWhereWithoutSectionsInput = {
  where?: Prisma.ForumModeratorWhereInput
  data: Prisma.XOR<Prisma.ForumModeratorUpdateWithoutSectionsInput, Prisma.ForumModeratorUncheckedUpdateWithoutSectionsInput>
}

export type ForumModeratorUpdateWithoutSectionsInput = {
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  profile?: Prisma.ForumProfileUpdateOneRequiredWithoutModeratorNestedInput
  group?: Prisma.ForumSectionGroupUpdateOneWithoutModeratorsNestedInput
  actionLogs?: Prisma.ForumModeratorActionLogUpdateManyWithoutModeratorNestedInput
}

export type ForumModeratorUncheckedUpdateWithoutSectionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  groupId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  actionLogs?: Prisma.ForumModeratorActionLogUncheckedUpdateManyWithoutModeratorNestedInput
}

export type ForumModeratorCreateWithoutProfileInput = {
  roleType?: number
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  group?: Prisma.ForumSectionGroupCreateNestedOneWithoutModeratorsInput
  actionLogs?: Prisma.ForumModeratorActionLogCreateNestedManyWithoutModeratorInput
  sections?: Prisma.ForumModeratorSectionCreateNestedManyWithoutModeratorInput
}

export type ForumModeratorUncheckedCreateWithoutProfileInput = {
  id?: number
  roleType?: number
  groupId?: number | null
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  actionLogs?: Prisma.ForumModeratorActionLogUncheckedCreateNestedManyWithoutModeratorInput
  sections?: Prisma.ForumModeratorSectionUncheckedCreateNestedManyWithoutModeratorInput
}

export type ForumModeratorCreateOrConnectWithoutProfileInput = {
  where: Prisma.ForumModeratorWhereUniqueInput
  create: Prisma.XOR<Prisma.ForumModeratorCreateWithoutProfileInput, Prisma.ForumModeratorUncheckedCreateWithoutProfileInput>
}

export type ForumModeratorUpsertWithoutProfileInput = {
  update: Prisma.XOR<Prisma.ForumModeratorUpdateWithoutProfileInput, Prisma.ForumModeratorUncheckedUpdateWithoutProfileInput>
  create: Prisma.XOR<Prisma.ForumModeratorCreateWithoutProfileInput, Prisma.ForumModeratorUncheckedCreateWithoutProfileInput>
  where?: Prisma.ForumModeratorWhereInput
}

export type ForumModeratorUpdateToOneWithWhereWithoutProfileInput = {
  where?: Prisma.ForumModeratorWhereInput
  data: Prisma.XOR<Prisma.ForumModeratorUpdateWithoutProfileInput, Prisma.ForumModeratorUncheckedUpdateWithoutProfileInput>
}

export type ForumModeratorUpdateWithoutProfileInput = {
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  group?: Prisma.ForumSectionGroupUpdateOneWithoutModeratorsNestedInput
  actionLogs?: Prisma.ForumModeratorActionLogUpdateManyWithoutModeratorNestedInput
  sections?: Prisma.ForumModeratorSectionUpdateManyWithoutModeratorNestedInput
}

export type ForumModeratorUncheckedUpdateWithoutProfileInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  groupId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  actionLogs?: Prisma.ForumModeratorActionLogUncheckedUpdateManyWithoutModeratorNestedInput
  sections?: Prisma.ForumModeratorSectionUncheckedUpdateManyWithoutModeratorNestedInput
}

export type ForumModeratorCreateWithoutGroupInput = {
  roleType?: number
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  profile: Prisma.ForumProfileCreateNestedOneWithoutModeratorInput
  actionLogs?: Prisma.ForumModeratorActionLogCreateNestedManyWithoutModeratorInput
  sections?: Prisma.ForumModeratorSectionCreateNestedManyWithoutModeratorInput
}

export type ForumModeratorUncheckedCreateWithoutGroupInput = {
  id?: number
  userId: number
  roleType?: number
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  actionLogs?: Prisma.ForumModeratorActionLogUncheckedCreateNestedManyWithoutModeratorInput
  sections?: Prisma.ForumModeratorSectionUncheckedCreateNestedManyWithoutModeratorInput
}

export type ForumModeratorCreateOrConnectWithoutGroupInput = {
  where: Prisma.ForumModeratorWhereUniqueInput
  create: Prisma.XOR<Prisma.ForumModeratorCreateWithoutGroupInput, Prisma.ForumModeratorUncheckedCreateWithoutGroupInput>
}

export type ForumModeratorCreateManyGroupInputEnvelope = {
  data: Prisma.ForumModeratorCreateManyGroupInput | Prisma.ForumModeratorCreateManyGroupInput[]
  skipDuplicates?: boolean
}

export type ForumModeratorUpsertWithWhereUniqueWithoutGroupInput = {
  where: Prisma.ForumModeratorWhereUniqueInput
  update: Prisma.XOR<Prisma.ForumModeratorUpdateWithoutGroupInput, Prisma.ForumModeratorUncheckedUpdateWithoutGroupInput>
  create: Prisma.XOR<Prisma.ForumModeratorCreateWithoutGroupInput, Prisma.ForumModeratorUncheckedCreateWithoutGroupInput>
}

export type ForumModeratorUpdateWithWhereUniqueWithoutGroupInput = {
  where: Prisma.ForumModeratorWhereUniqueInput
  data: Prisma.XOR<Prisma.ForumModeratorUpdateWithoutGroupInput, Prisma.ForumModeratorUncheckedUpdateWithoutGroupInput>
}

export type ForumModeratorUpdateManyWithWhereWithoutGroupInput = {
  where: Prisma.ForumModeratorScalarWhereInput
  data: Prisma.XOR<Prisma.ForumModeratorUpdateManyMutationInput, Prisma.ForumModeratorUncheckedUpdateManyWithoutGroupInput>
}

export type ForumModeratorScalarWhereInput = {
  AND?: Prisma.ForumModeratorScalarWhereInput | Prisma.ForumModeratorScalarWhereInput[]
  OR?: Prisma.ForumModeratorScalarWhereInput[]
  NOT?: Prisma.ForumModeratorScalarWhereInput | Prisma.ForumModeratorScalarWhereInput[]
  id?: Prisma.IntFilter<"ForumModerator"> | number
  userId?: Prisma.IntFilter<"ForumModerator"> | number
  roleType?: Prisma.IntFilter<"ForumModerator"> | number
  groupId?: Prisma.IntNullableFilter<"ForumModerator"> | number | null
  permissions?: Prisma.IntNullableListFilter<"ForumModerator">
  isEnabled?: Prisma.BoolFilter<"ForumModerator"> | boolean
  remark?: Prisma.StringNullableFilter<"ForumModerator"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ForumModerator"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ForumModerator"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"ForumModerator"> | Date | string | null
}

export type ForumModeratorCreateManyGroupInput = {
  id?: number
  userId: number
  roleType?: number
  permissions?: Prisma.ForumModeratorCreatepermissionsInput | number[]
  isEnabled?: boolean
  remark?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type ForumModeratorUpdateWithoutGroupInput = {
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  profile?: Prisma.ForumProfileUpdateOneRequiredWithoutModeratorNestedInput
  actionLogs?: Prisma.ForumModeratorActionLogUpdateManyWithoutModeratorNestedInput
  sections?: Prisma.ForumModeratorSectionUpdateManyWithoutModeratorNestedInput
}

export type ForumModeratorUncheckedUpdateWithoutGroupInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  actionLogs?: Prisma.ForumModeratorActionLogUncheckedUpdateManyWithoutModeratorNestedInput
  sections?: Prisma.ForumModeratorSectionUncheckedUpdateManyWithoutModeratorNestedInput
}

export type ForumModeratorUncheckedUpdateManyWithoutGroupInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  roleType?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorUpdatepermissionsInput | number[]
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type ForumModeratorCountOutputType
 */

export type ForumModeratorCountOutputType = {
  actionLogs: number
  sections: number
}

export type ForumModeratorCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actionLogs?: boolean | ForumModeratorCountOutputTypeCountActionLogsArgs
  sections?: boolean | ForumModeratorCountOutputTypeCountSectionsArgs
}

/**
 * ForumModeratorCountOutputType without action
 */
export type ForumModeratorCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorCountOutputType
   */
  select?: Prisma.ForumModeratorCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ForumModeratorCountOutputType without action
 */
export type ForumModeratorCountOutputTypeCountActionLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ForumModeratorActionLogWhereInput
}

/**
 * ForumModeratorCountOutputType without action
 */
export type ForumModeratorCountOutputTypeCountSectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ForumModeratorSectionWhereInput
}


export type ForumModeratorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  roleType?: boolean
  groupId?: boolean
  permissions?: boolean
  isEnabled?: boolean
  remark?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  profile?: boolean | Prisma.ForumProfileDefaultArgs<ExtArgs>
  group?: boolean | Prisma.ForumModerator$groupArgs<ExtArgs>
  actionLogs?: boolean | Prisma.ForumModerator$actionLogsArgs<ExtArgs>
  sections?: boolean | Prisma.ForumModerator$sectionsArgs<ExtArgs>
  _count?: boolean | Prisma.ForumModeratorCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["forumModerator"]>

export type ForumModeratorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  roleType?: boolean
  groupId?: boolean
  permissions?: boolean
  isEnabled?: boolean
  remark?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  profile?: boolean | Prisma.ForumProfileDefaultArgs<ExtArgs>
  group?: boolean | Prisma.ForumModerator$groupArgs<ExtArgs>
}, ExtArgs["result"]["forumModerator"]>

export type ForumModeratorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  roleType?: boolean
  groupId?: boolean
  permissions?: boolean
  isEnabled?: boolean
  remark?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  profile?: boolean | Prisma.ForumProfileDefaultArgs<ExtArgs>
  group?: boolean | Prisma.ForumModerator$groupArgs<ExtArgs>
}, ExtArgs["result"]["forumModerator"]>

export type ForumModeratorSelectScalar = {
  id?: boolean
  userId?: boolean
  roleType?: boolean
  groupId?: boolean
  permissions?: boolean
  isEnabled?: boolean
  remark?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type ForumModeratorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "roleType" | "groupId" | "permissions" | "isEnabled" | "remark" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["forumModerator"]>
export type ForumModeratorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profile?: boolean | Prisma.ForumProfileDefaultArgs<ExtArgs>
  group?: boolean | Prisma.ForumModerator$groupArgs<ExtArgs>
  actionLogs?: boolean | Prisma.ForumModerator$actionLogsArgs<ExtArgs>
  sections?: boolean | Prisma.ForumModerator$sectionsArgs<ExtArgs>
  _count?: boolean | Prisma.ForumModeratorCountOutputTypeDefaultArgs<ExtArgs>
}
export type ForumModeratorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profile?: boolean | Prisma.ForumProfileDefaultArgs<ExtArgs>
  group?: boolean | Prisma.ForumModerator$groupArgs<ExtArgs>
}
export type ForumModeratorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profile?: boolean | Prisma.ForumProfileDefaultArgs<ExtArgs>
  group?: boolean | Prisma.ForumModerator$groupArgs<ExtArgs>
}

export type $ForumModeratorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ForumModerator"
  objects: {
    profile: Prisma.$ForumProfilePayload<ExtArgs>
    group: Prisma.$ForumSectionGroupPayload<ExtArgs> | null
    actionLogs: Prisma.$ForumModeratorActionLogPayload<ExtArgs>[]
    sections: Prisma.$ForumModeratorSectionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    /**
     * 主键ID
     */
    id: number
    /**
     * 关联的用户ID
     */
    userId: number
    /**
     * 版主角色类型（1=超级版主，2=分组版主，3=板块版主）
     */
    roleType: number
    /**
     * 关联的分组ID（分组版主时必填）
     */
    groupId: number | null
    /**
     * 权限数组（1=置顶, 2=加精, 3=锁定, 4=删除, 5=审核, 6=移动）
     */
    permissions: number[]
    /**
     * 是否启用
     */
    isEnabled: boolean
    /**
     * 备注
     */
    remark: string | null
    /**
     * 创建时间
     */
    createdAt: Date
    /**
     * 更新时间
     */
    updatedAt: Date
    /**
     * 软删除时间
     */
    deletedAt: Date | null
  }, ExtArgs["result"]["forumModerator"]>
  composites: {}
}

export type ForumModeratorGetPayload<S extends boolean | null | undefined | ForumModeratorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload, S>

export type ForumModeratorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ForumModeratorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: ForumModeratorCountAggregateInputType | true
  }

export interface ForumModeratorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ForumModerator'], meta: { name: 'ForumModerator' } }
  /**
   * Find zero or one ForumModerator that matches the filter.
   * @param {ForumModeratorFindUniqueArgs} args - Arguments to find a ForumModerator
   * @example
   * // Get one ForumModerator
   * const forumModerator = await prisma.forumModerator.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ForumModeratorFindUniqueArgs>(args: Prisma.SelectSubset<T, ForumModeratorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ForumModerator that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ForumModeratorFindUniqueOrThrowArgs} args - Arguments to find a ForumModerator
   * @example
   * // Get one ForumModerator
   * const forumModerator = await prisma.forumModerator.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ForumModeratorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ForumModeratorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ForumModerator that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorFindFirstArgs} args - Arguments to find a ForumModerator
   * @example
   * // Get one ForumModerator
   * const forumModerator = await prisma.forumModerator.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ForumModeratorFindFirstArgs>(args?: Prisma.SelectSubset<T, ForumModeratorFindFirstArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ForumModerator that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorFindFirstOrThrowArgs} args - Arguments to find a ForumModerator
   * @example
   * // Get one ForumModerator
   * const forumModerator = await prisma.forumModerator.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ForumModeratorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ForumModeratorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ForumModerators that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ForumModerators
   * const forumModerators = await prisma.forumModerator.findMany()
   * 
   * // Get first 10 ForumModerators
   * const forumModerators = await prisma.forumModerator.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const forumModeratorWithIdOnly = await prisma.forumModerator.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ForumModeratorFindManyArgs>(args?: Prisma.SelectSubset<T, ForumModeratorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ForumModerator.
   * @param {ForumModeratorCreateArgs} args - Arguments to create a ForumModerator.
   * @example
   * // Create one ForumModerator
   * const ForumModerator = await prisma.forumModerator.create({
   *   data: {
   *     // ... data to create a ForumModerator
   *   }
   * })
   * 
   */
  create<T extends ForumModeratorCreateArgs>(args: Prisma.SelectSubset<T, ForumModeratorCreateArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ForumModerators.
   * @param {ForumModeratorCreateManyArgs} args - Arguments to create many ForumModerators.
   * @example
   * // Create many ForumModerators
   * const forumModerator = await prisma.forumModerator.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ForumModeratorCreateManyArgs>(args?: Prisma.SelectSubset<T, ForumModeratorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ForumModerators and returns the data saved in the database.
   * @param {ForumModeratorCreateManyAndReturnArgs} args - Arguments to create many ForumModerators.
   * @example
   * // Create many ForumModerators
   * const forumModerator = await prisma.forumModerator.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ForumModerators and only return the `id`
   * const forumModeratorWithIdOnly = await prisma.forumModerator.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ForumModeratorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ForumModeratorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ForumModerator.
   * @param {ForumModeratorDeleteArgs} args - Arguments to delete one ForumModerator.
   * @example
   * // Delete one ForumModerator
   * const ForumModerator = await prisma.forumModerator.delete({
   *   where: {
   *     // ... filter to delete one ForumModerator
   *   }
   * })
   * 
   */
  delete<T extends ForumModeratorDeleteArgs>(args: Prisma.SelectSubset<T, ForumModeratorDeleteArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ForumModerator.
   * @param {ForumModeratorUpdateArgs} args - Arguments to update one ForumModerator.
   * @example
   * // Update one ForumModerator
   * const forumModerator = await prisma.forumModerator.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ForumModeratorUpdateArgs>(args: Prisma.SelectSubset<T, ForumModeratorUpdateArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ForumModerators.
   * @param {ForumModeratorDeleteManyArgs} args - Arguments to filter ForumModerators to delete.
   * @example
   * // Delete a few ForumModerators
   * const { count } = await prisma.forumModerator.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ForumModeratorDeleteManyArgs>(args?: Prisma.SelectSubset<T, ForumModeratorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ForumModerators.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ForumModerators
   * const forumModerator = await prisma.forumModerator.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ForumModeratorUpdateManyArgs>(args: Prisma.SelectSubset<T, ForumModeratorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ForumModerators and returns the data updated in the database.
   * @param {ForumModeratorUpdateManyAndReturnArgs} args - Arguments to update many ForumModerators.
   * @example
   * // Update many ForumModerators
   * const forumModerator = await prisma.forumModerator.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ForumModerators and only return the `id`
   * const forumModeratorWithIdOnly = await prisma.forumModerator.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ForumModeratorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ForumModeratorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ForumModerator.
   * @param {ForumModeratorUpsertArgs} args - Arguments to update or create a ForumModerator.
   * @example
   * // Update or create a ForumModerator
   * const forumModerator = await prisma.forumModerator.upsert({
   *   create: {
   *     // ... data to create a ForumModerator
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ForumModerator we want to update
   *   }
   * })
   */
  upsert<T extends ForumModeratorUpsertArgs>(args: Prisma.SelectSubset<T, ForumModeratorUpsertArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ForumModerators.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorCountArgs} args - Arguments to filter ForumModerators to count.
   * @example
   * // Count the number of ForumModerators
   * const count = await prisma.forumModerator.count({
   *   where: {
   *     // ... the filter for the ForumModerators we want to count
   *   }
   * })
  **/
  count<T extends ForumModeratorCountArgs>(
    args?: Prisma.Subset<T, ForumModeratorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ForumModeratorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ForumModerator.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ForumModeratorAggregateArgs>(args: Prisma.Subset<T, ForumModeratorAggregateArgs>): Prisma.PrismaPromise<GetForumModeratorAggregateType<T>>

  /**
   * Group by ForumModerator.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ForumModeratorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ForumModeratorGroupByArgs['orderBy'] }
      : { orderBy?: ForumModeratorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ForumModeratorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetForumModeratorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ForumModerator model
 */
readonly fields: ForumModeratorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ForumModerator.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ForumModeratorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profile<T extends Prisma.ForumProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ForumProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__ForumProfileClient<runtime.Types.Result.GetResult<Prisma.$ForumProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  group<T extends Prisma.ForumModerator$groupArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ForumModerator$groupArgs<ExtArgs>>): Prisma.Prisma__ForumSectionGroupClient<runtime.Types.Result.GetResult<Prisma.$ForumSectionGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  actionLogs<T extends Prisma.ForumModerator$actionLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ForumModerator$actionLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumModeratorActionLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  sections<T extends Prisma.ForumModerator$sectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ForumModerator$sectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ForumModerator model
 */
export interface ForumModeratorFieldRefs {
  readonly id: Prisma.FieldRef<"ForumModerator", 'Int'>
  readonly userId: Prisma.FieldRef<"ForumModerator", 'Int'>
  readonly roleType: Prisma.FieldRef<"ForumModerator", 'Int'>
  readonly groupId: Prisma.FieldRef<"ForumModerator", 'Int'>
  readonly permissions: Prisma.FieldRef<"ForumModerator", 'Int[]'>
  readonly isEnabled: Prisma.FieldRef<"ForumModerator", 'Boolean'>
  readonly remark: Prisma.FieldRef<"ForumModerator", 'String'>
  readonly createdAt: Prisma.FieldRef<"ForumModerator", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ForumModerator", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"ForumModerator", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ForumModerator findUnique
 */
export type ForumModeratorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorInclude<ExtArgs> | null
  /**
   * Filter, which ForumModerator to fetch.
   */
  where: Prisma.ForumModeratorWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModerator findUniqueOrThrow
 */
export type ForumModeratorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorInclude<ExtArgs> | null
  /**
   * Filter, which ForumModerator to fetch.
   */
  where: Prisma.ForumModeratorWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModerator findFirst
 */
export type ForumModeratorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorInclude<ExtArgs> | null
  /**
   * Filter, which ForumModerator to fetch.
   */
  where?: Prisma.ForumModeratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumModerators to fetch.
   */
  orderBy?: Prisma.ForumModeratorOrderByWithRelationInput | Prisma.ForumModeratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ForumModerators.
   */
  cursor?: Prisma.ForumModeratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumModerators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumModerators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ForumModerators.
   */
  distinct?: Prisma.ForumModeratorScalarFieldEnum | Prisma.ForumModeratorScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModerator findFirstOrThrow
 */
export type ForumModeratorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorInclude<ExtArgs> | null
  /**
   * Filter, which ForumModerator to fetch.
   */
  where?: Prisma.ForumModeratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumModerators to fetch.
   */
  orderBy?: Prisma.ForumModeratorOrderByWithRelationInput | Prisma.ForumModeratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ForumModerators.
   */
  cursor?: Prisma.ForumModeratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumModerators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumModerators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ForumModerators.
   */
  distinct?: Prisma.ForumModeratorScalarFieldEnum | Prisma.ForumModeratorScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModerator findMany
 */
export type ForumModeratorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorInclude<ExtArgs> | null
  /**
   * Filter, which ForumModerators to fetch.
   */
  where?: Prisma.ForumModeratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumModerators to fetch.
   */
  orderBy?: Prisma.ForumModeratorOrderByWithRelationInput | Prisma.ForumModeratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ForumModerators.
   */
  cursor?: Prisma.ForumModeratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumModerators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumModerators.
   */
  skip?: number
  distinct?: Prisma.ForumModeratorScalarFieldEnum | Prisma.ForumModeratorScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModerator create
 */
export type ForumModeratorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorInclude<ExtArgs> | null
  /**
   * The data needed to create a ForumModerator.
   */
  data: Prisma.XOR<Prisma.ForumModeratorCreateInput, Prisma.ForumModeratorUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModerator createMany
 */
export type ForumModeratorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ForumModerators.
   */
  data: Prisma.ForumModeratorCreateManyInput | Prisma.ForumModeratorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ForumModerator createManyAndReturn
 */
export type ForumModeratorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * The data used to create many ForumModerators.
   */
  data: Prisma.ForumModeratorCreateManyInput | Prisma.ForumModeratorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ForumModerator update
 */
export type ForumModeratorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorInclude<ExtArgs> | null
  /**
   * The data needed to update a ForumModerator.
   */
  data: Prisma.XOR<Prisma.ForumModeratorUpdateInput, Prisma.ForumModeratorUncheckedUpdateInput>
  /**
   * Choose, which ForumModerator to update.
   */
  where: Prisma.ForumModeratorWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModerator updateMany
 */
export type ForumModeratorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ForumModerators.
   */
  data: Prisma.XOR<Prisma.ForumModeratorUpdateManyMutationInput, Prisma.ForumModeratorUncheckedUpdateManyInput>
  /**
   * Filter which ForumModerators to update
   */
  where?: Prisma.ForumModeratorWhereInput
  /**
   * Limit how many ForumModerators to update.
   */
  limit?: number
}

/**
 * ForumModerator updateManyAndReturn
 */
export type ForumModeratorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * The data used to update ForumModerators.
   */
  data: Prisma.XOR<Prisma.ForumModeratorUpdateManyMutationInput, Prisma.ForumModeratorUncheckedUpdateManyInput>
  /**
   * Filter which ForumModerators to update
   */
  where?: Prisma.ForumModeratorWhereInput
  /**
   * Limit how many ForumModerators to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ForumModerator upsert
 */
export type ForumModeratorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorInclude<ExtArgs> | null
  /**
   * The filter to search for the ForumModerator to update in case it exists.
   */
  where: Prisma.ForumModeratorWhereUniqueInput
  /**
   * In case the ForumModerator found by the `where` argument doesn't exist, create a new ForumModerator with this data.
   */
  create: Prisma.XOR<Prisma.ForumModeratorCreateInput, Prisma.ForumModeratorUncheckedCreateInput>
  /**
   * In case the ForumModerator was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ForumModeratorUpdateInput, Prisma.ForumModeratorUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModerator delete
 */
export type ForumModeratorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorInclude<ExtArgs> | null
  /**
   * Filter which ForumModerator to delete.
   */
  where: Prisma.ForumModeratorWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModerator deleteMany
 */
export type ForumModeratorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ForumModerators to delete
   */
  where?: Prisma.ForumModeratorWhereInput
  /**
   * Limit how many ForumModerators to delete.
   */
  limit?: number
}

/**
 * ForumModerator.group
 */
export type ForumModerator$groupArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumSectionGroup
   */
  select?: Prisma.ForumSectionGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumSectionGroup
   */
  omit?: Prisma.ForumSectionGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumSectionGroupInclude<ExtArgs> | null
  where?: Prisma.ForumSectionGroupWhereInput
}

/**
 * ForumModerator.actionLogs
 */
export type ForumModerator$actionLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorActionLog
   */
  select?: Prisma.ForumModeratorActionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorActionLog
   */
  omit?: Prisma.ForumModeratorActionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorActionLogInclude<ExtArgs> | null
  where?: Prisma.ForumModeratorActionLogWhereInput
  orderBy?: Prisma.ForumModeratorActionLogOrderByWithRelationInput | Prisma.ForumModeratorActionLogOrderByWithRelationInput[]
  cursor?: Prisma.ForumModeratorActionLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ForumModeratorActionLogScalarFieldEnum | Prisma.ForumModeratorActionLogScalarFieldEnum[]
}

/**
 * ForumModerator.sections
 */
export type ForumModerator$sectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionInclude<ExtArgs> | null
  where?: Prisma.ForumModeratorSectionWhereInput
  orderBy?: Prisma.ForumModeratorSectionOrderByWithRelationInput | Prisma.ForumModeratorSectionOrderByWithRelationInput[]
  cursor?: Prisma.ForumModeratorSectionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ForumModeratorSectionScalarFieldEnum | Prisma.ForumModeratorSectionScalarFieldEnum[]
}

/**
 * ForumModerator without action
 */
export type ForumModeratorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModerator
   */
  select?: Prisma.ForumModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModerator
   */
  omit?: Prisma.ForumModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorInclude<ExtArgs> | null
}
