
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ForumModeratorSection` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ForumModeratorSection
 * 论坛版主板块关联表 - 管理板块版主与板块的多对多关系，一个板块版主可以管理多个板块
 */
export type ForumModeratorSectionModel = runtime.Types.Result.DefaultSelection<Prisma.$ForumModeratorSectionPayload>

export type AggregateForumModeratorSection = {
  _count: ForumModeratorSectionCountAggregateOutputType | null
  _avg: ForumModeratorSectionAvgAggregateOutputType | null
  _sum: ForumModeratorSectionSumAggregateOutputType | null
  _min: ForumModeratorSectionMinAggregateOutputType | null
  _max: ForumModeratorSectionMaxAggregateOutputType | null
}

export type ForumModeratorSectionAvgAggregateOutputType = {
  id: number | null
  moderatorId: number | null
  sectionId: number | null
  permissions: number | null
}

export type ForumModeratorSectionSumAggregateOutputType = {
  id: number | null
  moderatorId: number | null
  sectionId: number | null
  permissions: number[]
}

export type ForumModeratorSectionMinAggregateOutputType = {
  id: number | null
  moderatorId: number | null
  sectionId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ForumModeratorSectionMaxAggregateOutputType = {
  id: number | null
  moderatorId: number | null
  sectionId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ForumModeratorSectionCountAggregateOutputType = {
  id: number
  moderatorId: number
  sectionId: number
  permissions: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ForumModeratorSectionAvgAggregateInputType = {
  id?: true
  moderatorId?: true
  sectionId?: true
  permissions?: true
}

export type ForumModeratorSectionSumAggregateInputType = {
  id?: true
  moderatorId?: true
  sectionId?: true
  permissions?: true
}

export type ForumModeratorSectionMinAggregateInputType = {
  id?: true
  moderatorId?: true
  sectionId?: true
  createdAt?: true
  updatedAt?: true
}

export type ForumModeratorSectionMaxAggregateInputType = {
  id?: true
  moderatorId?: true
  sectionId?: true
  createdAt?: true
  updatedAt?: true
}

export type ForumModeratorSectionCountAggregateInputType = {
  id?: true
  moderatorId?: true
  sectionId?: true
  permissions?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ForumModeratorSectionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ForumModeratorSection to aggregate.
   */
  where?: Prisma.ForumModeratorSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumModeratorSections to fetch.
   */
  orderBy?: Prisma.ForumModeratorSectionOrderByWithRelationInput | Prisma.ForumModeratorSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ForumModeratorSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumModeratorSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumModeratorSections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ForumModeratorSections
  **/
  _count?: true | ForumModeratorSectionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ForumModeratorSectionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ForumModeratorSectionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ForumModeratorSectionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ForumModeratorSectionMaxAggregateInputType
}

export type GetForumModeratorSectionAggregateType<T extends ForumModeratorSectionAggregateArgs> = {
      [P in keyof T & keyof AggregateForumModeratorSection]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateForumModeratorSection[P]>
    : Prisma.GetScalarType<T[P], AggregateForumModeratorSection[P]>
}




export type ForumModeratorSectionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ForumModeratorSectionWhereInput
  orderBy?: Prisma.ForumModeratorSectionOrderByWithAggregationInput | Prisma.ForumModeratorSectionOrderByWithAggregationInput[]
  by: Prisma.ForumModeratorSectionScalarFieldEnum[] | Prisma.ForumModeratorSectionScalarFieldEnum
  having?: Prisma.ForumModeratorSectionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ForumModeratorSectionCountAggregateInputType | true
  _avg?: ForumModeratorSectionAvgAggregateInputType
  _sum?: ForumModeratorSectionSumAggregateInputType
  _min?: ForumModeratorSectionMinAggregateInputType
  _max?: ForumModeratorSectionMaxAggregateInputType
}

export type ForumModeratorSectionGroupByOutputType = {
  id: number
  moderatorId: number
  sectionId: number
  permissions: number[]
  createdAt: Date
  updatedAt: Date
  _count: ForumModeratorSectionCountAggregateOutputType | null
  _avg: ForumModeratorSectionAvgAggregateOutputType | null
  _sum: ForumModeratorSectionSumAggregateOutputType | null
  _min: ForumModeratorSectionMinAggregateOutputType | null
  _max: ForumModeratorSectionMaxAggregateOutputType | null
}

type GetForumModeratorSectionGroupByPayload<T extends ForumModeratorSectionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ForumModeratorSectionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ForumModeratorSectionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ForumModeratorSectionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ForumModeratorSectionGroupByOutputType[P]>
      }
    >
  >



export type ForumModeratorSectionWhereInput = {
  AND?: Prisma.ForumModeratorSectionWhereInput | Prisma.ForumModeratorSectionWhereInput[]
  OR?: Prisma.ForumModeratorSectionWhereInput[]
  NOT?: Prisma.ForumModeratorSectionWhereInput | Prisma.ForumModeratorSectionWhereInput[]
  id?: Prisma.IntFilter<"ForumModeratorSection"> | number
  moderatorId?: Prisma.IntFilter<"ForumModeratorSection"> | number
  sectionId?: Prisma.IntFilter<"ForumModeratorSection"> | number
  permissions?: Prisma.IntNullableListFilter<"ForumModeratorSection">
  createdAt?: Prisma.DateTimeFilter<"ForumModeratorSection"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ForumModeratorSection"> | Date | string
  moderator?: Prisma.XOR<Prisma.ForumModeratorScalarRelationFilter, Prisma.ForumModeratorWhereInput>
  section?: Prisma.XOR<Prisma.ForumSectionScalarRelationFilter, Prisma.ForumSectionWhereInput>
}

export type ForumModeratorSectionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  moderatorId?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  moderator?: Prisma.ForumModeratorOrderByWithRelationInput
  section?: Prisma.ForumSectionOrderByWithRelationInput
}

export type ForumModeratorSectionWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  moderatorId_sectionId?: Prisma.ForumModeratorSectionModeratorIdSectionIdCompoundUniqueInput
  AND?: Prisma.ForumModeratorSectionWhereInput | Prisma.ForumModeratorSectionWhereInput[]
  OR?: Prisma.ForumModeratorSectionWhereInput[]
  NOT?: Prisma.ForumModeratorSectionWhereInput | Prisma.ForumModeratorSectionWhereInput[]
  moderatorId?: Prisma.IntFilter<"ForumModeratorSection"> | number
  sectionId?: Prisma.IntFilter<"ForumModeratorSection"> | number
  permissions?: Prisma.IntNullableListFilter<"ForumModeratorSection">
  createdAt?: Prisma.DateTimeFilter<"ForumModeratorSection"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ForumModeratorSection"> | Date | string
  moderator?: Prisma.XOR<Prisma.ForumModeratorScalarRelationFilter, Prisma.ForumModeratorWhereInput>
  section?: Prisma.XOR<Prisma.ForumSectionScalarRelationFilter, Prisma.ForumSectionWhereInput>
}, "id" | "moderatorId_sectionId">

export type ForumModeratorSectionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  moderatorId?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ForumModeratorSectionCountOrderByAggregateInput
  _avg?: Prisma.ForumModeratorSectionAvgOrderByAggregateInput
  _max?: Prisma.ForumModeratorSectionMaxOrderByAggregateInput
  _min?: Prisma.ForumModeratorSectionMinOrderByAggregateInput
  _sum?: Prisma.ForumModeratorSectionSumOrderByAggregateInput
}

export type ForumModeratorSectionScalarWhereWithAggregatesInput = {
  AND?: Prisma.ForumModeratorSectionScalarWhereWithAggregatesInput | Prisma.ForumModeratorSectionScalarWhereWithAggregatesInput[]
  OR?: Prisma.ForumModeratorSectionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ForumModeratorSectionScalarWhereWithAggregatesInput | Prisma.ForumModeratorSectionScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ForumModeratorSection"> | number
  moderatorId?: Prisma.IntWithAggregatesFilter<"ForumModeratorSection"> | number
  sectionId?: Prisma.IntWithAggregatesFilter<"ForumModeratorSection"> | number
  permissions?: Prisma.IntNullableListFilter<"ForumModeratorSection">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ForumModeratorSection"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ForumModeratorSection"> | Date | string
}

export type ForumModeratorSectionCreateInput = {
  permissions?: Prisma.ForumModeratorSectionCreatepermissionsInput | number[]
  createdAt?: Date | string
  updatedAt?: Date | string
  moderator: Prisma.ForumModeratorCreateNestedOneWithoutSectionsInput
  section: Prisma.ForumSectionCreateNestedOneWithoutModeratorSectionsInput
}

export type ForumModeratorSectionUncheckedCreateInput = {
  id?: number
  moderatorId: number
  sectionId: number
  permissions?: Prisma.ForumModeratorSectionCreatepermissionsInput | number[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ForumModeratorSectionUpdateInput = {
  permissions?: Prisma.ForumModeratorSectionUpdatepermissionsInput | number[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  moderator?: Prisma.ForumModeratorUpdateOneRequiredWithoutSectionsNestedInput
  section?: Prisma.ForumSectionUpdateOneRequiredWithoutModeratorSectionsNestedInput
}

export type ForumModeratorSectionUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  moderatorId?: Prisma.IntFieldUpdateOperationsInput | number
  sectionId?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorSectionUpdatepermissionsInput | number[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ForumModeratorSectionCreateManyInput = {
  id?: number
  moderatorId: number
  sectionId: number
  permissions?: Prisma.ForumModeratorSectionCreatepermissionsInput | number[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ForumModeratorSectionUpdateManyMutationInput = {
  permissions?: Prisma.ForumModeratorSectionUpdatepermissionsInput | number[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ForumModeratorSectionUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  moderatorId?: Prisma.IntFieldUpdateOperationsInput | number
  sectionId?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorSectionUpdatepermissionsInput | number[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ForumModeratorSectionModeratorIdSectionIdCompoundUniqueInput = {
  moderatorId: number
  sectionId: number
}

export type ForumModeratorSectionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  moderatorId?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ForumModeratorSectionAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  moderatorId?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
}

export type ForumModeratorSectionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  moderatorId?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ForumModeratorSectionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  moderatorId?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ForumModeratorSectionSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  moderatorId?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
}

export type ForumModeratorSectionListRelationFilter = {
  every?: Prisma.ForumModeratorSectionWhereInput
  some?: Prisma.ForumModeratorSectionWhereInput
  none?: Prisma.ForumModeratorSectionWhereInput
}

export type ForumModeratorSectionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ForumModeratorSectionCreatepermissionsInput = {
  set: number[]
}

export type ForumModeratorSectionUpdatepermissionsInput = {
  set?: number[]
  push?: number | number[]
}

export type ForumModeratorSectionCreateNestedManyWithoutModeratorInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutModeratorInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutModeratorInput> | Prisma.ForumModeratorSectionCreateWithoutModeratorInput[] | Prisma.ForumModeratorSectionUncheckedCreateWithoutModeratorInput[]
  connectOrCreate?: Prisma.ForumModeratorSectionCreateOrConnectWithoutModeratorInput | Prisma.ForumModeratorSectionCreateOrConnectWithoutModeratorInput[]
  createMany?: Prisma.ForumModeratorSectionCreateManyModeratorInputEnvelope
  connect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
}

export type ForumModeratorSectionUncheckedCreateNestedManyWithoutModeratorInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutModeratorInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutModeratorInput> | Prisma.ForumModeratorSectionCreateWithoutModeratorInput[] | Prisma.ForumModeratorSectionUncheckedCreateWithoutModeratorInput[]
  connectOrCreate?: Prisma.ForumModeratorSectionCreateOrConnectWithoutModeratorInput | Prisma.ForumModeratorSectionCreateOrConnectWithoutModeratorInput[]
  createMany?: Prisma.ForumModeratorSectionCreateManyModeratorInputEnvelope
  connect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
}

export type ForumModeratorSectionUpdateManyWithoutModeratorNestedInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutModeratorInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutModeratorInput> | Prisma.ForumModeratorSectionCreateWithoutModeratorInput[] | Prisma.ForumModeratorSectionUncheckedCreateWithoutModeratorInput[]
  connectOrCreate?: Prisma.ForumModeratorSectionCreateOrConnectWithoutModeratorInput | Prisma.ForumModeratorSectionCreateOrConnectWithoutModeratorInput[]
  upsert?: Prisma.ForumModeratorSectionUpsertWithWhereUniqueWithoutModeratorInput | Prisma.ForumModeratorSectionUpsertWithWhereUniqueWithoutModeratorInput[]
  createMany?: Prisma.ForumModeratorSectionCreateManyModeratorInputEnvelope
  set?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  disconnect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  delete?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  connect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  update?: Prisma.ForumModeratorSectionUpdateWithWhereUniqueWithoutModeratorInput | Prisma.ForumModeratorSectionUpdateWithWhereUniqueWithoutModeratorInput[]
  updateMany?: Prisma.ForumModeratorSectionUpdateManyWithWhereWithoutModeratorInput | Prisma.ForumModeratorSectionUpdateManyWithWhereWithoutModeratorInput[]
  deleteMany?: Prisma.ForumModeratorSectionScalarWhereInput | Prisma.ForumModeratorSectionScalarWhereInput[]
}

export type ForumModeratorSectionUncheckedUpdateManyWithoutModeratorNestedInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutModeratorInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutModeratorInput> | Prisma.ForumModeratorSectionCreateWithoutModeratorInput[] | Prisma.ForumModeratorSectionUncheckedCreateWithoutModeratorInput[]
  connectOrCreate?: Prisma.ForumModeratorSectionCreateOrConnectWithoutModeratorInput | Prisma.ForumModeratorSectionCreateOrConnectWithoutModeratorInput[]
  upsert?: Prisma.ForumModeratorSectionUpsertWithWhereUniqueWithoutModeratorInput | Prisma.ForumModeratorSectionUpsertWithWhereUniqueWithoutModeratorInput[]
  createMany?: Prisma.ForumModeratorSectionCreateManyModeratorInputEnvelope
  set?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  disconnect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  delete?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  connect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  update?: Prisma.ForumModeratorSectionUpdateWithWhereUniqueWithoutModeratorInput | Prisma.ForumModeratorSectionUpdateWithWhereUniqueWithoutModeratorInput[]
  updateMany?: Prisma.ForumModeratorSectionUpdateManyWithWhereWithoutModeratorInput | Prisma.ForumModeratorSectionUpdateManyWithWhereWithoutModeratorInput[]
  deleteMany?: Prisma.ForumModeratorSectionScalarWhereInput | Prisma.ForumModeratorSectionScalarWhereInput[]
}

export type ForumModeratorSectionCreateNestedManyWithoutSectionInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutSectionInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutSectionInput> | Prisma.ForumModeratorSectionCreateWithoutSectionInput[] | Prisma.ForumModeratorSectionUncheckedCreateWithoutSectionInput[]
  connectOrCreate?: Prisma.ForumModeratorSectionCreateOrConnectWithoutSectionInput | Prisma.ForumModeratorSectionCreateOrConnectWithoutSectionInput[]
  createMany?: Prisma.ForumModeratorSectionCreateManySectionInputEnvelope
  connect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
}

export type ForumModeratorSectionUncheckedCreateNestedManyWithoutSectionInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutSectionInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutSectionInput> | Prisma.ForumModeratorSectionCreateWithoutSectionInput[] | Prisma.ForumModeratorSectionUncheckedCreateWithoutSectionInput[]
  connectOrCreate?: Prisma.ForumModeratorSectionCreateOrConnectWithoutSectionInput | Prisma.ForumModeratorSectionCreateOrConnectWithoutSectionInput[]
  createMany?: Prisma.ForumModeratorSectionCreateManySectionInputEnvelope
  connect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
}

export type ForumModeratorSectionUpdateManyWithoutSectionNestedInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutSectionInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutSectionInput> | Prisma.ForumModeratorSectionCreateWithoutSectionInput[] | Prisma.ForumModeratorSectionUncheckedCreateWithoutSectionInput[]
  connectOrCreate?: Prisma.ForumModeratorSectionCreateOrConnectWithoutSectionInput | Prisma.ForumModeratorSectionCreateOrConnectWithoutSectionInput[]
  upsert?: Prisma.ForumModeratorSectionUpsertWithWhereUniqueWithoutSectionInput | Prisma.ForumModeratorSectionUpsertWithWhereUniqueWithoutSectionInput[]
  createMany?: Prisma.ForumModeratorSectionCreateManySectionInputEnvelope
  set?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  disconnect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  delete?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  connect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  update?: Prisma.ForumModeratorSectionUpdateWithWhereUniqueWithoutSectionInput | Prisma.ForumModeratorSectionUpdateWithWhereUniqueWithoutSectionInput[]
  updateMany?: Prisma.ForumModeratorSectionUpdateManyWithWhereWithoutSectionInput | Prisma.ForumModeratorSectionUpdateManyWithWhereWithoutSectionInput[]
  deleteMany?: Prisma.ForumModeratorSectionScalarWhereInput | Prisma.ForumModeratorSectionScalarWhereInput[]
}

export type ForumModeratorSectionUncheckedUpdateManyWithoutSectionNestedInput = {
  create?: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutSectionInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutSectionInput> | Prisma.ForumModeratorSectionCreateWithoutSectionInput[] | Prisma.ForumModeratorSectionUncheckedCreateWithoutSectionInput[]
  connectOrCreate?: Prisma.ForumModeratorSectionCreateOrConnectWithoutSectionInput | Prisma.ForumModeratorSectionCreateOrConnectWithoutSectionInput[]
  upsert?: Prisma.ForumModeratorSectionUpsertWithWhereUniqueWithoutSectionInput | Prisma.ForumModeratorSectionUpsertWithWhereUniqueWithoutSectionInput[]
  createMany?: Prisma.ForumModeratorSectionCreateManySectionInputEnvelope
  set?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  disconnect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  delete?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  connect?: Prisma.ForumModeratorSectionWhereUniqueInput | Prisma.ForumModeratorSectionWhereUniqueInput[]
  update?: Prisma.ForumModeratorSectionUpdateWithWhereUniqueWithoutSectionInput | Prisma.ForumModeratorSectionUpdateWithWhereUniqueWithoutSectionInput[]
  updateMany?: Prisma.ForumModeratorSectionUpdateManyWithWhereWithoutSectionInput | Prisma.ForumModeratorSectionUpdateManyWithWhereWithoutSectionInput[]
  deleteMany?: Prisma.ForumModeratorSectionScalarWhereInput | Prisma.ForumModeratorSectionScalarWhereInput[]
}

export type ForumModeratorSectionCreateWithoutModeratorInput = {
  permissions?: Prisma.ForumModeratorSectionCreatepermissionsInput | number[]
  createdAt?: Date | string
  updatedAt?: Date | string
  section: Prisma.ForumSectionCreateNestedOneWithoutModeratorSectionsInput
}

export type ForumModeratorSectionUncheckedCreateWithoutModeratorInput = {
  id?: number
  sectionId: number
  permissions?: Prisma.ForumModeratorSectionCreatepermissionsInput | number[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ForumModeratorSectionCreateOrConnectWithoutModeratorInput = {
  where: Prisma.ForumModeratorSectionWhereUniqueInput
  create: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutModeratorInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutModeratorInput>
}

export type ForumModeratorSectionCreateManyModeratorInputEnvelope = {
  data: Prisma.ForumModeratorSectionCreateManyModeratorInput | Prisma.ForumModeratorSectionCreateManyModeratorInput[]
  skipDuplicates?: boolean
}

export type ForumModeratorSectionUpsertWithWhereUniqueWithoutModeratorInput = {
  where: Prisma.ForumModeratorSectionWhereUniqueInput
  update: Prisma.XOR<Prisma.ForumModeratorSectionUpdateWithoutModeratorInput, Prisma.ForumModeratorSectionUncheckedUpdateWithoutModeratorInput>
  create: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutModeratorInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutModeratorInput>
}

export type ForumModeratorSectionUpdateWithWhereUniqueWithoutModeratorInput = {
  where: Prisma.ForumModeratorSectionWhereUniqueInput
  data: Prisma.XOR<Prisma.ForumModeratorSectionUpdateWithoutModeratorInput, Prisma.ForumModeratorSectionUncheckedUpdateWithoutModeratorInput>
}

export type ForumModeratorSectionUpdateManyWithWhereWithoutModeratorInput = {
  where: Prisma.ForumModeratorSectionScalarWhereInput
  data: Prisma.XOR<Prisma.ForumModeratorSectionUpdateManyMutationInput, Prisma.ForumModeratorSectionUncheckedUpdateManyWithoutModeratorInput>
}

export type ForumModeratorSectionScalarWhereInput = {
  AND?: Prisma.ForumModeratorSectionScalarWhereInput | Prisma.ForumModeratorSectionScalarWhereInput[]
  OR?: Prisma.ForumModeratorSectionScalarWhereInput[]
  NOT?: Prisma.ForumModeratorSectionScalarWhereInput | Prisma.ForumModeratorSectionScalarWhereInput[]
  id?: Prisma.IntFilter<"ForumModeratorSection"> | number
  moderatorId?: Prisma.IntFilter<"ForumModeratorSection"> | number
  sectionId?: Prisma.IntFilter<"ForumModeratorSection"> | number
  permissions?: Prisma.IntNullableListFilter<"ForumModeratorSection">
  createdAt?: Prisma.DateTimeFilter<"ForumModeratorSection"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ForumModeratorSection"> | Date | string
}

export type ForumModeratorSectionCreateWithoutSectionInput = {
  permissions?: Prisma.ForumModeratorSectionCreatepermissionsInput | number[]
  createdAt?: Date | string
  updatedAt?: Date | string
  moderator: Prisma.ForumModeratorCreateNestedOneWithoutSectionsInput
}

export type ForumModeratorSectionUncheckedCreateWithoutSectionInput = {
  id?: number
  moderatorId: number
  permissions?: Prisma.ForumModeratorSectionCreatepermissionsInput | number[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ForumModeratorSectionCreateOrConnectWithoutSectionInput = {
  where: Prisma.ForumModeratorSectionWhereUniqueInput
  create: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutSectionInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutSectionInput>
}

export type ForumModeratorSectionCreateManySectionInputEnvelope = {
  data: Prisma.ForumModeratorSectionCreateManySectionInput | Prisma.ForumModeratorSectionCreateManySectionInput[]
  skipDuplicates?: boolean
}

export type ForumModeratorSectionUpsertWithWhereUniqueWithoutSectionInput = {
  where: Prisma.ForumModeratorSectionWhereUniqueInput
  update: Prisma.XOR<Prisma.ForumModeratorSectionUpdateWithoutSectionInput, Prisma.ForumModeratorSectionUncheckedUpdateWithoutSectionInput>
  create: Prisma.XOR<Prisma.ForumModeratorSectionCreateWithoutSectionInput, Prisma.ForumModeratorSectionUncheckedCreateWithoutSectionInput>
}

export type ForumModeratorSectionUpdateWithWhereUniqueWithoutSectionInput = {
  where: Prisma.ForumModeratorSectionWhereUniqueInput
  data: Prisma.XOR<Prisma.ForumModeratorSectionUpdateWithoutSectionInput, Prisma.ForumModeratorSectionUncheckedUpdateWithoutSectionInput>
}

export type ForumModeratorSectionUpdateManyWithWhereWithoutSectionInput = {
  where: Prisma.ForumModeratorSectionScalarWhereInput
  data: Prisma.XOR<Prisma.ForumModeratorSectionUpdateManyMutationInput, Prisma.ForumModeratorSectionUncheckedUpdateManyWithoutSectionInput>
}

export type ForumModeratorSectionCreateManyModeratorInput = {
  id?: number
  sectionId: number
  permissions?: Prisma.ForumModeratorSectionCreatepermissionsInput | number[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ForumModeratorSectionUpdateWithoutModeratorInput = {
  permissions?: Prisma.ForumModeratorSectionUpdatepermissionsInput | number[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  section?: Prisma.ForumSectionUpdateOneRequiredWithoutModeratorSectionsNestedInput
}

export type ForumModeratorSectionUncheckedUpdateWithoutModeratorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sectionId?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorSectionUpdatepermissionsInput | number[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ForumModeratorSectionUncheckedUpdateManyWithoutModeratorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sectionId?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorSectionUpdatepermissionsInput | number[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ForumModeratorSectionCreateManySectionInput = {
  id?: number
  moderatorId: number
  permissions?: Prisma.ForumModeratorSectionCreatepermissionsInput | number[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ForumModeratorSectionUpdateWithoutSectionInput = {
  permissions?: Prisma.ForumModeratorSectionUpdatepermissionsInput | number[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  moderator?: Prisma.ForumModeratorUpdateOneRequiredWithoutSectionsNestedInput
}

export type ForumModeratorSectionUncheckedUpdateWithoutSectionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  moderatorId?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorSectionUpdatepermissionsInput | number[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ForumModeratorSectionUncheckedUpdateManyWithoutSectionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  moderatorId?: Prisma.IntFieldUpdateOperationsInput | number
  permissions?: Prisma.ForumModeratorSectionUpdatepermissionsInput | number[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ForumModeratorSectionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  moderatorId?: boolean
  sectionId?: boolean
  permissions?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  moderator?: boolean | Prisma.ForumModeratorDefaultArgs<ExtArgs>
  section?: boolean | Prisma.ForumSectionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["forumModeratorSection"]>

export type ForumModeratorSectionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  moderatorId?: boolean
  sectionId?: boolean
  permissions?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  moderator?: boolean | Prisma.ForumModeratorDefaultArgs<ExtArgs>
  section?: boolean | Prisma.ForumSectionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["forumModeratorSection"]>

export type ForumModeratorSectionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  moderatorId?: boolean
  sectionId?: boolean
  permissions?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  moderator?: boolean | Prisma.ForumModeratorDefaultArgs<ExtArgs>
  section?: boolean | Prisma.ForumSectionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["forumModeratorSection"]>

export type ForumModeratorSectionSelectScalar = {
  id?: boolean
  moderatorId?: boolean
  sectionId?: boolean
  permissions?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ForumModeratorSectionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "moderatorId" | "sectionId" | "permissions" | "createdAt" | "updatedAt", ExtArgs["result"]["forumModeratorSection"]>
export type ForumModeratorSectionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  moderator?: boolean | Prisma.ForumModeratorDefaultArgs<ExtArgs>
  section?: boolean | Prisma.ForumSectionDefaultArgs<ExtArgs>
}
export type ForumModeratorSectionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  moderator?: boolean | Prisma.ForumModeratorDefaultArgs<ExtArgs>
  section?: boolean | Prisma.ForumSectionDefaultArgs<ExtArgs>
}
export type ForumModeratorSectionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  moderator?: boolean | Prisma.ForumModeratorDefaultArgs<ExtArgs>
  section?: boolean | Prisma.ForumSectionDefaultArgs<ExtArgs>
}

export type $ForumModeratorSectionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ForumModeratorSection"
  objects: {
    moderator: Prisma.$ForumModeratorPayload<ExtArgs>
    section: Prisma.$ForumSectionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    /**
     * 主键ID
     */
    id: number
    /**
     * 关联的版主ID
     */
    moderatorId: number
    /**
     * 关联的板块ID
     */
    sectionId: number
    /**
     * 自定义权限数组（与版主基础权限做合并）
     */
    permissions: number[]
    /**
     * 创建时间
     */
    createdAt: Date
    /**
     * 更新时间
     */
    updatedAt: Date
  }, ExtArgs["result"]["forumModeratorSection"]>
  composites: {}
}

export type ForumModeratorSectionGetPayload<S extends boolean | null | undefined | ForumModeratorSectionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload, S>

export type ForumModeratorSectionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ForumModeratorSectionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: ForumModeratorSectionCountAggregateInputType | true
  }

export interface ForumModeratorSectionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ForumModeratorSection'], meta: { name: 'ForumModeratorSection' } }
  /**
   * Find zero or one ForumModeratorSection that matches the filter.
   * @param {ForumModeratorSectionFindUniqueArgs} args - Arguments to find a ForumModeratorSection
   * @example
   * // Get one ForumModeratorSection
   * const forumModeratorSection = await prisma.forumModeratorSection.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ForumModeratorSectionFindUniqueArgs>(args: Prisma.SelectSubset<T, ForumModeratorSectionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorSectionClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ForumModeratorSection that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ForumModeratorSectionFindUniqueOrThrowArgs} args - Arguments to find a ForumModeratorSection
   * @example
   * // Get one ForumModeratorSection
   * const forumModeratorSection = await prisma.forumModeratorSection.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ForumModeratorSectionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ForumModeratorSectionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorSectionClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ForumModeratorSection that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorSectionFindFirstArgs} args - Arguments to find a ForumModeratorSection
   * @example
   * // Get one ForumModeratorSection
   * const forumModeratorSection = await prisma.forumModeratorSection.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ForumModeratorSectionFindFirstArgs>(args?: Prisma.SelectSubset<T, ForumModeratorSectionFindFirstArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorSectionClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ForumModeratorSection that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorSectionFindFirstOrThrowArgs} args - Arguments to find a ForumModeratorSection
   * @example
   * // Get one ForumModeratorSection
   * const forumModeratorSection = await prisma.forumModeratorSection.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ForumModeratorSectionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ForumModeratorSectionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorSectionClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ForumModeratorSections that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorSectionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ForumModeratorSections
   * const forumModeratorSections = await prisma.forumModeratorSection.findMany()
   * 
   * // Get first 10 ForumModeratorSections
   * const forumModeratorSections = await prisma.forumModeratorSection.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const forumModeratorSectionWithIdOnly = await prisma.forumModeratorSection.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ForumModeratorSectionFindManyArgs>(args?: Prisma.SelectSubset<T, ForumModeratorSectionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ForumModeratorSection.
   * @param {ForumModeratorSectionCreateArgs} args - Arguments to create a ForumModeratorSection.
   * @example
   * // Create one ForumModeratorSection
   * const ForumModeratorSection = await prisma.forumModeratorSection.create({
   *   data: {
   *     // ... data to create a ForumModeratorSection
   *   }
   * })
   * 
   */
  create<T extends ForumModeratorSectionCreateArgs>(args: Prisma.SelectSubset<T, ForumModeratorSectionCreateArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorSectionClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ForumModeratorSections.
   * @param {ForumModeratorSectionCreateManyArgs} args - Arguments to create many ForumModeratorSections.
   * @example
   * // Create many ForumModeratorSections
   * const forumModeratorSection = await prisma.forumModeratorSection.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ForumModeratorSectionCreateManyArgs>(args?: Prisma.SelectSubset<T, ForumModeratorSectionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ForumModeratorSections and returns the data saved in the database.
   * @param {ForumModeratorSectionCreateManyAndReturnArgs} args - Arguments to create many ForumModeratorSections.
   * @example
   * // Create many ForumModeratorSections
   * const forumModeratorSection = await prisma.forumModeratorSection.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ForumModeratorSections and only return the `id`
   * const forumModeratorSectionWithIdOnly = await prisma.forumModeratorSection.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ForumModeratorSectionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ForumModeratorSectionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ForumModeratorSection.
   * @param {ForumModeratorSectionDeleteArgs} args - Arguments to delete one ForumModeratorSection.
   * @example
   * // Delete one ForumModeratorSection
   * const ForumModeratorSection = await prisma.forumModeratorSection.delete({
   *   where: {
   *     // ... filter to delete one ForumModeratorSection
   *   }
   * })
   * 
   */
  delete<T extends ForumModeratorSectionDeleteArgs>(args: Prisma.SelectSubset<T, ForumModeratorSectionDeleteArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorSectionClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ForumModeratorSection.
   * @param {ForumModeratorSectionUpdateArgs} args - Arguments to update one ForumModeratorSection.
   * @example
   * // Update one ForumModeratorSection
   * const forumModeratorSection = await prisma.forumModeratorSection.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ForumModeratorSectionUpdateArgs>(args: Prisma.SelectSubset<T, ForumModeratorSectionUpdateArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorSectionClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ForumModeratorSections.
   * @param {ForumModeratorSectionDeleteManyArgs} args - Arguments to filter ForumModeratorSections to delete.
   * @example
   * // Delete a few ForumModeratorSections
   * const { count } = await prisma.forumModeratorSection.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ForumModeratorSectionDeleteManyArgs>(args?: Prisma.SelectSubset<T, ForumModeratorSectionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ForumModeratorSections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorSectionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ForumModeratorSections
   * const forumModeratorSection = await prisma.forumModeratorSection.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ForumModeratorSectionUpdateManyArgs>(args: Prisma.SelectSubset<T, ForumModeratorSectionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ForumModeratorSections and returns the data updated in the database.
   * @param {ForumModeratorSectionUpdateManyAndReturnArgs} args - Arguments to update many ForumModeratorSections.
   * @example
   * // Update many ForumModeratorSections
   * const forumModeratorSection = await prisma.forumModeratorSection.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ForumModeratorSections and only return the `id`
   * const forumModeratorSectionWithIdOnly = await prisma.forumModeratorSection.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ForumModeratorSectionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ForumModeratorSectionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ForumModeratorSection.
   * @param {ForumModeratorSectionUpsertArgs} args - Arguments to update or create a ForumModeratorSection.
   * @example
   * // Update or create a ForumModeratorSection
   * const forumModeratorSection = await prisma.forumModeratorSection.upsert({
   *   create: {
   *     // ... data to create a ForumModeratorSection
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ForumModeratorSection we want to update
   *   }
   * })
   */
  upsert<T extends ForumModeratorSectionUpsertArgs>(args: Prisma.SelectSubset<T, ForumModeratorSectionUpsertArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorSectionClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorSectionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ForumModeratorSections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorSectionCountArgs} args - Arguments to filter ForumModeratorSections to count.
   * @example
   * // Count the number of ForumModeratorSections
   * const count = await prisma.forumModeratorSection.count({
   *   where: {
   *     // ... the filter for the ForumModeratorSections we want to count
   *   }
   * })
  **/
  count<T extends ForumModeratorSectionCountArgs>(
    args?: Prisma.Subset<T, ForumModeratorSectionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ForumModeratorSectionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ForumModeratorSection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorSectionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ForumModeratorSectionAggregateArgs>(args: Prisma.Subset<T, ForumModeratorSectionAggregateArgs>): Prisma.PrismaPromise<GetForumModeratorSectionAggregateType<T>>

  /**
   * Group by ForumModeratorSection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumModeratorSectionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ForumModeratorSectionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ForumModeratorSectionGroupByArgs['orderBy'] }
      : { orderBy?: ForumModeratorSectionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ForumModeratorSectionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetForumModeratorSectionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ForumModeratorSection model
 */
readonly fields: ForumModeratorSectionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ForumModeratorSection.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ForumModeratorSectionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  moderator<T extends Prisma.ForumModeratorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ForumModeratorDefaultArgs<ExtArgs>>): Prisma.Prisma__ForumModeratorClient<runtime.Types.Result.GetResult<Prisma.$ForumModeratorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  section<T extends Prisma.ForumSectionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ForumSectionDefaultArgs<ExtArgs>>): Prisma.Prisma__ForumSectionClient<runtime.Types.Result.GetResult<Prisma.$ForumSectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ForumModeratorSection model
 */
export interface ForumModeratorSectionFieldRefs {
  readonly id: Prisma.FieldRef<"ForumModeratorSection", 'Int'>
  readonly moderatorId: Prisma.FieldRef<"ForumModeratorSection", 'Int'>
  readonly sectionId: Prisma.FieldRef<"ForumModeratorSection", 'Int'>
  readonly permissions: Prisma.FieldRef<"ForumModeratorSection", 'Int[]'>
  readonly createdAt: Prisma.FieldRef<"ForumModeratorSection", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ForumModeratorSection", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ForumModeratorSection findUnique
 */
export type ForumModeratorSectionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionInclude<ExtArgs> | null
  /**
   * Filter, which ForumModeratorSection to fetch.
   */
  where: Prisma.ForumModeratorSectionWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModeratorSection findUniqueOrThrow
 */
export type ForumModeratorSectionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionInclude<ExtArgs> | null
  /**
   * Filter, which ForumModeratorSection to fetch.
   */
  where: Prisma.ForumModeratorSectionWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModeratorSection findFirst
 */
export type ForumModeratorSectionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionInclude<ExtArgs> | null
  /**
   * Filter, which ForumModeratorSection to fetch.
   */
  where?: Prisma.ForumModeratorSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumModeratorSections to fetch.
   */
  orderBy?: Prisma.ForumModeratorSectionOrderByWithRelationInput | Prisma.ForumModeratorSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ForumModeratorSections.
   */
  cursor?: Prisma.ForumModeratorSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumModeratorSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumModeratorSections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ForumModeratorSections.
   */
  distinct?: Prisma.ForumModeratorSectionScalarFieldEnum | Prisma.ForumModeratorSectionScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModeratorSection findFirstOrThrow
 */
export type ForumModeratorSectionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionInclude<ExtArgs> | null
  /**
   * Filter, which ForumModeratorSection to fetch.
   */
  where?: Prisma.ForumModeratorSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumModeratorSections to fetch.
   */
  orderBy?: Prisma.ForumModeratorSectionOrderByWithRelationInput | Prisma.ForumModeratorSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ForumModeratorSections.
   */
  cursor?: Prisma.ForumModeratorSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumModeratorSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumModeratorSections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ForumModeratorSections.
   */
  distinct?: Prisma.ForumModeratorSectionScalarFieldEnum | Prisma.ForumModeratorSectionScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModeratorSection findMany
 */
export type ForumModeratorSectionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionInclude<ExtArgs> | null
  /**
   * Filter, which ForumModeratorSections to fetch.
   */
  where?: Prisma.ForumModeratorSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumModeratorSections to fetch.
   */
  orderBy?: Prisma.ForumModeratorSectionOrderByWithRelationInput | Prisma.ForumModeratorSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ForumModeratorSections.
   */
  cursor?: Prisma.ForumModeratorSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumModeratorSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumModeratorSections.
   */
  skip?: number
  distinct?: Prisma.ForumModeratorSectionScalarFieldEnum | Prisma.ForumModeratorSectionScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModeratorSection create
 */
export type ForumModeratorSectionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionInclude<ExtArgs> | null
  /**
   * The data needed to create a ForumModeratorSection.
   */
  data: Prisma.XOR<Prisma.ForumModeratorSectionCreateInput, Prisma.ForumModeratorSectionUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModeratorSection createMany
 */
export type ForumModeratorSectionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ForumModeratorSections.
   */
  data: Prisma.ForumModeratorSectionCreateManyInput | Prisma.ForumModeratorSectionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ForumModeratorSection createManyAndReturn
 */
export type ForumModeratorSectionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * The data used to create many ForumModeratorSections.
   */
  data: Prisma.ForumModeratorSectionCreateManyInput | Prisma.ForumModeratorSectionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ForumModeratorSection update
 */
export type ForumModeratorSectionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionInclude<ExtArgs> | null
  /**
   * The data needed to update a ForumModeratorSection.
   */
  data: Prisma.XOR<Prisma.ForumModeratorSectionUpdateInput, Prisma.ForumModeratorSectionUncheckedUpdateInput>
  /**
   * Choose, which ForumModeratorSection to update.
   */
  where: Prisma.ForumModeratorSectionWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModeratorSection updateMany
 */
export type ForumModeratorSectionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ForumModeratorSections.
   */
  data: Prisma.XOR<Prisma.ForumModeratorSectionUpdateManyMutationInput, Prisma.ForumModeratorSectionUncheckedUpdateManyInput>
  /**
   * Filter which ForumModeratorSections to update
   */
  where?: Prisma.ForumModeratorSectionWhereInput
  /**
   * Limit how many ForumModeratorSections to update.
   */
  limit?: number
}

/**
 * ForumModeratorSection updateManyAndReturn
 */
export type ForumModeratorSectionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * The data used to update ForumModeratorSections.
   */
  data: Prisma.XOR<Prisma.ForumModeratorSectionUpdateManyMutationInput, Prisma.ForumModeratorSectionUncheckedUpdateManyInput>
  /**
   * Filter which ForumModeratorSections to update
   */
  where?: Prisma.ForumModeratorSectionWhereInput
  /**
   * Limit how many ForumModeratorSections to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ForumModeratorSection upsert
 */
export type ForumModeratorSectionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionInclude<ExtArgs> | null
  /**
   * The filter to search for the ForumModeratorSection to update in case it exists.
   */
  where: Prisma.ForumModeratorSectionWhereUniqueInput
  /**
   * In case the ForumModeratorSection found by the `where` argument doesn't exist, create a new ForumModeratorSection with this data.
   */
  create: Prisma.XOR<Prisma.ForumModeratorSectionCreateInput, Prisma.ForumModeratorSectionUncheckedCreateInput>
  /**
   * In case the ForumModeratorSection was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ForumModeratorSectionUpdateInput, Prisma.ForumModeratorSectionUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModeratorSection delete
 */
export type ForumModeratorSectionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionInclude<ExtArgs> | null
  /**
   * Filter which ForumModeratorSection to delete.
   */
  where: Prisma.ForumModeratorSectionWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ForumModeratorSection deleteMany
 */
export type ForumModeratorSectionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ForumModeratorSections to delete
   */
  where?: Prisma.ForumModeratorSectionWhereInput
  /**
   * Limit how many ForumModeratorSections to delete.
   */
  limit?: number
}

/**
 * ForumModeratorSection without action
 */
export type ForumModeratorSectionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumModeratorSection
   */
  select?: Prisma.ForumModeratorSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumModeratorSection
   */
  omit?: Prisma.ForumModeratorSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumModeratorSectionInclude<ExtArgs> | null
}
