export const PERMISSION_ERROR_MESSAGE = {
  WORK_NOT_FOUND: '作品不存在',
  CHAPTER_NOT_FOUND: '章节不存在',
  USER_NOT_FOUND: '用户不存在',
  MEMBER_LEVEL_INSUFFICIENT: '会员等级不足',
  REQUIRED_MEMBER_LEVEL_NOT_FOUND: '指定的阅读会员等级不存在',
  CHAPTER_PURCHASE_REQUIRED: '请先购买该章节',
  WORK_PURCHASE_UNSUPPORTED: '作品不支持购买权限，请使用会员权限',
  UNKNOWN_PERMISSION_TYPE: '未知的权限类型',
  WORK_DOWNLOAD_FORBIDDEN: '作品禁止下载',
  CHAPTER_DOWNLOAD_FORBIDDEN: '章节禁止下载',
  CHAPTER_ACCESS_REQUIRED: '请先登录',
}
