ALTER TABLE "admin_user_token" ADD COLUMN "geo_country" varchar(100);--> statement-breakpoint
ALTER TABLE "admin_user_token" ADD COLUMN "geo_province" varchar(100);--> statement-breakpoint
ALTER TABLE "admin_user_token" ADD COLUMN "geo_city" varchar(100);--> statement-breakpoint
ALTER TABLE "admin_user_token" ADD COLUMN "geo_isp" varchar(100);--> statement-breakpoint
ALTER TABLE "admin_user_token" ADD COLUMN "geo_source" varchar(50);--> statement-breakpoint
ALTER TABLE "app_user_token" ADD COLUMN "geo_country" varchar(100);--> statement-breakpoint
ALTER TABLE "app_user_token" ADD COLUMN "geo_province" varchar(100);--> statement-breakpoint
ALTER TABLE "app_user_token" ADD COLUMN "geo_city" varchar(100);--> statement-breakpoint
ALTER TABLE "app_user_token" ADD COLUMN "geo_isp" varchar(100);--> statement-breakpoint
ALTER TABLE "app_user_token" ADD COLUMN "geo_source" varchar(50);--> statement-breakpoint
ALTER TABLE "user_comment" ADD COLUMN "geo_country" varchar(100);--> statement-breakpoint
ALTER TABLE "user_comment" ADD COLUMN "geo_province" varchar(100);--> statement-breakpoint
ALTER TABLE "user_comment" ADD COLUMN "geo_city" varchar(100);--> statement-breakpoint
ALTER TABLE "user_comment" ADD COLUMN "geo_isp" varchar(100);--> statement-breakpoint
ALTER TABLE "user_comment" ADD COLUMN "geo_source" varchar(50);--> statement-breakpoint
ALTER TABLE "forum_topic" ADD COLUMN "geo_country" varchar(100);--> statement-breakpoint
ALTER TABLE "forum_topic" ADD COLUMN "geo_province" varchar(100);--> statement-breakpoint
ALTER TABLE "forum_topic" ADD COLUMN "geo_city" varchar(100);--> statement-breakpoint
ALTER TABLE "forum_topic" ADD COLUMN "geo_isp" varchar(100);--> statement-breakpoint
ALTER TABLE "forum_topic" ADD COLUMN "geo_source" varchar(50);--> statement-breakpoint
ALTER TABLE "forum_user_action_log" ADD COLUMN "geo_country" varchar(100);--> statement-breakpoint
ALTER TABLE "forum_user_action_log" ADD COLUMN "geo_province" varchar(100);--> statement-breakpoint
ALTER TABLE "forum_user_action_log" ADD COLUMN "geo_city" varchar(100);--> statement-breakpoint
ALTER TABLE "forum_user_action_log" ADD COLUMN "geo_isp" varchar(100);--> statement-breakpoint
ALTER TABLE "forum_user_action_log" ADD COLUMN "geo_source" varchar(50);--> statement-breakpoint
ALTER TABLE "sys_request_log" ADD COLUMN "geo_country" varchar(100);--> statement-breakpoint
ALTER TABLE "sys_request_log" ADD COLUMN "geo_province" varchar(100);--> statement-breakpoint
ALTER TABLE "sys_request_log" ADD COLUMN "geo_city" varchar(100);--> statement-breakpoint
ALTER TABLE "sys_request_log" ADD COLUMN "geo_isp" varchar(100);--> statement-breakpoint
ALTER TABLE "sys_request_log" ADD COLUMN "geo_source" varchar(50);